#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: "Check if PV {{ pv_name }} exists"
  shell: "kubectl get pv {{ pv_name }}"
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  register: pv_check
  failed_when: false
  changed_when: false

- name: "Get PV {{ pv_name }} to {{ tmp_workspace }}/{{ pv_name }}.yaml file"
  shell: "kubectl get pv {{ pv_name }} -o yaml > {{ tmp_workspace }}/{{ pv_name }}.yaml"
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  when: pv_check.rc == 0

- name: "Read PV {{ pv_name }} YAML file"
  slurp:
    src: "{{ tmp_workspace }}/{{ pv_name }}.yaml"
  register: pv_data_file

- name: "Parse the PV {{ pv_name }} YAML content"
  set_fact:
    pv_data: "{{ pv_data_file.content | b64decode | from_yaml }}"

- name: "Get pool ID for {{ new_pool }}"
  shell: "ceph osd lspools | grep ' {{ new_pool }}$' | awk '{print $1}'"
  register: pool_id_output

- name: "Extract pool ID"
  set_fact:
    new_pool_id: "{{ pool_id_output.stdout.strip() }}"

- name: "Update PV data attributes to point to pool {{ new_pool }}"
  set_fact:
    pv_data_updated: "{{ pv_data | combine(updated_volume_attributes, recursive=True) }}"
  vars:
    updated_volume_attributes:
      spec:
        csi:
          volumeAttributes:
            journalPool: "{{ new_pool }}"
            pool: "{{ new_pool }}"
          volumeHandle: "{{ pv_data.spec.csi.volumeHandle | regex_replace('000000000000000\\d', '000000000000000' + new_pool_id) }}"

- name: Show new PV manifest
  debug:
    var: pv_data_updated

- name: "Write new PV data to {{ tmp_workspace }}/{{ pv_name }}.yaml file"
  copy:
    content: "{{ pv_data_updated | to_nice_yaml }}"
    dest: "{{ tmp_workspace }}/{{ pv_name }}.yaml"

- name: "Replace PV {{ pv_name }} with updated attributes"
  command: "kubectl replace --force -f {{ tmp_workspace }}/{{ pv_name }}.yaml"
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  async: 60
  poll: 0
  register: replace_pv_job

- name: Show job register
  debug:
    var: replace_pv_job

- name: "Remove finalizer from PV {{ pv_name }}"
  command: >
    kubectl patch pv {{ pv_name }}
    -p '{"metadata":{"finalizers":null}}'
    --type=merge
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  ignore_errors: true

- name: Wait for the PV {{ pv_name }} replacement
  async_status:
    jid: "{{ replace_pv_job.ansible_job_id }}"
  register: replace_pv_job_result
  until: replace_pv_job_result is finished
  retries: 60
  delay: 1

- name: "Delete new PV {{ pv_name }} file"
  command: "rm -rf {{ tmp_workspace }}/{{ pv_name }}.yaml"
