---
#
# Copyright (c) 2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
#   This role is to check the service status, lock the controller-0 and mark
#   the completion of the enrollment
#

- name: Check service status after enrollment
  include_role:
    name: common/check-services-status

- name: Cleanup the cloud-init services
  command: /usr/local/bin/enroll-init-cleanup
  become: yes

- name: Lock controller-0
  include_role:
    name: common/host-lock
  vars:
    target_host: 'controller-0'

# In non-SX system, the controller-0 node will be tainted disabled during lock,
# remove the taint after locking the only controller.
- name: Remove disabled taint on controller-0 if not simplex
  command: kubectl taint nodes controller-0 services=disabled:NoExecute-
  environment:
    KUBECONFIG: "/etc/kubernetes/admin.conf"
  failed_when: false
  when: system_mode != 'simplex'

- name: Mark enrollment is completed
  file:
    path: "{{ subcloud_enrollment_completed_flag }}"
    state: touch
