---
#
# Copyright (c) 2024-2025 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
#   This role is to check the service status, lock the controller-0 and mark
#   the completion of the enrollment
#

- name: Check service status after enrollment
  include_role:
    name: common/check-services-status

# Ensure controller-0 is schedulable in non-simplex systems
- name: Ensure controller-0 is schedulable and taints are removed
  block:
    - name: Uncordon controller-0 node
      command: kubectl uncordon controller-0
      environment:
        KUBECONFIG: "/etc/kubernetes/admin.conf"
      failed_when: false
      register: uncordon_result

    - name: Remove services=disabled taint from controller-0
      command: kubectl taint nodes controller-0 services=disabled:NoExecute-
      environment:
        KUBECONFIG: "/etc/kubernetes/admin.conf"
      failed_when: false
      register: taint_removal_result

    - name: Debug uncordon and taint removal results
      debug:
        msg:
          - "Uncordon result: {{ uncordon_result.stdout }}"
          - "Taint removal result: {{ taint_removal_result.stdout }}"
  when: system_mode != 'simplex'

- name: Mark enrollment is completed
  file:
    path: "{{ subcloud_enrollment_completed_flag }}"
    state: touch

- name: Clear enrollment_in_progress flag
  file:
    path: /var/run/.enrollment_in_progress
    state: absent
  become: true

# We need to remove the seed and cloud-init services to avoid
# the system to be re-enrolled again. Only if the enrollment
# was successful. For that reason, we are adding this task
# to the end of the enrollment playbook.
- name: Clean up cloud-init and seed services
  shell: |
    /usr/local/bin/enroll-init-cleanup
    /var/lib/factory-install/run-cloud-init-from-seed.sh clean
  become: true
