---
#
# Copyright (c) 2022-2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# ROLE DESCRIPTION:
#   This will complete the restoration process.
#   Applying any missing changes or creating any missing flags
#   that are not created during optimized restore.

- set_fact:
    _remove_items:
      - "{{ ansible_remote_tmp|default('') }}"
      - "{{ override_files_dir }}/{{ override_filename }}"
      - "{{ target_backup_dir }}/{{ override_filename }}"

- set_fact:
    _restore_remove_items:
      - "{{ platform_backup_fqpn }}"
      - "{{ registry_backup_fqpn|default('') }}"
  when: initial_backup_dir != target_backup_dir

- block:
  - set_fact:
      _encrypted_remove_items:
        - "{{ encrypted_backup_filepath }}"
    when: not on_box_data|bool

  - set_fact:
      _decrypted_remove_items:
        - "{{ decrypted_backup_filepath }}"
    when: initial_backup_dir == target_backup_dir
  when: platform_tarball_encrypted|bool

- set_fact:
    _upgrade_remove_items:
      - "{{ temp_upgrade_platform_dir }}"
      - "{{ mini_restore_data_file | default('') }}"
      - "{{ patching_restore_data_file | default('') }}"
  when: upgrade_in_progress

- name: Remove temporary files and directories used during restore
  file:
    path: "{{ item }}"
    state: absent
  loop: >
    {{
      _remove_items + _restore_remove_items|default([])
      + _upgrade_remove_items|default([])
      + _encrypted_remove_items|default([])
      + _decrypted_remove_items|default([])
      | reject('equalto', '')
    }}

- name: Combine required flags
  set_fact:
    all_required_flags: "{{ default_required_flags + extra_required_flags }}"

- name: Set restore in progress for sysinv
  shell: "source /etc/platform/openrc; system restore-start"

# Optimized restore does not create all the required flags.
# Any missing flags will be created here.
- name: Set flags for puppet
  file:
    path: "{{ (flags_dir, item) | path_join }}"
    state: touch
  loop: "{{ all_required_flags }}"

# If the system is online, restore was most likely successful.
# Network instability on management network can
# cause system to not be online immediately.
- name: Check if system is in online state
  shell: source /etc/platform/openrc; system host-show controller-0 --column availability --format value
  register: check_online
  retries: "{{ system_online_retries }}"
  delay: "{{ system_online_retry_delay }}"
  until: check_online.stdout == "online"

# When controller unlock occurs there is a chance platform-integ-apps
# has not yet been completely removed. This causes the running removal to abort
# and sets the state from removing to remove-failed. This removal is necessary
# to ensure that the platform-integ-apps will be reapplied after the unlock.
# This new task will be executed only if the wipe_ceph_osds is set to true.

- name: Check if platform-integ-apps is in uploaded state
  shell: |
    source /etc/platform/openrc
    system application-show platform-integ-apps --column status --format value
  register: check_uploaded
  retries: "{{ application_check_retries }}"
  delay: "{{ application_check_retry_delay }}"
  until: check_uploaded.stdout == "uploaded"
  when: wipe_ceph_osds|bool and ceph_backend.rc == 0
