#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Display current DM file name
  debug:
    var: current_dm_file_name

- name: Set final DM file name
  set_fact:
    final_dm_file_name: "{{ storage_backend_migration_target }}-migration-{{ dm_system_name }}-dm-file.yaml"
    cacheable: true

- name: Set final DM full file path
  set_fact:
    final_dm_full_file_path: "{{ storage_backend_migration_backup_dir }}/{{ final_dm_file_name }}"
    cacheable: true

- name: Display final DM full file path
  debug:
    var: final_dm_full_file_path

- name: "Ensure {{ storage_backend_migration_backup_dir }} exist"
  file:
    path: "{{ storage_backend_migration_backup_dir }}"
    state: directory
    mode: "0644"

- name: "Copy new DM file to final destination ({{ final_dm_full_file_path }})"
  copy:
    src: "{{ tmp_workspace }}/{{ current_dm_file_name }}"
    dest: "{{ final_dm_full_file_path }}"
    remote_src: true
    mode: "0644"
