#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Display DM script name
  debug:
    var: dm_script_name

- name: Display target DM file name
  debug:
    var: target_dm_file_name

- name: "Check if {{ target_dm_file_name }} already exists"
  stat:
    path: "{{ tmp_workspace }}/{{ target_dm_file_name }}"
  register: target_dm_file
  changed_when: false

- name: "Generate {{ target_dm_file_name }} only if it does NOT exist yet"
  block:
    - name: Apply change to DM file
      shell: "{{ tmp_workspace }}/{{ dm_script_name }} {{ tmp_workspace }}/{{ current_dm_file_name }} | tee {{ tmp_workspace }}/{{ target_dm_file_name }}"
      register: dm_change_output

    - name: Debug dm_change_output
      debug:
        var: dm_change_output.stdout_lines
  when: not target_dm_file.stat.exists

- name: Set DM name for next stage
  set_fact:
    current_dm_file_name: "{{ target_dm_file_name }}"
    cacheable: true

- name: Display current DM file name
  debug:
    var: current_dm_file_name
