#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Set DM system name variable
  block:
    - name: Get system name
      command: kubectl -n deployment get system -o jsonpath='{.items[].metadata.name}'
      environment:
        KUBECONFIG: "{{ kubeconfig }}"
      register: dm_system_name_output
      changed_when: false

    - name: Set variable for system name
      set_fact:
        dm_system_name: "{{ dm_system_name_output.stdout | trim }}"
        cacheable: true
  when: dm_system_name is undefined

- name: Display DM system name
  debug:
    var: dm_system_name

- name: Check if full-system-dm-file.yaml already exists
  stat:
    path: "{{ tmp_workspace }}/full-system-dm-file.yaml"
  register: full_file
  changed_when: false

- name: Generate full-system-dm-file.yaml only if it does NOT exist yet
  block:
    - name: Get full DM file
      environment: "{{ system_env }}"
      command: >
        deployctl build
        --no-ca-certificates
        -s {{ dm_system_name }} -o {{ tmp_workspace }}/full-system-dm-file.yaml
      register: deployctl_output
      failed_when: false # it returns non-zero if generates the file with warnings

    - name: Debug deployctl_output
      debug:
        var: deployctl_output.stdout_lines
  when: not full_file.stat.exists

- name: Check if full-system-dm-file.yaml was created
  stat:
    path: "{{ tmp_workspace }}/full-system-dm-file.yaml"
  register: full_dm_file
  changed_when: false

- name: Fail if full DM file was not generated
  fail:
    msg: "full-system-dm-file.yaml not generated by deployctl"
  when: not full_dm_file.stat.exists

- name: Set DM name for next stage
  set_fact:
    current_dm_file_name: "full-system-dm-file.yaml"
    cacheable: true

- name: Display DM file name
  debug:
    var: current_dm_file_name
