#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: "Check if PVC {{ pvc_map[pv_name].name }}-new exists"
  shell: "kubectl get pvc -n {{ pvc_map[pv_name].namespace }} {{ pvc_map[pv_name].name }}-new"
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  register: pvc_check
  failed_when: false
  changed_when: false
  when: ( 'new' not in pv_name )

- block:
  - name: Render recreate_pvc.py using template
    template:
      src: recreate_pvc.py.j2
      dest: "{{ tmp_workspace }}/recreate_pvc.py"
      mode: 0644
    vars:
      pvc_name: "{{ pvc_map[pv_name].name }}"
      sufix: "new"
      new_volume: true
      is_backup: true
    register: python_script_creation
    failed_when: python_script_creation.failed

  - name: "Execute recreate PVC script for {{ pvc_map[pv_name].name }}"
    command: "python {{ tmp_workspace }}/recreate_pvc.py"

  - name: "Apply backup PVC {{ pvc_map[pv_name].name }} file"
    command: "kubectl apply -f {{ tmp_workspace }}/{{ pvc_map[pv_name].name }}.yaml.bkp"
    environment:
      KUBECONFIG: "{{ kubeconfig }}"

  when:
    - pvc_check is defined
    - pvc_check.rc != 0

- name: "Set new PVC name"
  set_fact:
    new_pvc_name: "{{ pvc_map[pv_name].name }}-new"

- name: "Wait for pvc to be completed for migration from PV {{ pv_name }}"
  command: kubectl get pvc -n {{ pvc_map[pv_name].namespace }} {{ new_pvc_name }} -o 'jsonpath={.status.phase}'
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  register: temp_pv_status
  until: "'Bound' in temp_pv_status.stdout"
  retries: 60
  delay: 10
  changed_when: false
  failed_when:
    - "'Bound' not in temp_pv_status.stdout"

- name: "Save pvc {{ new_pvc_name }} to {{ tmp_workspace }}/{{ new_pvc_name }}.yaml file"
  shell: "kubectl get pvc -n {{ pvc_map[pv_name].namespace }} {{ new_pvc_name }} -o yaml | tee {{ tmp_workspace }}/{{ new_pvc_name }}.yaml"
  environment:
    KUBECONFIG: "{{ kubeconfig }}"

- name: Read pvc {{ new_pvc_name }} YAML file
  slurp:
    src: "{{ tmp_workspace }}/{{ new_pvc_name }}.yaml"
  register: new_pvc_data_file

- name: Parse the pvc {{ new_pvc_name }} YAML content
  set_fact:
    new_pvc_data: "{{ new_pvc_data_file.content | b64decode | from_yaml }}"

- name: "Set new PV name"
  set_fact:
    new_pv_name: "{{ new_pvc_data.spec.volumeName }}"

- name: "Check if PV {{ new_pv_name }} exists"
  shell: "kubectl get pv {{ new_pv_name }}"
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  register: new_pv_check
  failed_when: false
  changed_when: false

- name: "Save PV {{ new_pv_name }} to {{ tmp_workspace }}/{{ new_pv_name }}.yaml file"
  shell: "kubectl get pv {{ new_pv_name }} -o yaml | tee {{ tmp_workspace }}/{{ new_pv_name }}.yaml {{ tmp_workspace }}/{{ new_pv_name }}.yaml.bkp"
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  when: new_pv_check.rc == 0
