#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Render recreate_pvc.py using template
  template:
    src: recreate_pvc.py.j2
    dest: "{{ tmp_workspace }}/recreate_pvc.py"
    mode: 0644
  vars:
    pvc_name: "{{ pvc_map[pv_name].name }}"
  register: python_script_creation
  failed_when: python_script_creation.failed

- name: "Execute recreate PVC script for {{ pvc_map[pv_name].name }}"
  command: "python {{ tmp_workspace }}/recreate_pvc.py"

- name: "Check if PVC {{ pvc_map[pv_name].name }}-old exists"
  shell: "kubectl get pvc -n {{ pvc_map[pv_name].namespace }} {{ pvc_map[pv_name].name }}-old"
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  register: pvc_check
  failed_when: false
  changed_when: false

- name: "Apply new PVC {{ pvc_map[pv_name].name }} file"
  command: "kubectl apply -f {{ tmp_workspace }}/{{ pvc_map[pv_name].name }}.yaml"
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  when: pvc_check.rc | default(0) != 0
