#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Export system variables
  include_tasks: system_env.yaml

- name: Set ansible_become_pass
  set_fact:
    ansible_become_pass: "{{ system_env.OS_PASSWORD }}"
  no_log: true
  when: ansible_become_pass is undefined

- name: Set ansible_password
  set_fact:
    ansible_password: "{{ system_env.OS_PASSWORD }}"
  no_log: true
  when: ansible_password is undefined

- name: Retrieve hosts
  become: true
  become_user: postgres
  command: >
    psql -d sysinv -t -A -F','
    -c "SELECT hostname, personality FROM i_host
        WHERE hostname IS NOT NULL AND PERSONALITY IS NOT NULL;"
  register: host_list_output
  changed_when: false

- name: Build hosts list from database
  set_fact:
    _db_hosts: "{{ _db_hosts | default([]) + [{'hostname': item.split(',')[0], 'personality': item.split(',')[1]}] }}"
  loop: "{{ host_list_output.stdout_lines }}"
  loop_control:
    label: "{{ item }}"

- name: Update hosts if undefined or count mismatch
  set_fact:
    hosts: "{{ _db_hosts }}"
    cacheable: true
  when: hosts is undefined or (hosts | length) != (_db_hosts | length)

- name: Show list of hosts retrieved
  debug:
    var: hosts

- name: Import tasks to gather system information
  import_tasks: system_info.yaml

- name: Import tasks to discover hosts and add them to inventory
  import_tasks: discover_hosts.yaml
  tags: discover_hosts
