#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Export system variables
  include_tasks: system_env.yaml

- name: Set ansible_become_pass
  set_fact:
    ansible_become_pass: "{{ system_env.OS_PASSWORD }}"
  no_log: true
  when: ansible_become_pass is undefined

- name: Set ansible_password
  set_fact:
    ansible_password: "{{ system_env.OS_PASSWORD }}"
  no_log: true
  when: ansible_password is undefined

- name: Set hosts if undefined
  block:
    - name: Retrieve hosts
      become: true
      become_user: postgres
      command: >
        psql -d sysinv -t -A -F','
        -c "SELECT hostname, personality FROM i_host;"
      register: host_list_output
      changed_when: false

    - name: Parse SQL output into list of dicts
      set_fact:
        hosts: >-
          [
            {% for line in host_list_output.stdout_lines %}
            {"hostname": "{{ line.split(',')[0] }}", "personality": "{{ line.split(',')[1] }}"}{% if not loop.last %},{% endif %}
            {% endfor %}
          ]
        cacheable: true
  when: hosts is undefined

- name: Show list of hosts retrieved
  debug:
    var: hosts

- name: Import tasks to gather system information
  import_tasks: system_info.yaml

- name: Import tasks to discover hosts and add them to inventory
  import_tasks: discover_hosts.yaml
  tags: discover_hosts
