#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Export system variables
  shell: |
    set -a
    source /etc/platform/openrc
    env
  register: env_output
  failed_when: "'Openstack Admin credentials can only be loaded from the active controller.' in env_output.stdout"
  when: system_env is undefined

- name: Gather wanted variables
  set_fact:
    system_env: >-
      {{
        system_env | default({}) | combine({
          item:
            (env_output.stdout_lines
            | select('match', '^' ~ item ~ '=')
            | list
            | first
            | default('')
            | regex_replace('^' ~ item ~ '=', ''))
        })
      }}
    cacheable: true
  loop:
    - OS_ENDPOINT_TYPE
    - CINDER_ENDPOINT_TYPE
    - OS_USERNAME
    - OS_PASSWORD
    - OS_AUTH_TYPE
    - OS_AUTH_URL
    - OS_PROJECT_NAME
    - OS_USER_DOMAIN_NAME
    - OS_PROJECT_DOMAIN_NAME
    - OS_IDENTITY_API_VERSION
    - OS_REGION_NAME
    - OS_INTERFACE
  loop_control:
    label: "{{ item }}"
    extended: true
  when: system_env is undefined or system_env | length < ansible_loop.length
