#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Export platform variables
  shell: |
    set -a
    source /etc/platform/platform.conf
    env
  register: platform_output
  when: platform is undefined

- name: Gather wanted variables from platform.conf
  set_fact:
    platform: >-
      {{
        platform | default({}) | combine({
          item:
            (platform_output.stdout_lines
            | select('match', '^' ~ item ~ '=')
            | list
            | first
            | default('')
            | regex_replace('^' ~ item ~ '=', ''))
        })
      }}
    cacheable: true
  vars:
  loop:
    - sw_version
    - system_type
    - system_mode
  loop_control:
    label: "{{ item }}"
    extended: true
  when: platform is undefined or platform | length < ansible_loop.length

- name: Set system additional details if undefined
  set_fact:
    has_worker: "{{ 'worker' in hosts | map(attribute='personality') }}"
    has_storage: "{{ 'storage' in hosts | map(attribute='personality') }}"
    cacheable: true
  when: has_worker is undefined or has_storage is undefined

- name: Determine system deployment
  set_fact:
    system_deployment: >-
      {%- if (platform.system_type, platform.system_mode) == ('All-in-one', 'simplex') -%}
      AIO-SX
      {%- elif (platform.system_type, platform.system_mode) == ('All-in-one', 'duplex') -%}
      {%- if has_worker -%}
      AIO-DX+
      {%- else -%}
      AIO-DX
      {%- endif -%}
      {%- elif (platform.system_type, platform.system_mode) == ('Standard', 'duplex') -%}
      {%- if has_storage -%}
      STORAGE
      {%- else -%}
      STANDARD
      {%- endif -%}
      {%- endif -%}
    cacheable: true
  when: system_deployment is undefined

- name: Fail if system mode is not defined
  fail:
    msg: "system_deployment could not be determined"
  when: system_deployment is undefined or system_deployment | length == 0
