#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Validate data integrity of the generated pool list
  set_fact:
    invalid_pool_fields: >-
      [
        {% set pools_data = all_pools_list %}
        {% for pool in pools_data %}

          {% set mandatory_fields = ['name', 'id', 'pg_num', 'pgp_num', 'crush_rule', 'size', 'min_size', 'application'] %}

          {% for field in mandatory_fields %}
            {% if pool[field] is not defined or pool[field] is none or pool[field] | string | length == 0 %}
               "Pool '{{ pool.name | default('Unknown') }}': Field '{{ field }}' is empty or null",
            {% endif %}
          {% endfor %}

        {% endfor %}
      ]
  when: all_pools_list is defined and all_pools_list | length > 0

- block:
    - name: Show validation errors details
      debug:
        msg: "{{ invalid_pool_fields }}"

    - name: Fail due to data integrity issues
      fail:
        msg: "FAILURE: Integrity check failed. See the list above for details."
  when: invalid_pool_fields is defined and invalid_pool_fields | length > 0
