#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Check Ceph cluster status
  command: timeout 30 ceph -s
  register: ceph_status
  changed_when: false

- name: Ceph Cluster status
  debug:
    var: ceph_status.stdout_lines

- name: Check Ceph cluster health
  command: timeout 30 ceph health detail
  register: ceph_health_detail
  failed_when: >
    ceph_health_detail.rc != 0 or
    ('HEALTH_OK' not in ceph_health_detail.stdout)
  changed_when: false

- name: Ceph Cluster health result
  debug:
    var: ceph_health_detail.stdout_lines
