#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Try to restore RBD
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  block:
    - name: Create toolbox pod with backup path
      template:
        src: pod-migration-import-rbd.yaml.j2
        dest: "{{ tmp_workspace }}/pod-migration-import-rbd.yaml"
        mode: 0644
      vars:
        pvc_name: "{{ item }}"
      register: pod_file_created
      changed_when: false
      failed_when: pod_file_created.failed

    - name: Apply pod
      command: "kubectl apply -f {{ tmp_workspace }}/pod-migration-import-rbd.yaml"
      register: apply_pod_result

    - name: Wait for migration-import-rbd pod to be applied
      command: kubectl -n rook-ceph get pods migration-import-rbd -o 'jsonpath={.status.phase}'
      register: toolbox_pod_applied
      until: "'Running' in toolbox_pod_applied.stdout"
      retries: 60
      delay: 10
      changed_when: false
      failed_when:
        - "'Running' not in toolbox_pod_applied.stdout"

    - name: Import RBD backup file
      shell: |
        kubectl -n rook-ceph exec migration-import-rbd -- bash -c '
        set -o pipefail

        cd /backup || { echo "ERROR: /backup dir not found"; exit 1; }

        for pool_dir in *; do
          if [ -d "$pool_dir" ]; then
            pool_name="$pool_dir"
            echo "Processing Pool Directory: $pool_name"

            if ! ceph osd pool ls | grep -q "^${pool_name}$"; then
              echo "ERROR: Pool ${pool_name} does not exist in destination."
              exit 1
            fi

            for backup_file in "$pool_dir"/*.bkp.gz; do
              [ -e "$backup_file" ] || continue

              obj_name=$(basename "$backup_file" .bkp.gz)

              if rbd info "${pool_name}/${obj_name}" >/dev/null 2>&1; then
                echo "Skipping ${pool_name}/${obj_name}: image already exists"
                continue
              fi

              echo "Restoring image: ${pool_name}/${obj_name}..."

              gunzip -c "$backup_file" | rbd import --export-format 2 - "${pool_name}/${obj_name}"

              if [[ $? -ne 0 ]]; then
                echo "Retrying: trying import format 1 for ${pool}/${obj_name}"
                rbd rm "${pool_name}/${obj_name}" 2>/dev/null || true
                gunzip -c "$backup_file" | rbd import --export-format 1 - "${pool_name}/${obj_name}" \
                || { echo "ERROR: import/gunzip failed"; exit 1; }
              fi
            done
          fi
          echo "pool ${pool_dir} images:"
          rbd ls "${pool_dir}"
        done

        echo "SUCCESS: Restore process finished."
        '
      environment:
        KUBECONFIG: "{{ kubeconfig }}"
      register: import_result
      changed_when: import_result.rc == 0

    - name: Show import result
      debug:
        var: import_result.stdout_lines

  always:
    - name: Cleanup migration-import-rbd pod
      command: "kubectl delete -f {{ tmp_workspace }}/pod-migration-import-rbd.yaml --ignore-not-found=true"
      environment:
        KUBECONFIG: "{{ kubeconfig }}"
