#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

rook_pod_path: "/var/lib/rook"
rook_base_pod: "{{ rook_pod_path }}/rook-ceph"

rook_base: "/var/lib/ceph/data"
rook_base_host: "{{ rook_base }}/rook-ceph"

fs_name: "kube-cephfs"
data_pool_name: "kube-cephfs-data"
metadata_pool_name: "kube-cephfs-metadata"
rook_ceph_manifests:
  - filesystem.yaml

rook_ceph_template_manifests:
  - name: rook-recovery.yaml
    vars:
      ceph_image: "{{ images.ceph.reef }}"
