---
#
# Copyright (c) 2022-2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# ROLE DESCRIPTION:
#   This role is used to perform the copy of ostree_repo from the release feed
#   (/www/pages/feed/rel-<release>/ostree_repo) to the prestage directory
#   (/opt/platform-backup/<release>).
#
#   If the prestage request release is the same as the software version of
#   the subcloud, the source ostree_repo will be locally, otherwise, it will
#   be on the system controller.
#
#   This role is specifically for Debian releases.
#

- name: Set target prestage repo path
  set_fact:
    prestage_ostree_repo: "{{ prestage_dir }}/ostree_repo"

- name: Ensure target prestage repo path exist
  file:
    path: "{{ prestage_ostree_repo }}"
    state: directory
    owner: root
    mode: 0755
    recurse: yes

- name: Copy prestaging repo from local ostree repo
  command: rsync -ap --delete {{ ostree_repo_release_feed }}/ {{ prestage_ostree_repo }}/
  when: prestage_source == 'local'

- block:
  # It's necessary to temporarily change the owner to sysadmin so that
  # the system controller can push the files to the subcloud, since the files
  # are in the folders only the root can access but the synchronize only
  # support passwordless sysadmin to execute ssh and rsync.
  - name: Temporarily change the ownership of the prestage ostree repo on {{ inventory_hostname }}
    file:
      path: "{{ prestage_ostree_repo }}"
      state: directory
      owner: sysadmin
      recurse: yes

  - name: Transfer prestaging repo from system controller to {{ inventory_hostname }}
    synchronize:
      mode: push
      src: "{{ ostree_repo_release_feed }}/"
      dest: "{{ prestage_ostree_repo }}/"
      rsync_opts:
        - "--delete"
        - "--chmod=ugo+rw"
        - "--exclude=*/~.tmp~"
    register: prestage_transfer
    retries: 3
    delay: 5
    until: prestage_transfer.rc == 0

  - name: Restore the ownership of the prestage ostree repo on {{ inventory_hostname }}
    file:
      path: "{{ prestage_ostree_repo }}"
      state: directory
      owner: root
      recurse: yes

  when: prestage_source == 'remote'

- name: Generate ostree_repo directory checksum
  shell: >-
    cd {{ prestage_dir }}
    &&  find ostree_repo -type f -exec md5sum {} + | LC_ALL=C sort | md5sum | awk '{ print $1; }'
    > .ostree_repo_checksum

- name: Mark feed release as prestaged for install
  file:
    path: "{{ prestage_dir }}/{{ for_install_flag_file }}"
    state: touch
