#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: "Ensure {{ tmp_workspace }} exist"
  file:
    path: "{{ tmp_workspace }}"
    state: directory

- name: Export RBD and CephFs backups
  block:

    - name: Create backup folders
      include_tasks: create_backups_folders.yaml

    - name: Create backup folders
      loop: "{{ hostvars[system.active_controller]['cephfs_pvcs_by_namespace'] | default({}) | dict2items }}"
      debug:
        var: item

    - name: Create CephFS data backup
      include_tasks: create_cephfs_backup.yaml
      loop: "{{ hostvars[system.active_controller]['cephfs_pvcs_by_namespace'] | default({}) | dict2items }}"
      vars:
        cephfs_pvc_namespace: "{{ item.key }}"
        cephfs_pvc_list: "{{ item.value }}"
      when:
        - hostvars[system.active_controller]['cephfs_pvcs_by_namespace'] is defined
        - hostvars[system.active_controller]['cephfs_pvcs_by_namespace'] | length > 0

    - name: Create RBD data backup
      include_tasks: create_rbd_backup.yaml
      when: hostvars[system.active_controller]['rbd_pvcs_names'] | length > 0

  rescue:
    - name: Cleanup copied backups
      command: rm -rf {{ backups_path }}/*
      environment: "{{ system_env }}"
      ignore_errors: true
      args:
        warn: false

    - name: Capture failure details
      set_fact:
        failure_msg: >
          Task '{{ ansible_failed_task.name }}' failed.
          Error: {{ ansible_failed_result.msg | default('No error message captured.') }}

    - name: Force playbook failure
      fail:
        msg: "{{ failure_msg }}"

  always:
    - name: "Cleanup {{ tmp_workspace }}"
      file:
        path: "{{ tmp_workspace }}"
        state: absent
