#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Get rook-ceph-tool pod name
  shell: kubectl get pods -n rook-ceph | awk '/rook-ceph-tool/ {print $1}'
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  register: tool_pod
  changed_when: false
  when: inventory_hostname in groups.active_controller

- name: "Wait {{ tool_pod.stdout }} pod to be Running"
  command: kubectl get pods {{ tool_pod.stdout }} -n rook-ceph -o 'jsonpath={.status.phase}'
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  register: tool_pod_running
  until: "'Running' in tool_pod_running.stdout"
  retries: 60
  delay: 10
  changed_when: false
  failed_when:
    - "'Running' not in tool_pod_running.stdout"
  when: inventory_hostname in groups.active_controller

- name: Copy ceph config from tool pod
  command: kubectl cp -n rook-ceph {{ tool_pod.stdout }}:/etc/ceph /etc/ceph
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  when: inventory_hostname in groups.active_controller

- name: Copy all Ceph configuration files from active controller
  shell: >
    SSHPASS='{{ ansible_password }}' sshpass -e
    rsync -vrpP -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    sysadmin@{{ groups.active_controller | first }}:/etc/ceph /etc/ceph
  register: copy_result
  when: inventory_hostname not in groups.active_controller

- name: Render rook-ceph manifests to remote
  delegate_to: "{{ system.active_controller }}"
  template:
    src: "{{ role_path_common }}/templates/rook-recovery.yaml.j2"
    dest: "{{ tmp_workspace }}/rook-recovery-{{ inventory_hostname }}.yaml"

- name: Delete rook-ceph-recovery jobs
  delegate_to: "{{ system.active_controller }}"
  shell: kubectl delete job -n rook-ceph rook-ceph-recovery-{{ inventory_hostname }} --ignore-not-found
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  changed_when: true

- name: Wait for rook-ceph-recovery pods to terminate
  delegate_to: "{{ system.active_controller }}"
  shell: |
    kubectl get pods -n rook-ceph -o name \
    | grep '^pod/rook-ceph-recovery-{{ inventory_hostname }}' || true
  register: recovery_pods
  retries: 60
  delay: 10
  until: recovery_pods.stdout == ""
  environment:
    KUBECONFIG: "{{ kubeconfig }}"

- name: Apply rook-recovery-deploy.yaml
  delegate_to: "{{ system.active_controller }}"
  command: kubectl apply -f {{ tmp_workspace }}/rook-recovery-{{ inventory_hostname }}.yaml
  environment:
    KUBECONFIG: "{{ kubeconfig }}"

- name: "Wait for rook-ceph-recovery pods to be Running"
  delegate_to: "{{ system.active_controller }}"
  shell: |
    kubectl get pods -n rook-ceph --field-selector=status.phase!=Running -o name \
    | grep '^pod/rook-ceph-recovery-{{ inventory_hostname }}' || true
  register: recovery_pods
  retries: 60
  delay: 10
  until: recovery_pods.stdout == ""
  changed_when: false
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
