#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Delete rook-ceph-recovery jobs
  delegate_to: "{{ system.active_controller }}"
  shell: kubectl delete job -n rook-ceph rook-ceph-recovery-{{ inventory_hostname }} --ignore-not-found
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  changed_when: true

- name: Wait for rook-ceph-recovery pods to terminate
  delegate_to: "{{ system.active_controller }}"
  shell: |
    kubectl get pods -n rook-ceph -o name \
    | grep '^pod/rook-ceph-recovery-{{ inventory_hostname }}' || true
  register: recovery_pods
  retries: 60
  delay: 10
  until: recovery_pods.stdout == ""
  environment:
    KUBECONFIG: "{{ kubeconfig }}"

- name: Delete rook-recovery-deploy
  delegate_to: "{{ system.active_controller }}"
  command: kubectl delete -f {{ tmp_workspace }}/rook-recovery-{{ inventory_hostname }}.yaml --ignore-not-found
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
