---
#
# Copyright (c) 2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# This playbook provides the capability to disable IPsec on all hosts
# in a multi node system, such as AIO-DX, Stanadard, etc.
#
# The playbook is supposed to run on Active controller.
#
# Example to run the playbook:
# ansible-playbook /usr/share/ansible/stx-ansible/playbooks/roles/disable-ipsec.yml \
#   -e "ansible_ssh_user=sysadmin ansible_ssh_pass=<ssh_passwd> ansible_become_pass=<sudo passwd>"
#

- hosts: all
  gather_facts: no

  roles:
    - role: configure-ipsec/update_heartbeat_failure_action
      vars:
        action: 'alarm'
    - role: configure-ipsec/disable-ipsec-on-nodes
      become: yes
    - role: configure-ipsec/cleanup-after-disable-ipsec
      become: yes
    - role: configure-ipsec/update_heartbeat_failure_action
      vars:
        action: 'fail'
