---
#
# Copyright (c) 2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
#   This playbook convert a factory installed system into a subcloud of a
#   distributed cloud system.
#
#   Example command:
#   ansible-playbook /usr/share/ansible/stx-ansible/playbooks/enroll_subcloud.yml \
#   -i <inventory-file> --limit <subcloudname> -e '@<subcloudname>.yml'
#   -e 'override_files_dir=<overrides-files-dir>'
#

- hosts: all
  gather_facts: no

  vars_files:
    - vars/common/main.yml
    - host_vars/enroll-subcloud/default.yml

  vars:
    mode: "enroll"
    distributed_cloud_role: "subcloud"

  # TODO(yuxing) uncomment the roles below onces enabled the support of subcloud enrollment
  roles:
    - common/prepare-env
    - common/validate-target
    - common/recover-subcloud-certificates
    - role: rehome-enroll-common/recover-essential-services
      become: yes
    - rehome-enroll-common/prepare-env
    - enroll-subcloud/validate-before-enroll
    - rehome-enroll-common/update-ca-cert
    - role: common/update-sc-cert
      when: subcloud_dc_admin_ep_cert_chain_recovered is undefined
    - role: rehome-enroll-common/update-keystone-data
      become: yes
    - rehome-enroll-common/persist-configuration
    - common/update-sc-admin-endpoints
    # - enroll-subcloud/complete-enrollment
