---
#
# Copyright (c) 2022-2025 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# This playbook copies  ostree repo (Debian) from
# /var/www/pages/feed/rel-<release>) to the prestage directory
# (/opt/platform-backup/<release>).
# The playbook is meant to be integrated with the dcmanager to provide
# subcloud prestaging functionality.
#
# Usage:
#   ansible-playbook prestage_sw_packages.yml -i <inventory-file> \
#      -e "software_version=<MM.mm> prestage_reason=<for_install|for_sw_deploy>"

- hosts: all
  gather_facts: false

  vars:
    prestage_type: "packages"
    prestage_reason: for_install
    platform_backup_dir: /opt/platform-backup
    for_install_flag_file: ".ostree_rsync_completed"

  roles:
    - role: prestage/prepare-env

    - role: prestage/sync-software-metadata
      when: prestage_reason == 'for_sw_deploy'
      vars:
        ansible_become_pass: "{{ ansible_ssh_pass }}"

    - role: prestage/prestage-sw-packages
      when: prestage_reason == 'for_install'
      become: true

    - role: prestage/prestage-patches
      when: prestage_reason == 'for_install'
      become: true

    - role: prestage/get-prestage-versions
      become: true
