---
#
# Copyright (c) 2022-2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# This playbook downloads container images, generates image archive files
# and stores them in /opt/platform-backup/<release-number> in preparation
# for subcloud upgrade or reinstall. The playbook is meant to be integrated
# with the dcmanager to provide subcloud prestaging functionality.
#
# Usage:
#   ansible-playbook prestage_images.yml -i <inventory-file> \
#      -e "software_version=<MM.mm> image_list_file=<images-file>"
#
# Images file is mandatory if the specified software version is greater
# than the current software version of the subcloud.

- hosts: all
  gather_facts: false

  vars:
    prestage_type: 'images'
    prestage_reason: 'for_install'
    platform_backup_dir: /opt/platform-backup
    image_list: []
    # Max image bundle size in bytes
    bundle_size: 4000000000

  roles:
    - prestage/prepare-env
    - { role: prestage/prestage-images, become: true }
