---
#
# Copyright (c) 2022-2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# This playbook copies prestage packages (Centos) or ostree repo (Debian)
# from the release feed (Centos: /www/pages/feed/rel-<release>,
# Debian: /var/www/pages/feed/rel-<release>) to the prestage directory
# (/opt/platform-backup/<release>).
# The playbook is meant to be integrated with the dcmanager to provide
# subcloud prestaging functionality.
#
# Usage:
#   ansible-playbook prestage_sw_packages.yml -i <inventory-file> \
#      -e "software_version=<MM.YY.nn> software_major_release=<MM.YY> prestage_install=<for_install|for_sw_deploy>"

- hosts: all
  gather_facts: false

  vars:
    prestage_type: "packages"
    prestage_install: for_install
    platform_backup_dir: /opt/platform-backup

  roles:
    - role: prestage/prepare-env

    - role: prestage/sync-software-metadata
      when: prestage_install == 'for_sw_deploy' and prestage_sync_software_metadata_required
      vars:
        ansible_become_pass: "{{ ansible_ssh_pass }}"

    - role: prestage/prestage-sw-packages
      when: prestage_install == 'for_install' and prestage_os_type == 'debian'
      become: true

    - role: prestage/prestage-sw-packages-centos
      when: prestage_install == 'for_install' and prestage_os_type == 'centos'
      become: true

    - role: prestage/prestage-patches
      when: software_major_release is version('24.09', '<') and prestage_install == 'for_install' and host_patches_exist
      become: true

    - role: prestage/get-prestage-versions
      become: true
