---
#
# Copyright (c) 2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

# requires two variables passed:
# initial_backup_dir = the directory where the vault backup package will be found
# backup_filename = filename for vault backup package

- hosts: all
  gather_facts: no

  # Specify defaults including:
  #   backup_encryption_enabled
  #   backup_encryption_passphrase
  vars_files:
    - host_vars/backup-restore/default.yml

  vars:
    password_change: false
    vault_encrypt: "{{ backup_encryption_enabled|bool }}"
    encrypt_hc_vault_secret: "{{ backup_encryption_passphrase | default('') }}"
    vault_mode: "restore"
    op_mode: "standalone"

  roles:
    - role: common/prepare-env
    - role: vault/prepare_env
      become: yes
    - role: vault/vault_restore
      become: yes
