- project:
    check:
      jobs:
        - ansible-playbooks-tox-linters
        - ansible-playbooks-tox-pep8
        - ansible-playbooks-tox-bandit
    gate:
      jobs:
        - ansible-playbooks-tox-linters
        - ansible-playbooks-tox-pep8
        - ansible-playbooks-tox-bandit
    post:
      jobs:
        - stx-ansible-playbooks-upload-git-mirror

- job:
    name: ansible-playbooks-tox-linters
    parent: openstack-tox-linters
    description: |
      Run linters
    nodeset: debian-bullseye

- job:
    name: ansible-playbooks-tox-pep8
    parent: openstack-tox-pep8
    description: |
      Check conformance with pep8
    nodeset: debian-bullseye

- job:
    name: ansible-playbooks-tox-bandit
    parent: tox
    description: |
      Run bandit test for ansible-playbooks
    nodeset: debian-bullseye
    files:
      - ./*
    vars:
      tox_envlist: bandit
      tox_extra_args: -c ./tox.ini

- job:
    name: stx-ansible-playbooks-upload-git-mirror
    parent: upload-git-mirror
    description: >
      Mirrors opendev.org/starlingx/ansible-playbooks to
      github.com/starlingx/ansible-playbooks
    vars:
      git_mirror_repository: starlingx/ansible-playbooks
    secrets:
      - name: git_mirror_credentials
        secret: stx-ansible-playbooks-github-secret3
        pass-to-parent: true

- secret:
    name: stx-ansible-playbooks-github-secret3
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      ssh_key: !encrypted/pkcs1-oaep
        - C/6c28PFMDW50kcTOGp0IeBsYQKLusdWIOKSPktNzf5gFpiDj6nhTw8JdLtdAMby7Xwub
          NiQatCZCxbE8AjLlZsfGaIwxG8LZ2gbfrr6hYsgnqxrZ+QYcNizdEntN4M8CeYcNofuq5
          DPlaYCocSWOEUFz08ycnUplIhwaf14ewfeHYq0wo5Pd1BEdi9w/BKPcvM81S0w9sUTtKo
          KVkh073pNQK5PS+Ap+l4Jxn3jUUKdcsK7Mia4fnMO6nMNJ0DbsyUkctUCRKbqxIvg8U2I
          IfexRwmYFMfP1PP2LNWwg+6V5DUA3IqTLoM8WD5sDAA2bJr3BC0G6BTvFQMPyYPGj94JM
          omBprHYDXo9FrknSHqW2WbNV+JhDVND5j9jDKwZZrUjXij2R/EvFSQ2ujO6rIByzGWOdF
          RsHi0yTA/Absmng3zO0qlw8HKWDwjsocVrAlePZlrpOTExEWjWeorV4lRQfxk1D1o4rBz
          2CjSjydlApvLK0OfVw4J0F4vhKElj6lM2j5C8x77QUfLpTcScgLm6Q8q91PmEJ5Yl/Utg
          Qx3Qx8UCzIfIJXJgeACw36Hiq5RyJUsJxU8z6RLZ6eqOdtayvJ5fz0uRpXuFl/5yU26Qt
          zDJB6ZdEN2GXDaWPuyjry3ZFXzlUzXTCuPJmy+noeh3qIwAob/HPydxEidjS9w=
        - IE+7kXj2rFm9vCaCP6O+Gq/hcNMn6319XAfAOj/78a7BmEUgzefFohN3P7W9amgXHl1Uy
          bKptVtFp9wVe6OgTcQh7N+b9IahgoaCREqLes8Ae3jaovtxGx9LYEzmW0dGwvmJAPEg8k
          lgE4kF3UJ1dRiUQQ5GeDEVC81qSKejDH7HxVT2zklleAdqLH4Sb8jnsZ1CE5Y3emJJvRD
          ykuKeXRKW0+3yoH6eZHZ0GRWWrFi5CuO1cYPCf7GZBPLD2hTeLQ8GtDUJeVzU96pR+ezg
          SNU/DpLJWqLe3fmX06ZzhQd7pj5V/a2CrsVlU3u+zRat12EaqFCMdZ7aaulAS3hNqRR1S
          ed+HH+ietOYpgLJzKYHgiY6X8JYVJnLx0TLzac2RcqUL7UYf0vhaZMbNMmY/4gJH4r25r
          oTZuwfVY0pGnfGplO2EgZWklrCPIMNJnKL0heCEzQEfBE7sfctK5omv31EcAP5Bl3ceFL
          2Q/9kQ4J+qoftJpgPlEuGpJvxveasqszmKuc/qs6G/QEqeoqL5rckeOwEt/cIR2AMMqXI
          kmmsQdm3SnaK45vz8h53Cy3xF8nIvueYCBbuR0PvkkC6fzwSp9aEpoVWbvnV8LGlNwz5W
          wpbmSFI87y3QHBRMSjBZ01ZSIK9pHU8M4Rnip5Zs+OHsUEhXIq8NeSp1kdV0mI=
        - NZBGIjwSX+PxI9fFj83R3IZh70IPMUA/2E/5J3lDLget0VCMA+Dn/lZgn0a63akmjB2Hp
          AUEp5cUPa9AzEmx0EZUUtD0AyhQRjnAeQ57u74fw7+nwdOpnJYBlyuoOwVJdJgz1a/Diy
          CC5ks7FXuK/mSJFqqjpK0S0tAGDt7i29L4GAQVBWOL24qi3VnQC6x54wZsyEJmisZeKsc
          aC696Yysa4Srq5F3UfSTKWaXHAFjk4krBB2vEoi8oH7rfTAJUcsHxLgg6r0XRsdVstIv9
          zYq7phzoH9OjUgVMjIV0QFIRt0ONjbcM2hG7rdjWJbkYgq7rPtfNhrvEga5nXKFvVQxXl
          XUxFpxCZLSbNuLQAAi75UP0QNN5RguBBnUX3+gQnRVv3KVtCQU+EU9cQFZoecdUgpMTvB
          779OekzIw9kWRBTjHEPL/QUWTMKzTJumOslNMK1U+XZAE61pIb8PkqzJ31hiYusmWtDmU
          brLbAE5V2LibxZkOlycMPH8eqm558HwhdBb5/BWE3mvRtVsj0AifLwjIVIzHCgGdDHI5z
          vO+gT0clCJqbPqDwL0j/wI8ox8jVtqXbi+C6fQhR3HlOcak2M9dc5YXDBVlSTJQlWvh8d
          6/uDP4rbY1C8EaF+++BFzQNPlR5IeIZRKZZQwohHwrg6mdX7B2ivTCL99/L2D4=
        - iMb4M0tTP3mjkqXXr0CKdC1Inb5Vb4JUVytGLLq7dB/1dq+b+XNWq5cX6AlKgJ70QS+Ok
          82k7CMbztXOlON4pGOsVigsIPqvy9fTU+kqNB+WkNy6l/S+HUEvy/nImlK+chQqgMwAC2
          ZWuzAMaBX8AUH5m3s1ZNT7JAXKTwJoBDdELvmQMIPnLGFlRIEEEVt1L9RCoXFJQHMb8yZ
          z/FljF9XrWGQZ1hBu7ZEiRMYzdqnK15982XYdSsj+xP9RDxBQtu6g4fE10cQvWXMoOl1j
          HgJge5Pyen/w7tgnjkTer3do1WsKg3duUiM3ItkDU2aLjCg/XGbZD4CKsDfqwRamjbcOY
          5JtGO92peN9gpytPUS1hvYPQXK/XajEkiFwKMHTp24VjbX5Iw3BMn40NNNHrOMOz4f4Et
          aOdqrDgu0HnS9AloW23buWQeXcn7AhQct+cIVoRpqG4z6UFouryt8PUmZ+Nh3CnzEJXfs
          foThuxJ2DWjUBFDb3KcExT0r4JEvomnEYOLfLSfRRc7q4xT0FfZix6xHHw7pknu1A/Fbf
          jLn93kUTvLTzmL/OEZ+P2/2hRvH2c/mTFfonuGSaoy+iwq7TtrqdYKopL5s1tbn590O7e
          tq+jxixcnrK2A0XYBNfaLokSuATKXQ8dM9EfCMbDk/y5RHl+YlGW2agUvKlMeQ=
        - eXvCVAMTMdnMmIWp+hA0ghqilobctgII8HIgEE+jHLy+HihTybaLHn+SEFs9vLhXsDz6Q
          JUtpTAPkwNqHVUVHbjbjyygmSgdrtfaB60P8mfG2eW1VFUR7M2MrZi83qP1v4Fw7c43Tr
          BmNHV4r78vbMm08bmwxeRezUaz+O1AjrzMQEEguTzejQaah4hHO32szi8j36g4SolDRCF
          kSOcfQ8O0wnJlkbl8ERRedHWQ2BAp5KBcx8s19s/KbY7DoLHc/GzfDfImIVrsXz8LAkYb
          B050MFMqf6mrrmnzlAKZWax7bhICC6LWEr8EU8q4h8Yxf8rl6lAe5kRvknpLdhIwmaoJF
          0eiaAvxh0al93kI/N1sEdBKZjYT4IHvnEyv1+GSzxM9jkguE94/MGTPIDg1+oRvRuyW3G
          KOx8fMbcB06czoM64roDz2+vKLd7arRQ9Dl4J2Zuf4l7yLdhlRSXY7GJ9ZJ2wt/QDQ8TK
          UfMfACes1IU9x4PNFSzy4WBM9ixQ5P6hN+s8LVV95RfnQ2hQaxIW5gMATB2hwG2Z67jrN
          WW4XnsSQ5NQlJTLYZlwQdYtCCxOcRKUL60AyM4QvRtruuTlFwTH18c1WUwScbigDZOMUm
          LQwE+Vi5MbGOdirYkN9p0+V8V+6eSQNf1EYSkLDsYf7DLV0f6TQwEYXpfsm4pQ=
        - DpstMzI6ztQ4MBAFfwjwHo5k4E+V+idw4SzHORw4OaAi1NV8VRTcJP3nV6vbIQLLXk4u4
          p1P/r3zf2bGAkT/oxXS5iKCWocf44WOhAJORqVJO92uhnrRtwy5K8gcZ2MtW7QvRrrcms
          Wq+RQ2fGD8fwHfGO2Pi3NdIW64Y8LnY6bgMnv6Lf4jL6T0I/KXgzCFhhTsMOtghSZD/Cg
          cRYIOBl4e3NKIucjG+DEpkW0LMI7Y9gLVcnnROrtH4x86AQebOtazbrStrkBouJ+sv8o9
          5/gwkM4ZEUijVJ0QriXJ/9mCnj5LRbqZZdOGgRFyan9snkuoIGP9nCEykI67Q5f1shJu0
          aMECSJvTa7tSmRg46TCyEaEA9rij40PE5+eBU9ewgQQrpOYwVfVROQpbPHli+jbD6uoxv
          f3lj8o1WQk67NW51qHrKqPd7TJ1zUniguwuhircytYVd2Ie7ZSb3x+OuP9y/7O6rTLvGI
          EabpcYib5ZLqHppRdrQtyX+6/zc7Ues34olYMCoDaHGav4YyGs0K+B4H04p0kCfgzMaVc
          Wvw4LeYaGAqttK9UknqBeeRtZLhavcWy2bY2Vh0WHrFcjthkixo787bcNrD8juN2w8+u0
          sKDdxoxd0x87y1SqSdYjGp/Flc9aHzgfT2+DjGmZ/w66I1deLB2cWXJxhlCE/4=
        - liamXS6AWKzPKfIWmGqx7ZYGO4PXSUqW8DrSr02vSCJLfWaJUv/TEvxwZZZoAivhnwy8c
          pARJzRwgkqgropXTQrSaHq/eY7Qx1bkTETaFkZPo+cGVal3o2h4L408lGH6+wH3rRAgsz
          HF20nnh9LigGoYN4yvzedccS1dAY7rTFzOdvV1dEjmcTeab4bHeC2zh3lgW3PzDP8nSHd
          Z6UWLHsfcuUSz4ZzTsC2iAuoJbRAhe1tv+B6QQbhDB0ohBhtezfBT4Xm1N3rM8iqjQfeo
          nRhFGtMG3H9Ql+66HsEgAQDB+DwtGdzJaKKSGp9BlePtztOtQmC49nVYhe1LjB1fJLnX0
          kLI5+Hb+SHvtS9pGzDWUWyZHN/5agtyYBsrE93WwTLsfFDLs14xkWqlE/29l79gMWkZJy
          31+qyqAK1Lae3FdYRdua5UjWEYxzOos8BxTPx6zAyzUPMh8nsn40hMFB+HGmFBdPtg/IT
          DJ+Gw0kyhGV/JX7MIaFnZantmpUo2GiZXzUfHW1D5HHLGgzEVK0V+vZ57HHdiyWTuPYA0
          FPV4CBY2TDJV9TSVOeCYMHg1Nvc7rgeM9fqhHwwxBXr5yE4suyT2GyXud+BPl6s6l+Suc
          jjz03KFf4cRL298QKwnRJEjnjtsoghwBB3ekZJnDEhBq+BKwkvBdloC2wUMKcg=
