#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Wait for rook-ceph to reach applied
  include_tasks: "{{ role_path_common }}/tasks/check_app_status.yaml"
  vars:
    app_name_to_check: "rook-ceph"
    success_statuses:
      - "applied"
    failure_statuses:
      - "apply-failed"
    retries: 366 # 1 hour and 1 minute, good luck
    delay: 10

- name: Show final application status
  debug:
    msg: "Final rook-ceph status: {{ app_status_check.stdout | trim }}"

- name: Give the cluster a few extra seconds to scrub and be stable
  pause:
    seconds: 10
  run_once: true
  delegate_to: "{{ system.active_controller }}"
  changed_when: false

- name: Wait for Ceph cluster to reach HEALTH_OK
  command: timeout 30 ceph health detail
  register: ceph_health
  until: "'HEALTH_OK' in ceph_health.stdout"
  retries: 120
  delay: 10
  changed_when: false

- name: Ceph Cluster health result
  debug:
    var: ceph_health.stdout_lines

- name: Wait until all PGs are active+clean
  command: timeout 30 ceph pg stat
  register: ceph_pg_stat
  until: >
    ceph_pg_stat.stdout is search('^([0-9]+) pgs: \\1 active\\+clean')
  retries: 60
  delay: 10
  changed_when: false

- name: Ceph PG stat result
  debug:
    var: ceph_pg_stat.stdout_lines

- name: Check storage backend has_long_running_operations
  become: true
  become_user: postgres
  command: >
    psql -d sysinv -t -A -c
    "SELECT capabilities::json->>'has_long_running_operations'
    FROM storage_backend;"
  register: has_long_running_operations
  until: has_long_running_operations.stdout_lines | length == 0
  retries: 60
  delay: 10
  changed_when: false

- name: Show storage backend has_long_running_operations
  debug:
    var: has_long_running_operations.stdout_lines
  when: has_long_running_operations.stdout_lines | length > 0

- name: Wait until the 'degraded' and 'scrub' keywords go away from ceph status
  command: timeout 30 ceph -s
  register: ceph_status
  until: >
    'degraded' not in ceph_status.stdout and 'scrub' not in ceph_status.stdout
  retries: 60
  delay: 10
  changed_when: false

- name: Ceph Cluster status
  debug:
    var: ceph_status.stdout_lines

- name: Delete old cluster alarms
  include_tasks: "{{ role_path_common }}/tasks/delete_old_cluster_alarms.yaml"
  when: migration_type != "in_service" # in-service keeps the same fsid
