#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Check storage backend has_long_running_operations
  become: true
  become_user: postgres
  command: >
    psql -d sysinv -t -A -c
    "SELECT capabilities::json->>'has_long_running_operations'
    FROM storage_backend;"
  register: has_long_running_operations
  until: has_long_running_operations.stdout_lines | length == 0
  retries: 120
  delay: 10
  changed_when: false

- name: Re-apply Rook-Ceph application
  environment: "{{ system_env }}"
  command: system application-apply rook-ceph
  register: app_apply_result
  failed_when:
    - app_apply_result.rc != 0
    - ("applying" not in app_apply_result.stderr)
    - ("is already in progress" not in app_apply_result.stderr)

- name: Wait for rook-ceph to reach applied
  include_tasks: "{{ role_path_common }}/tasks/check_app_status.yaml"
  vars:
    app_name_to_check: "rook-ceph"
    success_statuses:
      - "applied"
    failure_statuses:
      - "apply-failed"
    retries: 180
    delay: 10

- name: Show final application status
  debug:
    msg: "Final rook-ceph status: {{ app_status_check.stdout | trim }}"

- name: Give the the app a few seconds to start post apply
  pause:
    seconds: 5
  run_once: true
  changed_when: false

- name: Check storage backend has_long_running_operations
  become: true
  become_user: postgres
  command: >
    psql -d sysinv -t -A -c
    "SELECT capabilities::json->>'has_long_running_operations'
    FROM storage_backend;"
  register: has_long_running_operations
  until: has_long_running_operations.stdout_lines | length == 0
  retries: 120
  delay: 10
  changed_when: false

- name: Show storage backend has_long_running_operations
  debug:
    var: has_long_running_operations.stdout_lines
  when: has_long_running_operations.stdout_lines | length > 0

- name: Give the the app a few seconds to finish post apply
  pause:
    seconds: 10
  run_once: true
  changed_when: false

- name: Wait for Ceph cluster to reach HEALTH_OK
  command: timeout 30 ceph health detail
  register: ceph_health
  until: "'HEALTH_OK' in ceph_health.stdout"
  retries: 120
  delay: 10
  changed_when: false

- name: Ceph Cluster health result
  debug:
    var: ceph_health.stdout_lines
