#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Unmount LV and remove from fstab
  mount:
    path: "{{ lv_mount_point }}"
    state: absent

- name: Remove mount directory
  file:
    path: "{{ lv_mount_point }}"
    state: absent
    force: yes

- name: Remove LV
  lvol:
    vg: "{{ vg_name }}"
    lv: "{{ lv_name }}"
    state: absent
    force: yes
