#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Update cluster fixing name, type and deployment_model
  become: true
  become_user: postgres
  command: >
    psql -d sysinv
    -c "UPDATE clusters SET type='ceph-rook',name='ceph_rook_cluster' WHERE name='ceph_cluster' RETURNING id, uuid, type, name"
  register: update_cluster
  changed_when: update_cluster is defined
  failed_when: update_cluster is failed

- name: Summarize cluster updates
  when: update_cluster is defined
  debug:
    var: update_cluster.stdout_lines
