---

#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Unmount if already mounted
  mount:
    path: "{{ lv_mount_point }}"
    state: absent
  failed_when: false

- name: Remove existing LV if present
  lvol:
    vg: "{{ vg_name }}"
    lv: "{{ lv_name }}"
    state: absent
    force: yes
  failed_when: false

- name: "Obtain extent size for {{ vg_name }}"
  shell: "vgs --units b --no-suffix -o vg_extent_size {{ vg_name }} --noheadings --rows | tr -d ' '"
  changed_when: false
  register: vg_extent_size

# A multiple of the VG extent size, avoids error in LV creation with sizes not
# multiple of the block size, since extent size is already a multiple of block
# size. And avoids LVM rounding up the LV size passed to be conformant with the
# extent size by itself.
- name: >
    Round up LV size required ({{ backups_required_bytes }})
    to a multiple of the VG extent size"
  set_fact:
    lv_size_bytes: "{{ ((backups_required_bytes | int + vg_extent_size.stdout | int - 1) // vg_extent_size.stdout | int) * vg_extent_size.stdout | int }}"

- name: "Show LV size"
  debug:
    msg: >
      LV size is {{ lv_size_bytes }}, rounded down to multiple of {{ vg_name }}
      extent size {{ vg_extent_size.stdout | int | human_readable }})

- name: Create LV
  lvol:
    vg: "{{ vg_name }}"
    lv: "{{ lv_name }}"
    size: "{{ lv_size_bytes }}B"
    state: present
    force: yes

- name: Create filesystem on the LV
  filesystem:
    fstype: "{{ lv_fs_type }}"
    dev: "/dev/{{ vg_name }}/{{ lv_name }}"
    force: yes

- name: Create mount directory
  file:
    path: "{{ lv_mount_point }}"
    state: directory
    mode: '0755'

- name: Mount the logical volume
  mount:
    path: "{{ lv_mount_point }}"
    src: "/dev/{{ vg_name }}/{{ lv_name }}"
    fstype: "{{ lv_fs_type }}"
    state: mounted # already sets up fstab

- name: Set backups_path to LV mount point
  set_fact:
    backups_path: "{{ lv_mount_point }}"
    cacheable: true
  when: backups_path is undefined
