#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Stop each OSD service
  systemd:
    name: "ceph-osd@{{ item.osd_id }}.service"
    state: stopped
  loop: "{{ hostvars[system.active_controller]['ceph_disks_by_host'][inventory_hostname] }}"
  loop_control:
    label: "Host {{ inventory_hostname }} OSD id = {{ item.osd_id }}"
  register: stop_osd_result
  failed_when:
    - stop_osd_result is failed
    - ('Could not find the requested service' not in (stop_osd_result.msg | default('')))

- name: Remove ceph-osd unit files
  shell: rm -vf /etc/systemd/system/ceph-osd@*.service
  register: remove_osd_unit_files

- name: Display removed ceph-osd unit files
  debug:
    var: remove_osd_unit_files.stdout_lines
  when: remove_osd_unit_files.stdout_lines | length > 0

- name: Reload systemd
  systemd:
    daemon_reload: true
