---
#
# Copyright (c) 2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
#   This role is to update the openstack admin endpoints to reflect the
#   subcloud network reconfiguration change
#

- name: Wrap sc_floating_address in [] brackets if it's an ipv6 address
  set_fact:
    parsed_sc_floating_address: "{{ sc_floating_address | ipwrap }}"

- name: Retrieve subcloud endpoint region name
  shell: >-
    source /etc/platform/openrc; system show |
    grep region_name | awk '{ print $4 }'
  register: sc_region_name

- name: Create service endpoint list
  set_fact:
    service_list:
      - { port: "5001", service: "keystone" }
      - { port: "6386/v1", service: "sysinv" }
      - { port: "5492", service: "patching" }
      - { port: "4546", service: "vim" }
      - { port: "18003", service: "fm" }
      - { port: "9312", service: "barbican" }

- name: Add USM service to endpoint list for software_version > 22.12
  set_fact:
    service_list: "{{ service_list + [{ 'port': '5498', 'service': 'usm' }] }}"
  when: software_version is version('22.12', '>')

- name: Add dcdbsync service to endpoint list if not enroll
  set_fact:
    service_list: "{{ service_list + [{ 'port': '8220/v1.0', 'service': 'dcdbsync' }] }}"
  when: mode is not defined or mode != "enroll"

- name: Check and update admin endpoints
  include_tasks: check_and_update_endpoint.yml
  vars:
    service: "{{ item.service }}"
    port: "{{ item.port }}"
  loop: "{{ service_list }}"
