---
#
# Copyright (c) 2023-2025 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
#   This role is to update the openstack admin endpoints to reflect the
#   subcloud network reconfiguration change
#

# Try to get from sourced credentials and fall back to 'system show' if not available
- name: Retrieve subcloud endpoint region name
  shell: echo "${OS_REGION_NAME:-$(source /etc/platform/openrc && system show | grep region_name | awk '{ print $4 }')}"
  args:
    executable: /bin/bash
  register: sc_region_name
  changed_when: false

- name: Update admin endpoints
  script: update_admin_endpoints.py {{ sc_region_name.stdout }} {{ sc_floating_address }}
          {{ '--mode enroll' if mode is defined and mode == 'enroll' else '' }}
  register: update_admin_endpoints_result
  failed_when: false

- name: Show update admin endpoints result
  debug: var=update_admin_endpoints_result

- name: Fail if update admin endpoints script throws an exception
  fail:
    msg: >
      Failed to update admin endpoints, return code: {{ update_admin_endpoints_result.rc }}
      Error output: {{ update_admin_endpoints_result.stderr }}
  when: update_admin_endpoints_result.rc != 0
