#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Validate data integrity of the generated pool list
  set_fact:
    invalid_pool_fields: >-
      {{ invalid_pool_fields | default([]) +
         ([ "Pool '" ~ (item.0.name | default('Unknown')) ~ "': Field '" ~ item.1 ~ "' is empty or null" ]
          if (item.0[item.1] is not defined or item.0[item.1] is none or item.0[item.1] | string | length == 0)
          else [])
      }}
  loop: "{{ all_pools_list | product(mandatory_fields) | list }}"
  loop_control:
    label: "{{ item.0.name | default('Unknown') }} - {{ item.1 }}"
  vars:
    mandatory_fields:
      - name
      - id
      - pg_num
      - pgp_num
      - crush_rule
      - size
      - min_size
      - application
  when: all_pools_list is defined and all_pools_list | length > 0

- block:
    - name: Show validation errors details
      debug:
        msg: "{{ invalid_pool_fields }}"

    - name: Fail due to data integrity issues
      fail:
        msg: "FAILURE: Integrity check failed. See the list above for details."
  when: invalid_pool_fields is defined and invalid_pool_fields | length > 0
