#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Populate host in-sync list
  include_tasks: "{{ role_path_common }}/tasks/get_hosts_in_sync.yaml"

- name: Check if all hosts are in-sync and reconciled
  fail:
    msg: >
      Some hosts are NOT in-sync and reconciled:
      {{
        bad_hosts_in_sync
        | map(attribute='metadata.name')
        | unique
        | list
      }}
  when: bad_hosts_in_sync | length > 0

- name: All hosts are in-sync and reconciled
  debug:
    msg: "All hosts are in-sync=true and reconciled=true"
  when: bad_hosts_in_sync | length == 0
