#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Populate system in-sync list
  include_tasks: "{{ role_path_common }}/tasks/get_system_in_sync.yaml"

- name: Check if system is in-sync and reconciled
  fail:
    msg: |-
      System is NOT in-sync or reconciled:
      {{
        bad_system_in_sync
        | map(attribute='metadata.name')
        | unique
        | list
      }}
      In case the in-sync or reconciled false state is not important,
      this pre-check can be skipped by using the flag '-e allow_out_of_sync=true'.
      The final system state check will also allow the system to not be insync or reconciled.
  when:
    - bad_system_in_sync | length > 0
    - not allow_out_of_sync | bool

- name: System in-sync and reconciled
  debug:
    msg: "System in-sync=true and reconciled=true"
  when: bad_system_in_sync | length == 0
