#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Display system alarms if any
  include_tasks: "display_alarms.yaml"

- name: Check if any applications are in a undesired state
  include_tasks: "check_any_applications_state.yaml"

- name: Check Ceph cluster health
  include_tasks: "check_ceph_cluster_health.yaml"

- name: Check platform-integ-apps is applied
  include_tasks: "check_platform_integ_apps.yaml"

- name: Check deployment-manager is applied
  include_tasks: "check_dm_app.yaml"

- name: Check if hosts in deployment-manager are configured
  include_tasks: "check_dm_hosts_configured.yaml"

- name: Check openstack app is not applied
  include_tasks: "check_openstack_app.yaml"
  when: block_openstack_app | bool

- name: Check for none hosts
  include_tasks: "check_none_hosts.yaml"

- name: Check if hosts are unlocked/enabled/available
  include_tasks: "check_hosts_ready.yaml"

- name: Check if hosts are in-sync and reconciled
  include_tasks: "check_hosts_in_sync_reconciled.yaml"

- name: Check if system is in-sync and reconciled
  include_tasks: "check_system_in_sync_reconciled.yaml"

- name: Check if any monitors are not configured
  include_tasks: "check_monitor_state.yaml"

- name: Check if any OSDs are not configured
  include_tasks: "check_osds_state.yaml"

- name: Check if there is a backup or restore in progress
  include_tasks: "check_backup_or_restore_in_progress.yaml"

- name: "Check if there is sufficient space in {{ storage_backend_migration_backup_dir }}"
  include_tasks: "check_migration_backup_dir.yaml"

- name: Check if there is sufficient space in /var
  include_tasks: "check_var_space.yaml"

- name: Check if there is not allowed pools
  include_tasks: check_allowed_pools.yaml

- name: Check if all pools have required values
  include_tasks: check_pools_values.yaml

- name: Check if there is a upgrade in progress
  include_tasks: "check_upgrade_in_progress.yaml"

- name: Validate custom action hook URIs
  include_tasks: "check_custom_action_hooks.yaml"

- name: Check if there are Ceph PVCs to migrate
  include_tasks: "check_no_pvcs_found.yaml"
  when: migration_type != "redeploy"

- name: Check if any pods are using Ceph PVCs
  include_tasks: "check_ceph_pvcs.yaml"

- name: "Check DataVolumes matching PVCs"
  include_tasks: "check_dvs.yaml"
  when: dv_map_original | length > 0

- name: Check kubevirt-app is applied when DataVolumes exist
  include_tasks: "{{ role_path_common }}/tasks/check_app_status.yaml"
  vars:
    app_name_to_check: kubevirt-app
    success_statuses:
      - applied
  when: dv_map_original | length > 0

- name: "Check {{ migration_target }} migration common cases"
  include_tasks: "{{ migration_target }}/main.yaml"
