#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

"""Shared test constants for ansible-playbooks tests.

Centralizes configuration values used across multiple
test files. Update values here to propagate everywhere.
"""

MGMT_SUBNET = "192.168.204.0/24"
MGMT_NETWORK = "192.168.204.0"
MGMT_START = "192.168.204.2"
MGMT_END = "192.168.204.254"
MGMT_FLOAT = "192.168.204.1"
MGMT_GATEWAY = "192.168.204.1"
MGMT_CTRL0 = "192.168.204.3"
MGMT_CTRL1 = "192.168.204.4"

ADMIN_SUBNET = "192.168.205.0/24"
ADMIN_START = "192.168.205.2"
ADMIN_END = "192.168.205.254"
ADMIN_FLOAT = "192.168.205.1"
ADMIN_GATEWAY = "192.168.205.1"

OAM_SUBNET = "10.10.10.0/24"
OAM_START = "10.10.10.2"
OAM_END = "10.10.10.254"
OAM_FLOAT = "10.10.10.1"
OAM_GATEWAY = "10.10.10.1"
OAM_ADDR_0 = "10.10.10.3"
OAM_ADDR_1 = "10.10.10.4"

OAM_SECONDARY_START = "10.10.11.2"
OAM_SECONDARY_END = "10.10.11.254"
OAM_SECONDARY_FLOAT = "10.10.11.1"
OAM_SECONDARY_GATEWAY = "10.10.11.1"
OAM_SECONDARY_ADDR_0 = "10.10.11.3"
OAM_SECONDARY_ADDR_1 = "10.10.11.4"

PXEBOOT_SUBNET = "169.254.202.0/24"
PXEBOOT_START = "169.254.202.2"
PXEBOOT_END = "169.254.202.254"

MULTICAST_SUBNET = "239.1.1.0/28"
MULTICAST_START = "239.1.1.1"
MULTICAST_END = "239.1.1.14"

CLUSTER_HOST_SUBNET = "192.168.206.0/24"
CLUSTER_HOST_START = "192.168.206.2"
CLUSTER_HOST_END = "192.168.206.254"

CLUSTER_POD_SUBNET = "172.16.0.0/16"
CLUSTER_POD_START = "172.16.0.1"
CLUSTER_POD_END = "172.16.255.254"

CLUSTER_SVC_SUBNET = "10.96.0.0/12"
CLUSTER_SVC_START = "10.96.0.1"
CLUSTER_SVC_END = "10.111.255.254"

SC_SUBNET = "192.168.100.0/24"
SC_FLOAT = "192.168.100.1"
SC_OAM_SUBNET = "10.10.20.0/24"
SC_OAM_FLOAT = "10.10.20.1"

NAMESERVERS = "8.8.8.8"
CONTROLLER_HOSTNAME = "controller-0"
SW_VERSION = "24.09"
CONTROLLER_0_ADMIN_NETWORK_IF = "enp0s8"

# OpenStack credential test data
OS_ENV_LINES = [
    "OS_USERNAME=admin\n",
    "OS_PASSWORD=p\n",
    "OS_AUTH_URL=http://x\n",
    "OS_PROJECT_NAME=a\n",
    "OS_USER_DOMAIN_NAME=D\n",
    "OS_PROJECT_DOMAIN_NAME=D\n",
    "OS_REGION_NAME=R\n",
]


def default_bootstrap_config():
    """Return default bootstrap config dict.

    :returns: dict of bootstrap config key-value pairs
    """
    return {
        "DISTRIBUTED_CLOUD_ROLE": "none",
        "SYSTEM_MODE": "simplex",
        "SYSTEM_TYPE": "All-in-one",
        "TIMEZONE": "UTC",
        "REGION_NAME": "RegionOne",
        "INCOMPLETE_BOOTSTRAP": "False",
        "MANAGEMENT_SUBNET": MGMT_SUBNET,
        "MANAGEMENT_START_ADDRESS": MGMT_START,
        "MANAGEMENT_END_ADDRESS": MGMT_END,
        "MANAGEMENT_FLOATING_ADDRESS": MGMT_FLOAT,
        "MANAGEMENT_GATEWAY_ADDRESS": "undef",
        "MANAGEMENT_DYNAMIC_ADDRESS_ALLOCATION": "True",
        "MANAGEMENT_SUBNET_SECONDARY": "undef",
        "ADMIN_SUBNET": "undef",
        "ADMIN_SUBNET_SECONDARY": "undef",
        "ADMIN_START_ADDRESS": ADMIN_START,
        "ADMIN_END_ADDRESS": ADMIN_END,
        "ADMIN_FLOATING_ADDRESS": ADMIN_FLOAT,
        "ADMIN_GATEWAY_ADDRESS": "undef",
        "EXTERNAL_OAM_SUBNET": OAM_SUBNET,
        "EXTERNAL_OAM_START_ADDRESS": OAM_START,
        "EXTERNAL_OAM_END_ADDRESS": OAM_END,
        "EXTERNAL_OAM_FLOATING_ADDRESS": OAM_FLOAT,
        "EXTERNAL_OAM_GATEWAY_ADDRESS": OAM_GATEWAY,
        "EXTERNAL_OAM_0_ADDRESS": OAM_ADDR_0,
        "EXTERNAL_OAM_1_ADDRESS": OAM_ADDR_1,
        "EXTERNAL_OAM_SUBNET_SECONDARY": "undef",
        "EXTERNAL_OAM_START_ADDRESS_SECONDARY": (OAM_SECONDARY_START),
        "EXTERNAL_OAM_END_ADDRESS_SECONDARY": (OAM_SECONDARY_END),
        "EXTERNAL_OAM_FLOATING_ADDRESS_SECONDARY": (
            OAM_SECONDARY_FLOAT
        ),
        "EXTERNAL_OAM_GATEWAY_ADDRESS_SECONDARY": (
            OAM_SECONDARY_GATEWAY
        ),
        "EXTERNAL_OAM_0_ADDRESS_SECONDARY": (OAM_SECONDARY_ADDR_0),
        "EXTERNAL_OAM_1_ADDRESS_SECONDARY": (OAM_SECONDARY_ADDR_1),
        "PXEBOOT_SUBNET": PXEBOOT_SUBNET,
        "PXEBOOT_START_ADDRESS": PXEBOOT_START,
        "PXEBOOT_END_ADDRESS": PXEBOOT_END,
        "PXEBOOT_FLOATING_ADDRESS": "undef",
        "MANAGEMENT_MULTICAST_SUBNET": MULTICAST_SUBNET,
        "MANAGEMENT_MULTICAST_START_ADDRESS": (MULTICAST_START),
        "MANAGEMENT_MULTICAST_END_ADDRESS": MULTICAST_END,
        "MANAGEMENT_MULTICAST_SUBNET_SECONDARY": "undef",
        "CLUSTER_HOST_SUBNET": CLUSTER_HOST_SUBNET,
        "CLUSTER_HOST_START_ADDRESS": CLUSTER_HOST_START,
        "CLUSTER_HOST_END_ADDRESS": CLUSTER_HOST_END,
        "CLUSTER_HOST_FLOATING_ADDRESS": "undef",
        "CLUSTER_HOST_DYNAMIC_ADDRESS_ALLOCATION": "True",
        "CLUSTER_HOST_SUBNET_SECONDARY": "undef",
        "CLUSTER_POD_SUBNET": CLUSTER_POD_SUBNET,
        "CLUSTER_POD_START_ADDRESS": CLUSTER_POD_START,
        "CLUSTER_POD_END_ADDRESS": CLUSTER_POD_END,
        "CLUSTER_POD_SUBNET_SECONDARY": "undef",
        "CLUSTER_SERVICE_SUBNET": CLUSTER_SVC_SUBNET,
        "CLUSTER_SERVICE_START_ADDRESS": CLUSTER_SVC_START,
        "CLUSTER_SERVICE_END_ADDRESS": CLUSTER_SVC_END,
        "CLUSTER_SERVICE_SUBNET_SECONDARY": "undef",
        "SYSTEM_CONTROLLER_SUBNET": SC_SUBNET,
        "SYSTEM_CONTROLLER_FLOATING_ADDRESS": SC_FLOAT,
        "SYSTEM_CONTROLLER_OAM_SUBNET": SC_OAM_SUBNET,
        "SYSTEM_CONTROLLER_OAM_FLOATING_ADDRESS": SC_OAM_FLOAT,
        "NAMESERVERS": NAMESERVERS,
        "DOCKER_HTTP_PROXY": "undef",
        "DOCKER_HTTPS_PROXY": "undef",
        "DOCKER_NO_PROXY": "localhost",
        "USE_PUBLIC_REGISTRIES": "True",
        "VIRTUAL_SYSTEM": "False",
        "KUBERNETES_VERSION": "none",
        "MANAGEMENT_INTERFACE": "enp0s8",
        "CONTROLLER_HOSTNAME": CONTROLLER_HOSTNAME,
        "SW_VERSION": SW_VERSION,
        "CONTROLLER_0_ADMIN_NETWORK_IF": CONTROLLER_0_ADMIN_NETWORK_IF,
        "MANAGEMENT_CONTROLLER0_ADDRESS": MGMT_CTRL0,
        "MANAGEMENT_CONTROLLER1_ADDRESS": MGMT_CTRL1,
        "OIDC_ISSUER_URL": "undef",
        "OIDC_CLIENT_ID": "undef",
        "OIDC_USERNAME_CLAIM": "undef",
        "OIDC_GROUPS_CLAIM": "undef",
    }
