---
#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# This playbook is intended to be run on standalone systems.
#
# It prepares the alarms and hosts for the migrattion of storage backend used.
#

- name: Execute pre-migration
  hosts: active_controller
  gather_facts: false
  become: true

  pre_tasks:
    - name: Raise in-progress migration alarm
      script: "{{ role_path_common }}/files/fm_alarm.py --entity-uuid {{ storage_backend.uuid }} --set in_progress"
      vars:
        storage_backend: "{{ hostvars[system.active_controller].storage_backend }}"

- name: Disable host services
  hosts: storages, workers, standby_controller, active_controller
  gather_facts: false
  become: true

  roles:
    - role: manage-host-services
      host_service_action: disable
      checkpoint_name: manage-host-services-disable
