---
#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# This playbook is intended to be run on standalone systems.
#
# It clears the alarms and hosts changes after the migrattion of storage backend.
#

- name: Generate, backup new DM file, apply it and check the system state
  hosts: active_controller
  gather_facts: false
  become: true

  roles:
    - role: generate-system-dm-file
    - role: final-system-state-check

- name: Enable host services
  hosts: storages, workers, standby_controller, active_controller
  gather_facts: false
  become: true

  roles:
    - role: manage-host-services
      host_service_action: enable
      checkpoint_name: manage-host-services-enable

- name: Execute Post-migration
  hosts: active_controller
  gather_facts: false
  become: true

  post_tasks:
    - name: Clear storage-backend migration capability
      become: true
      become_user: postgres
      command: >
        psql -d sysinv -c "
        UPDATE storage_backend
        SET capabilities = (capabilities::jsonb - 'migration_type' - 'migration_step' - 'migration_status')::text
        WHERE id = {{ storage_backend.id }};
        "
      vars:
        storage_backend: "{{ hostvars[system.active_controller].storage_backend }}"

    - name: Clear migration alarms
      script: "{{ role_path_common }}/files/fm_alarm.py --entity-uuid {{ storage_backend.uuid }} --clear {{ item }}"
      vars:
        storage_backend: "{{ hostvars[system.active_controller].storage_backend }}"
      loop:
        - "in_progress"
        - "error"

    - name: Remove in-progress migration flag
      file:
        path: /run/.rook_migration_in_progress
        state: absent

    - name: New DM file reminder
      debug:
        msg: "A new DM file was generated after the migration and it is saved in {{hostvars[system.active_controller].final_dm_full_file_path }}"
