#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Unmanage ceph-osd service
  command: sm-unmanage service ceph-osd

- name: Deprovision ceph-osd service
  command: sm-deprovision service-group-member --apply storage-services ceph-osd

- name: Give ceph-osd services a few extra seconds to identify the changes
  pause:
    seconds: 12
  delegate_to: "{{ system.active_controller }}"
  changed_when: false

- name: Stop all filestore OSDs on this host first
  command: /etc/init.d/ceph stop osd
  register: stop_osds_result

- name: Debug stopped OSDs
  debug:
    var: stop_osds_result

- name: Give ceph some time to know what to do with OSDs down
  pause:
    seconds: 10
  delegate_to: "{{ system.active_controller }}"
  changed_when: false

- name: Wait for all PGs not be incomplete|inactive|peering
  include_tasks: wait_pg_states.yaml

- name: Display cluster status
  debug:
    var: ceph_status.stdout_lines

- name: Give Ceph some time to rellocate the active PGs
  pause:
    seconds: 20
  delegate_to: "{{ system.active_controller }}"
  changed_when: false

- name: Migrate OSDs all at once
  include_tasks: migrate_single_osd.yaml
  loop: "{{ host_osd_info }}"
  loop_control:
    label: "Host {{ inventory_hostname }} OSD id = {{ item.osd_id }}"
  when: item.osd_objectstore == "filestore"

- name: Give ceph some time to know what to do with OSDs purged
  pause:
    seconds: 10
  delegate_to: "{{ system.active_controller }}"
  changed_when: false

- name: Wait for cluster to stabilize after OSD destroy/purge
  include_tasks: wait_pg_states.yaml

- name: Give Ceph some time to rellocate the active PGs before starting OSDs
  pause:
    seconds: 20
  delegate_to: "{{ system.active_controller }}"
  changed_when: false

- name: Reload systemd
  systemd:
    daemon_reload: true

- name: "Start OSDs services"
  systemd:
    name: "ceph-osd@{{ item.osd_id }}.service"
    state: started
    enabled: true
  retries: 10
  delay: 10
  loop: "{{ host_osd_info }}"
  loop_control:
    label: "Host {{ inventory_hostname }} OSD id = {{ item.osd_id }}"

- name: Wait until OSDs are up
  command: ceph osd tree -f json
  register: ceph_osd_tree
  retries: 60
  delay: 10
  until: >
    ceph_osd_tree.stdout | from_json | json_query("nodes[?type=='osd'].status") is not none and
    (
      ceph_osd_tree.stdout | from_json | json_query("nodes[?type=='osd'].status")
    ) | select("equalto", "up") | list | length ==
    (
      ceph_osd_tree.stdout | from_json | json_query("nodes[?type=='osd'].status") | length
    )
  changed_when: false

- name: Wait until cluster finishes recovery and health check
  include_tasks: wait_recovery.yaml

- name: Display cluster status
  debug:
    var: ceph_status.stdout_lines

- name: Get OSD tree after migrating OSD
  command: timeout 30 ceph osd tree
  register: ceph_osd_tree_output
  changed_when: false

- name: Display OSD tree
  debug:
    var: ceph_osd_tree_output.stdout_lines
