#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Mark OSD as out if replica is 1
  block:
    - name: Reweight osd {{ item.osd_id }} to zero
      command: ceph osd crush reweight osd.{{ item.osd_id }} 0
      register: reweight_zero_result

    - name: Wait for OSD {{ item.osd_id }} to be safe to destroy
      command: ceph osd safe-to-destroy {{ item.osd_id }}
      register: safe_to_destroy_check
      until: safe_to_destroy_check.rc == 0
      retries: 1080
      delay: 10
      failed_when: safe_to_destroy_check.rc != 0
      changed_when: false

    - name: Wait until cluster finishes recovery
      command: ceph health -f json
      register: ceph_health
      retries: 180
      delay: 10
      until: >
        (
          ceph_health.stdout | from_json | json_query("status") == "HEALTH_OK"
        ) or
        (
          (
            ceph_health.stdout | from_json | json_query("checks")
          | dict2items
          | selectattr("value.severity", "equalto", "HEALTH_WARN")
          | list
          | length
          ) == 0
        )
      changed_when: false

    - name: Wait until all PGs are active+clean
      command: timeout 30 ceph pg stat
      register: ceph_pg_stat
      until: >
        ceph_pg_stat.stdout is search('^([0-9]+) pgs: \\1 active\\+clean')
      retries: 180
      delay: 10
      changed_when: false

    - name: Wait until the 'recover' keyword goes away from ceph status
      command: timeout 30 ceph -s
      register: ceph_status
      until: >
        'recover' not in ceph_status.stdout
      retries: 120
      delay: 10
      changed_when: false

    - name: Mark osd {{ item.osd_id }} as out
      command: ceph osd out {{ item.osd_id }}
      register: mark_osd_out_result

    - name: Wait until the 'recover' keyword goes away from ceph status
      command: timeout 30 ceph -s
      register: ceph_status
      until: >
        'recover' not in ceph_status.stdout
      retries: 120
      delay: 10
      changed_when: false

  when: hostvars[system.active_controller]['pool_size'] | int < 2

- name: Migrate one OSD
  include_tasks: migrate_single_osd.yaml # it takes an item

- name: Give Ceph some time to rellocate the active PGs when replica is bigger than 1
  pause:
    seconds: 5
  delegate_to: "{{ system.active_controller }}"
  changed_when: false
  when: hostvars[system.active_controller]['pool_size'] | int > 1

- name: Reload systemd
  systemd:
    daemon_reload: true

- name: "Start OSD {{ item.osd_id }} service"
  systemd:
    name: "ceph-osd@{{ item.osd_id }}.service"
    state: started
    enabled: true

- name: Wait until OSDs are up
  command: ceph osd tree -f json
  register: ceph_osd_tree
  retries: 120
  delay: 10
  until: >
    ceph_osd_tree.stdout | from_json | json_query("nodes[?type=='osd'].status") is not none and
    (
      ceph_osd_tree.stdout | from_json | json_query("nodes[?type=='osd'].status")
    ) | select("equalto", "up") | list | length ==
    (
      ceph_osd_tree.stdout | from_json | json_query("nodes[?type=='osd'].status") | length
    )
  changed_when: false

- name: Wait until cluster finishes recovery
  command: ceph health -f json
  register: ceph_health
  retries: 1080
  delay: 10
  until: >
    (
      ceph_health.stdout | from_json | json_query("status") == "HEALTH_OK"
    ) or
    (
      (
        ceph_health.stdout | from_json | json_query("checks")
      | dict2items
      | selectattr("value.severity", "equalto", "HEALTH_WARN")
      | list
      | length
      ) == 0
    )
  changed_when: false

- name: Wait until all PGs are active+clean
  command: timeout 30 ceph pg stat
  register: ceph_pg_stat
  until: >
    ceph_pg_stat.stdout is search('^([0-9]+) pgs: \\1 active\\+clean')
  retries: 240
  delay: 10
  changed_when: false

- name: Wait until the 'recover' keyword goes away from ceph status
  command: timeout 30 ceph -s
  register: ceph_status
  until: >
    'recover' not in ceph_status.stdout
  retries: 120
  delay: 10
  changed_when: false

- name: Display cluster status
  debug:
    var: ceph_status.stdout_lines

- name: Get OSD tree after migrating OSD
  command: timeout 30 ceph osd tree
  register: ceph_osd_tree_output
  changed_when: false

- name: Display OSD tree
  debug:
    var: ceph_osd_tree_output.stdout_lines
