#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: "Check if PVC {{ pvc_map[pv_name].name }} exists"
  shell: "kubectl get pvc -n {{ pvc_map[pv_name].namespace }} {{ pvc_map[pv_name].name }}"
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  register: pvc_check
  failed_when: false
  changed_when: false

- name: "Save PVC {{ pvc_map[pv_name].name }} to {{ tmp_workspace }}/{{ pvc_map[pv_name].name }}.yaml file"
  shell: "kubectl get pvc -n {{ pvc_map[pv_name].namespace }} {{ pvc_map[pv_name].name }} -o yaml | tee {{ tmp_workspace }}/{{ pvc_map[pv_name].name }}.yaml {{ tmp_workspace }}/{{ pvc_map[pv_name].name }}.yaml.bkp {{ tmp_workspace }}/{{ pvc_map[pv_name].name }}.yaml.initial"
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  when: pvc_check.rc == 0

- name: Read PVC {{ pvc_map[pv_name].name }} YAML file
  slurp:
    src: "{{ tmp_workspace }}/{{ pvc_map[pv_name].name }}.yaml"
  register: pvc_data_file

- name: Parse the PVC {{ pvc_map[pv_name].name }} YAML content
  set_fact:
    pvc_data: "{{ pvc_data_file.content | b64decode | from_yaml }}"
