#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: "Create secret for registry in namespace {{ pvc_map[pv_name].namespace }}"
  include_tasks: "{{ role_path_common }}/tasks/create_registry_secret.yaml"
  vars:
    namespace: "{{ pvc_map[pv_name].namespace }}"

- name: Render migration_pvs.yaml using template
  template:
    src: migration_pvs.yaml.j2
    dest: "{{ tmp_workspace }}/migration_pvs.yaml"
    mode: 0644
  vars:
    old_pvc_name: "{{ pvc_map[pv_name].name }}-old"
    new_pvc_name: "{{ pvc_map[pv_name].name }}-new"
    namespace: "{{ pvc_map[pv_name].namespace }}"
  register: migration_yaml
  failed_when: migration_yaml.failed

- name: Migrate data between PVs
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  block:
    - name: "Apply migration pod for PV {{ pv_name }}"
      command: "kubectl apply -f {{ tmp_workspace }}/migration_pvs.yaml"

    - name: "Wait for pod to be completed for migration from PV {{ pv_name }}"
      command: kubectl get pods -n {{ pvc_map[pv_name].namespace }} migration-pvs -o 'jsonpath={.status.phase}'
      register: migration_pod_completed
      until: "'Succeeded' in migration_pod_completed.stdout"
      retries: 60
      delay: 10
      changed_when: false
      failed_when:
        - "'Succeeded' not in migration_pod_completed.stdout"

    - name: "Delete migration pod for PV {{ pv_name }}"
      command: "kubectl delete -f {{ tmp_workspace }}/migration_pvs.yaml"
  always:
    - name: Delete registry secret
      command: "kubectl delete -f {{ tmp_workspace }}/secret-migration-registry-local.yaml"
      environment:
        KUBECONFIG: "{{ kubeconfig }}"

- name: Set PV migrated
  set_fact:
    pv_migrated_list: "{{ pv_migrated_list | default([]) | list + [pv_name] }}"
    cacheable: true
  when:
    - pv_data.spec.claimRef is defined
    - pv_name not in (pv_migrated_list | default([]))
