#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Persist backups_path if it was provided
  set_fact:
    backups_path: "{{ backups_path }}"
    cacheable: true
  when: backups_path is defined

- name: Define whether to create temporary migration-lv
  set_fact:
    create_migration_lv: "{{ backups_path is undefined }}"
    cacheable: true
  when: create_migration_lv is undefined

- name: Get the available space for backups
  include_tasks: "get_avail_space_from_{{ backups_dest }}.yaml"
  vars:
    backups_dest: "{{ create_migration_lv | ternary('vg', 'path') }}"

- name: Show backups destination behavior
  debug:
    msg: >
      {{ 'A temporary logical volume will be created for backup data.'
         if create_migration_lv | bool
         else 'Using user-provided backups_path: ' ~ backups_path }}

- name: Set backups_required_bytes if undefined
  block:
    - name: Obtain ceph df information
      command: timeout 30 ceph df --format json
      changed_when: false
      register: ceph_df_json

    - name: Register total used bytes in ceph without consider replicas
      set_fact:
        ceph_used_bytes: >-
          {{ (ceph_df_json.stdout | from_json).pools
             | map (attribute='stats.stored')
             | sum }}

    - name: Register total available bytes in ceph cluster
      set_fact:
        cluster_avail_space_bytes: >-
          {{ (ceph_df_json.stdout | from_json).stats.total_avail_bytes }}
        cacheable: true

    - name: Display cluster_avail_space_bytes
      debug:
        var: cluster_avail_space_bytes

    - name: Register total bytes used by kube-rbdkube-system pool
      set_fact:
        old_pool_bytes: >-
          {{ (ceph_df_json.stdout | from_json).pools
             | selectattr('name', 'equalto', 'kube-rbdkube-system')
             | map (attribute='stats.stored')
             | sum }}
      when: old_pool_exist

    - name: Register backups required space for export_import
      set_fact:
        backups_required_bytes_no_margin: >-
          {{ [ceph_used_bytes | default(0) | int,
              old_pool_bytes | default(0) | int]
              | max }}
      when: migration_type == 'export_import'

    - name: Register backups required space for in_service
      set_fact:
        backups_required_bytes_no_margin: >-
          {{ old_pool_bytes | default(0) }}
      when: migration_type == 'in_service'

    - name: Calculate safety margin for backups
      set_fact:
        backups_safety_margin_bytes: >-
          {{ [backups_required_bytes_no_margin | int * (backups_max_safety_margin_percent | int / 100),
              backups_min_safety_margin_bytes | int] | max }}
        cacheable: true

    - name: Register final backups required space with an extra safety margin
      set_fact:
        backups_required_bytes: >-
          {{ backups_required_bytes_no_margin | int + backups_safety_margin_bytes | int }}
        cacheable: true
  when: backups_required_bytes is undefined

- name: Show available space in bytes
  debug:
    var: avail_space_bytes

- name: Show required space for backups in bytes
  debug:
    var: backups_required_bytes
