#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Get details of all pools in JSON format
  command: timeout 30 ceph osd pool ls detail --format json
  register: ceph_pools_raw
  changed_when: false
  become: true
  when: >
    (extra_pools_list is not defined) or (all_pools_list is not defined)

- name: Parse and cache configuration for ALL pools
  vars:
    _all_pools_json: |
      [
        {% for pool in ceph_pools_raw.stdout | from_json %}
        {
          "name": "{{ pool.pool_name }}",
          "id": {{ pool.pool_id }},
          "pg_num": {{ pool.pg_num }},
          "pgp_num": {{ pool.pg_placement_num }},
          "crush_rule": {{ pool.crush_rule }},
          "crush_rule_name": "replicated_rule",
          "size": {{ pool.size }},
          "min_size": {{ pool.min_size }},
          "application": "{{ pool.application_metadata | list | first | default('') }}"
          {% if pool.pg_autoscale_bias is defined %}
          ,"pg_autoscale_bias": {{ pool.pg_autoscale_bias }}
          {% endif %}
          {% if pool.pg_num_min is defined %}
          ,"pg_num_min": {{ pool.pg_num_min }}
          {% endif %}
          {% if pool.recovery_priority is defined %}
          ,"recovery_priority": {{ pool.recovery_priority }}
          {% endif %}
        }{{ ',' if not loop.last else '' }}
        {% endfor %}
      ]
  set_fact:
    all_pools_list: "{{ _all_pools_json | from_json if _all_pools_json is string else _all_pools_json }}"
    cacheable: true
  when: all_pools_list is not defined

- name: Create extra_pools_list from all_pools_list
  set_fact:
    extra_pools_list: "{{ all_pools_list | selectattr('name', 'in', extra_pools) | list }}"
    cacheable: true
  when:
    - extra_pools is defined
    - extra_pools_list is not defined

- name: Set if old pool kube-rbdkube-system exist
  set_fact:
    old_pool_exist: "{{ all_pools_list | selectattr('name', 'equalto', 'kube-rbdkube-system') | list | length > 0 }}"
    cacheable: true
  when: old_pool_exist is undefined

- name: Cleanup temporary variable
  set_fact:
    _crush_rule_map: null
  when: _crush_rule_map is defined
