#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: "Register total available bytes for {{ vg_name }}"
  shell: "vgs --units b --no-suffix -o vg_free {{ vg_name }} --noheadings --rows | tr -d ' '"
  changed_when: false
  register: vg_space_avail

- name: Register available space for backups and destination name
  set_fact:
    avail_space_bytes: "{{ vg_space_avail.stdout }}"
    backups_dest_name: "{{ vg_name }}"
