#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: "Get Ceph information"
  include_tasks: ceph_info.yaml

- name: "Get OSDs information"
  include_tasks: osds_info.yaml

- name: "Get CephFS subvolumes information"
  include_tasks: cephfs_subvolumes_info.yaml

- name: "Get Ceph Pools information"
  include_tasks: ceph_pools_info.yaml

- name: "Get PVCs information"
  include_tasks: pvcs_info.yaml

- name: "Get storage-backend information"
  include_tasks: storage_backend_info.yaml

- name: Get backups info and behavior
  include_tasks: backups_info.yaml
  when: migration_type == "export_import" or old_pool_exist and migration_type != "redeploy"

- name: Get network info
  include_tasks: network_info.yaml

- name: Get snapshots info
  include_tasks: "snapshot_info.yaml"
