#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Get Debian codename
  shell: grep VERSION_CODENAME /etc/os-release | cut -d'=' -f2
  register: codename
  changed_when: false

- name: Set codename facts
  set_fact:
    is_trixie: "{{ codename.stdout == 'trixie' }}"
    is_bullseye: "{{ codename.stdout == 'bullseye' }}"

- name: Main execution block
  block:
    - name: "Get storage-backend information"
      include_tasks: storage_backend_info.yaml

    - name: "Get Ceph information"
      include_tasks: ceph_info.yaml

    - name: "Get OSDs information"
      include_tasks: osds_info.yaml

    - name: "Get CephFS subvolumes information"
      include_tasks: cephfs_subvolumes_info.yaml

    - name: "Get Ceph Pools information"
      include_tasks: ceph_pools_info.yaml

    - name: Get network info
      include_tasks: network_info.yaml

    - name: Get snapshots info
      include_tasks: "snapshot_info.yaml"

    - name: Get LVM OSDs info
      include_tasks: "lvm_disk_info.yaml"
      when: migration_target == "lvm"

    - name: Get DataVolume info
      include_tasks: "data_volume_info.yaml"

    - name: Get RBD size info
      include_tasks: "rbd_size_info.yaml"

    - name: Get backups info and behavior
      include_tasks: backups_info.yaml
      when: migration_type == "export_import" or old_pool_exist and migration_type != "redeploy"

  rescue:
    - include_tasks: "{{ role_path_common }}/tasks/clear_facts_cache.yaml"

    - include_tasks: "{{ role_path_common }}/tasks/fail_playbook.yaml"
