#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Get cluster-pod IP family
  become: true
  become_user: postgres
  command: psql -d sysinv -t -A -c "SELECT primary_pool_family FROM networks WHERE type = 'cluster-pod'"
  register: cluster_ip_family_result
  when: cluster_ip_family is undefined

- name: Set cluster_ip_family
  set_fact:
    cluster_ip_family: "{{ cluster_ip_family_result.stdout }}"
    cacheable: true
  when: cluster_ip_family is undefined

- name: Show cluster_ip_family
  debug:
    var: cluster_ip_family
