#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Get OSDs information from ceph
  shell: "ceph osd tree -f json | python3 -c '{{ lookup('file', 'get_osd_info.py') }}'"
  register: ceph_osds_info
  changed_when: false

- name: Build OSD info lookup table
  set_fact:
    ceph_osd_lookup: "{{ ceph_osd_lookup | default({}) | combine({ item_json.osd_id: item_json }) }}"
  loop: "{{ ceph_osds_info.stdout_lines }}"
  loop_control:
    extended: true
  vars:
    item_json: "{{ item | from_json }}"
  when: ceph_osds_info.stdout_lines is defined

- name: Get list of OSD IDs from database lookup
  set_fact:
    all_osd_ids: "{{ ceph_disks_by_host_db.values() | flatten | map(attribute='osd_id') | list }}"

- name: Build OSD info lookup table with metadata
  shell: "ceph osd metadata {{ item }} -f json"
  register: osd_metadata_results
  changed_when: false
  loop: "{{ all_osd_ids }}"

- name: Integrate OSD metadata (including objectstore type) into a lookup table
  set_fact:
    ceph_osd_lookup: >-
      {{
        ceph_osd_lookup | default({}) | combine({
          item_json.id: (ceph_osd_lookup[item_json.id] | default({})) | combine({
            'osd_objectstore': item_json.osd_objectstore
          })
        })
      }}
  loop: "{{ osd_metadata_results.results }}"
  loop_control:
    extended: true
    label: "{{ item_json.id }}"
  vars:
    item_json: "{{ item.stdout | from_json }}"
  when: item.rc == 0 and item.stdout | length > 0

- name: Integrate Ceph OSD data into ceph_disks_by_host
  set_fact:
    ceph_disks_by_host: "{{ ceph_disks_by_host | default({}) | combine({ item.key: _enriched_disks | from_json }) }}"
    cacheable: true
  loop: "{{ ceph_disks_by_host_db | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  vars:
    _enriched_disks: >-
      [{% for disk in item.value %}
      {{ disk | combine(ceph_osd_lookup[disk.osd_id] | default({})) | to_json }}{% if not loop.last %},{% endif %}
      {% endfor %}]
  when: ceph_osd_lookup is defined