- name: Cache erase_rbd_snapshots
  set_fact:
    erase_rbd_snapshots_cache: "{{ erase_rbd_snapshots }}"
    cacheable: true
  when: erase_rbd_snapshots_cache is undefined

- name: Get VolumeSnapshotContent for RBD and set var
  block:
    - name: Get VolumeSnapshotContent for RBD
      shell: >
        kubectl get volumesnapshotcontents
        -o jsonpath='{range .items[?(@.spec.driver=="rbd.csi.ceph.com")]}{.metadata.name}{"\n"}{end}'
      register: rbd_vsc_output
      environment:
        KUBECONFIG: "{{ kubeconfig }}"

    - name: Set rbd_vsc
      set_fact:
        rbd_vsc: "{{ rbd_vsc_output.stdout_lines }}"
        cacheable: true
  when: rbd_vsc is undefined

- name: Display rbd VolumeSnapshotContents
  debug:
    var: rbd_vsc

- name: Get VolumeSnapshot for RBD and set var
  block:
    - name: Get VolumeSnapshot for RBD
      shell: >
        kubectl get VolumeSnapshot
        -o jsonpath='{range .items[?(@.spec.volumeSnapshotClassName=="rbd-snapshot")]}{.metadata.namespace}{" "}{.metadata.name}{"\n"}{end}' -A
      register: rbd_vs_output
      environment:
        KUBECONFIG: "{{ kubeconfig }}"

    - name: Set rbd_vs_raw
      set_fact:
        rbd_vs_raw: "{{ rbd_vs_output.stdout_lines }}"
        cacheable: true
  when: rbd_vs_raw is undefined

- name: Build dict with RBD VolumeSnapshot names keyed by namespace
  set_fact:
    rbd_vs_by_namespace: >
      {{
      rbd_vs_by_namespace
      | default({})
      | combine(
          { item.split()[0]: [{ 'name': item.split()[1] }]},
          list_merge='append'
        )
      }}
  loop: "{{ rbd_vs_raw }}"
  when: rbd_vs_raw | default([]) | length > 0

- name: Display rbd VolumeSnapshot by namespace
  debug:
    var: rbd_vs_by_namespace
  when: rbd_vs_by_namespace is defined

- name: Get VolumeSnapshotContent for CephFs and set var
  block:
    - name: Get VolumeSnapshotContent for CephFs
      shell: >
        kubectl get volumesnapshotcontents
        -o jsonpath='{range .items[?(@.spec.driver=="cephfs.csi.ceph.com")]}{.metadata.name}{"\n"}{end}'
      register: cephfs_vsc_output
      environment:
        KUBECONFIG: "{{ kubeconfig }}"

    - name: Set cephfs_vsc
      set_fact:
        cephfs_vsc: "{{ cephfs_vsc_output.stdout_lines }}"
        cacheable: true
  when: cephfs_vsc is undefined

- name: Display CephFs VolumeSnapshotContents
  debug:
    var: cephfs_vsc

- name: Get VolumeSnapshot for CephFs and set var
  block:
    - name: Get VolumeSnapshot for CephFs
      shell: >
        kubectl get VolumeSnapshot
        -o jsonpath='{range .items[?(@.spec.volumeSnapshotClassName=="cephfs-snapshot")]}{.metadata.namespace}{" "}{.metadata.name}{"\n"}{end}' -A
      register: cephfs_vs_output
      environment:
        KUBECONFIG: "{{ kubeconfig }}"

    - name: Set cephfs_vs_raw
      set_fact:
        cephfs_vs_raw: "{{ cephfs_vs_output.stdout_lines }}"
        cacheable: true
  when: cephfs_vs_raw is undefined

- name: Build dict with CephFs VolumeSnapshot names keyed by namespace
  set_fact:
    cephfs_vs_by_namespace: >
      {{
      cephfs_vs_by_namespace
      | default({})
      | combine(
          { item.split()[0]: [{ 'name': item.split()[1] }]},
          list_merge='append'
        )
      }}
  loop: "{{ cephfs_vs_raw }}"
  when: cephfs_vs_raw | default([]) | length > 0

- name: Display CephFs VolumeSnapshot by namespace
  debug:
    var: cephfs_vs_by_namespace
  when: cephfs_vs_by_namespace is defined
