---
#
# Copyright (c) 2025 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# This task file monitors a single enroll-init stage by waiting for IPMI SEL events
# and checking the results. It waits for either success or failure events for the
# given stage and fails immediately if a failure event is detected.
#
# This task file is included by the enroll_init.yml playbook for each monitoring stage
# (factory setup, manual ca certs check, k8s leaf certs check, system local ca certs,
# platform cloud-init, and custom cloud-init).
#

- name: "Waiting {{ item.timeout }} seconds for {{ item.name }} IPMI SEL event"
  include_role:
    name: common/ipmi_monitor
  vars:
    ipmi_data_values: "{{ item.success_data }},{{ item.failure_data }}"
    ipmi_timeout: "{{ item.timeout }}"
    # Disable event-type checks in the common role so it doesn't fail by itself
    check_event_type: false

# Capture raw monitoring result from the common role
- name: Capture monitoring result for this stage
  set_fact:
    stage_monitor_success: "{{ monitoring_json.success | default(false) }}"
    detected_event_data: "{{ monitoring_json.matched_data | default(omit) }}"
  changed_when: false

# Fail fast on timeout (no matching event during the stage timeout)
- name: Fail if stage timed out
  fail:
    msg: "IPMI monitoring for stage '{{ item.name }}' timed out without detecting target event"
  when: not stage_monitor_success

# Failure path: executed only if the event is defined and is not a success
- block:
    # First build the failure message
    - name: Build failure message
      set_fact:
        # If item.failure_map is defined and contains the code, use that specific message.
        # Otherwise, use item.failure_msg
        stage_failure_msg_effective: >-
          {{
            (item.failure_map[detected_event_data]
             if (item.failure_map is defined and detected_event_data in item.failure_map)
             else item.failure_msg )
          }}
      changed_when: false

    # Fail when the detected event is in of the failure codes
    - name: "Check {{ item.name }} IPMI monitoring result"
      fail:
        msg: >-
          {{ (operation_string | default('Enroll init')) }} failed:
          {{ stage_failure_msg_effective }}
      when: detected_event_data in (item.failure_data.split(','))
  when:
    - detected_event_data is defined
    - detected_event_data != item.success_data

- debug:
    msg: "{{ item.name | capitalize }} completed successfully"
