---
#
# Copyright (c) 2022-2025 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# These tasks get information from the running system and use it to
# generate a certificate spec file which is going to be applied to
# kubernetes at a later step
#
- name: Validate subject fields
  include_role:
    name: common/validate-cert-subject-fields

- block:
  - name: Get primary management ip addresses
    include_tasks: roles/common/get_network_addresses_from_sysinv/tasks/get_network_addresses_from_sysinv.yml
    vars:
      network_type: mgmt
      network_stack: primary

  - debug:
      msg: primary management addresses {{ addresses }}

  - name: Assign primary management ip addresses
    set_fact:
      management_floating_ip_primary: "{{ addresses.floating_address }}"
      management_c0_ip_primary: "{{ addresses.controller0_address }}"
      management_c1_ip_primary: "{{ addresses.controller1_address }}"

- block:
  - name: Get secondary management ip addresses
    include_tasks: roles/common/get_network_addresses_from_sysinv/tasks/get_network_addresses_from_sysinv.yml
    vars:
      network_type: mgmt
      network_stack: secondary

  - debug:
      msg: secondary management addresses {{ addresses }}

  - name: Assign secondary management ip addresses
    set_fact:
      management_floating_ip_secondary: "{{ addresses.floating_address }}"
      management_c0_ip_secondary: "{{ addresses.controller0_address }}"
      management_c1_ip_secondary: "{{ addresses.controller1_address }}"

- block:
  - name: Get primary oam ip addresses
    include_tasks: roles/common/get_network_addresses_from_sysinv/tasks/get_network_addresses_from_sysinv.yml
    vars:
      network_type: oam
      network_stack: primary

  - debug:
      msg: primary oam addresses {{ addresses }}

  - name: Assign primary oam ip addresses
    set_fact:
      oam_ip_primary: "{{ addresses.floating_address }}"

- block:
  - name: Get secondary oam ip addresses
    include_tasks: roles/common/get_network_addresses_from_sysinv/tasks/get_network_addresses_from_sysinv.yml
    vars:
      network_type: oam
      network_stack: secondary

  - debug:
      msg: secondary oam addresses {{ addresses }}

  - name: Assign secondary oam ip addresses
    set_fact:
      oam_ip_secondary: "{{ addresses.floating_address }}"

- block:
  - name: Get primary cluster-host ip addresses
    include_tasks: roles/common/get_network_addresses_from_sysinv/tasks/get_network_addresses_from_sysinv.yml
    vars:
      network_type: cluster-host
      network_stack: primary

  - debug:
      msg: primary cluster-host addresses {{ addresses }}

  - name: Assign primary cluster-host ip addresses
    set_fact:
      kubernetes_cluster_floating_ip_primary: "{{ addresses.floating_address }}"
      kubernetes_cluster_c0_ip_primary: "{{ addresses.controller0_address }}"
      kubernetes_cluster_c1_ip_primary: "{{ addresses.controller1_address }}"

- block:
  - name: Get secondary cluster-host ip addresses
    include_tasks: roles/common/get_network_addresses_from_sysinv/tasks/get_network_addresses_from_sysinv.yml
    vars:
      network_type: cluster-host
      network_stack: secondary

  - debug:
      msg: secondary cluster-host addresses {{ addresses }}

  - name: Assign secondary cluster-host ip addresses
    set_fact:
      kubernetes_cluster_floating_ip_secondary: "{{ addresses.floating_address }}"
      kubernetes_cluster_c0_ip_secondary: "{{ addresses.controller0_address }}"
      kubernetes_cluster_c1_ip_secondary: "{{ addresses.controller1_address }}"

- block:
  - name: Get primary admin ip addresses
    include_tasks: roles/common/get_network_addresses_from_sysinv/tasks/get_network_addresses_from_sysinv.yml
    vars:
      network_type: admin
      network_stack: primary

  - debug:
      msg: primary admin addresses {{ addresses }}

  - name: Assign primary admin ip addresses
    set_fact:
      admin_floating_ip_primary: "{{ addresses.floating_address }}"

- block:
  - name: Get secondary admin ip addresses
    include_tasks: roles/common/get_network_addresses_from_sysinv/tasks/get_network_addresses_from_sysinv.yml
    vars:
      network_type: admin
      network_stack: secondary

  - debug:
      msg: secondary admin addresses {{ addresses }}

  - name: Assign secondary admin ip addresses
    set_fact:
      admin_floating_ip_secondary: "{{ addresses.floating_address }}"

# Try to get from sourced credentials and fall back to 'system show' if not available
- name: Get region name
  shell: |
    echo "${OS_REGION_NAME:-$(source /etc/platform/openrc && system show | grep region_name | awk '{ print $4 }')}"
  register: region_name_register

- name: Get distributed_cloud role
  shell: |
    source /etc/platform/platform.conf; echo $distributed_cloud_role
  register: dc_role

- name: Get cert-manager api version
  shell: |
    kubectl --kubeconfig=/etc/kubernetes/admin.conf api-versions | grep cert-manager.io | sort -n | tail -1
  register: cert_manager_api_version

- name: Generate kubernetes yaml for cert-manager resources
  template:
    src: platform_certificates.yml.j2
    dest: "{{ destination }}"
    mode: '0640'
  become: yes
