---
#
# Copyright (c) 2022-2025 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# These tasks get information from the running system and use it to
# generate a certificate spec file which is going to be applied to
# kubernetes at a later step
#
- name: Validate subject fields
  include_role:
    name: common/validate-cert-subject-fields

- block:
  - name: Get primary and secondary ip addresses
    include_tasks: roles/common/get_network_addresses_from_sysinv/tasks/get_network_addresses_from_sysinv.yml
    vars:
      network_requests:
        - network_type: mgmt
          network_stack: primary
        - network_type: mgmt
          network_stack: secondary
        - network_type: oam
          network_stack: primary
        - network_type: oam
          network_stack: secondary
        - network_type: cluster-host
          network_stack: primary
        - network_type: cluster-host
          network_stack: secondary
        - network_type: admin
          network_stack: primary
        - network_type: admin
          network_stack: secondary

  - debug:
      msg: primary and secondary addresses {{ addresses }}

  - name: Assign primary and secondary ip addresses
    set_fact:
      management_floating_ip_primary: "{{ addresses.mgmt_primary.floating_address }}"
      management_c0_ip_primary: "{{ addresses.mgmt_primary.controller0_address }}"
      management_c1_ip_primary: "{{ addresses.mgmt_primary.controller1_address }}"
      management_floating_ip_secondary: "{{ addresses.mgmt_secondary.floating_address }}"
      management_c0_ip_secondary: "{{ addresses.mgmt_secondary.controller0_address }}"
      management_c1_ip_secondary: "{{ addresses.mgmt_secondary.controller1_address }}"
      oam_ip_primary: "{{ addresses.oam_primary.floating_address }}"
      oam_ip_secondary: "{{ addresses.oam_secondary.floating_address }}"
      kubernetes_cluster_floating_ip_primary: "{{ addresses.cluster_host_primary.floating_address }}"
      kubernetes_cluster_c0_ip_primary: "{{ addresses.cluster_host_primary.controller0_address }}"
      kubernetes_cluster_c1_ip_primary: "{{ addresses.cluster_host_primary.controller1_address }}"
      kubernetes_cluster_floating_ip_secondary: "{{ addresses.cluster_host_secondary.floating_address }}"
      kubernetes_cluster_c0_ip_secondary: "{{ addresses.cluster_host_secondary.controller0_address }}"
      kubernetes_cluster_c1_ip_secondary: "{{ addresses.cluster_host_secondary.controller1_address }}"
      admin_floating_ip_primary: "{{ addresses.admin_primary.floating_address }}"
      admin_floating_ip_secondary: "{{ addresses.admin_secondary.floating_address }}"

# Try to get from sourced credentials and fall back to 'system show' if not available
- name: Get region name
  shell: |
    echo "${OS_REGION_NAME:-$(source /etc/platform/openrc && system show | grep region_name | awk '{ print $4 }')}"
  register: region_name_register

- name: Get distributed_cloud role
  shell: |
    source /etc/platform/platform.conf; echo $distributed_cloud_role
  register: dc_role

- name: Get cert-manager api version
  shell: |
    kubectl --kubeconfig=/etc/kubernetes/admin.conf api-versions | grep cert-manager.io | sort -n | tail -1
  register: cert_manager_api_version

- name: Generate kubernetes yaml for cert-manager resources
  template:
    src: platform_certificates.yml.j2
    dest: "{{ destination }}"
    mode: '0640'
  become: yes
