#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Check rook-ceph status to be applying to continue
  include_tasks: "{{ role_path_common }}/tasks/check_app_status.yaml"
  vars:
    app_name_to_check: "rook-ceph"
    success_statuses: "applying"
    retries: 6
    delay: 10

- name: Wait for app to start applying after docker images retrieval
  include_tasks: "{{ role_path_common }}/tasks/check_app_progress.yaml"
  vars:
    app_name_to_check: "rook-ceph"
    target_values: ["%\\%%"]
    comparison_operator: "LIKE"
    db_field_to_check: "progress"
    retries: 90
    delay: 10
  when: app_status_check.stdout.strip() == "applying"

- name: Wait for all rook-ceph-osd-prepare jobs to be created
  include_tasks: "{{ role_path_common }}/tasks/kubernetes/wait_resources_condition.yaml"
  vars:
    k8s_namespace: "rook-ceph"
    k8s_resource_prefix: "osd-prepare"
    k8s_retries: 360
    wait_mode: "created"
    fact_name: "osd_prepare_jobs"

- name: Wait for all rook-ceph-osd-prepare jobs to be completed
  include_tasks: "{{ role_path_common }}/tasks/kubernetes/wait_resources_condition.yaml"
  vars:
    k8s_namespace: "rook-ceph"
    k8s_resource_list: "{{ osd_prepare_jobs }}"
    wait_mode: "complete"