#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Fail if migration type target is not supported for LVM
  fail:
    msg: "In-service migration not supported for LVM target"
  when: migration_target == "lvm"

- name: Fail if migration is not supported on this system
  fail:
    msg: "In-service migration not supported in {{ system.system_deployment }} deployment"
  when: system.system_deployment == "STORAGE"

- name: Check SX can mark out one OSD at a time
  include_tasks: sx_osd_checks.yaml
  when:
    - system.system_deployment == "AIO-SX"
    - pool_size | int < 2

- name: Check space for backups
  include_tasks: "{{ role_path_common }}/tasks/check_space_for_backups.yaml"
  when: old_pool_exist | bool
