#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

rook_ceph_manifests:
  - common.yaml
  - crds.yaml
  - configmap-overrides.yaml

rook_ceph_template_manifests:
  - name: operator.yaml
  - name: cluster.yaml
  - name: toolbox.yaml
