---
#
# Copyright (c) 2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
#   This playbook updates keystone passwords during subcloud enrollment
#

- name: Create a temporary file for user list
  ansible.builtin.tempfile:
    state: file
    prefix: "keystone_user_list_"
  register: temp_keystone_pass_file

- name: Write user list to a temporary file
  copy:
    content: "{{ user_list | to_nice_json }}"
    dest: "{{ temp_keystone_pass_file.path }}"

- name: Update keystone and keyring user passwords
  script: >
    update_keystone_keyring_passwords.py
    {{ software_version }}
    {{ temp_keystone_pass_file.path }}
  register: update_keystone_password_result
  failed_when: false

- debug: var=update_keystone_password_result

- name: Remove the temporary file
  file:
    path: "{{ temp_keystone_pass_file.path }}"
    state: absent

- name: Fail if update keystone password script throws an exception
  fail:
    msg: "Failed to update keystone passwords."
  when: update_keystone_password_result.rc != 0
