#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: "[PVC {{ pvc.name }}] Create CephFS backup file"
  shell: |
    set -e -o pipefail
    BACKUP_NAME="backup-${PVC_NAME}.dar"
    BKP_FILE_POD="/backup/${BACKUP_NAME}"
    BKP_FILE_HOST="${CEPHFS_BACKUP_DIR}/${BACKUP_NAME}"

    echo "Starting backup of /data/{{ pvc.name }}/..."
    kubectl exec -n {{ cephfs_pvc_namespace }} {{ batch_pod_name }} -- dar -c "$BKP_FILE_POD" -R "/data/{{ pvc.name }}/" -z -ah -Q || { echo "ERROR: dar backup failed, possibly out of space"; exit 1; }

    echo "Verifying backup integrity..."
    kubectl exec -n {{ cephfs_pvc_namespace }} {{ batch_pod_name }} -- dar -t "$BKP_FILE_POD" -Q || { echo "ERROR: dar integrity check failed"; exit 1; }
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
    PVC_NAME: "{{ cephfs_pvc_namespace }}-{{ pvc.name }}"
    CEPHFS_BACKUP_DIR: "{{ backups_cephfs_path }}"
  register: backup_result
