#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: "Ensure {{ tmp_workspace }} exist"
  file:
    path: "{{ tmp_workspace }}"
    state: directory

- name: List OSDs for FSID
  shell: ls {{ rook_base_host }}/ | grep {{ hostvars[system.active_controller]['ceph_fsid'] }}
  register: osds_result
  changed_when: false

- name: Set osds fact
  set_fact:
    osds: "{{ osds_result.stdout_lines }}"

- name: Read OSD keyring
  slurp:
    src: "{{ rook_base_host }}/{{ item }}/keyring"
  register: osd_keyring_file
  loop: "{{ osds }}"
  loop_control:
    label: "{{ item }}"

- name: Read OSD id
  slurp:
    src: "{{ rook_base_host }}/{{ item }}/whoami"
  register: osd_id_file
  loop: "{{ osds }}"
  loop_control:
    label: "{{ item }}"

- name: Write temporary osd keyring file
  copy:
    dest: "{{ tmp_workspace }}/osd.{{ osd_id_file.results[osd_index].content | b64decode | trim }}.keyring"
    content: |
      [osd.{{ osd_id_file.results[osd_index].content | b64decode | trim }}]
          key = {{ osd_keyring_file.results[osd_index].content | b64decode | regex_search('key = (.*)', '\1') | first }}
          caps mgr = "allow profile osd"
          caps mon = "allow profile osd"
          caps osd = "allow *"
    owner: root
    group: root
    mode: "0600"
  loop: "{{ osds }}"
  loop_control:
    index_var: osd_index

# To avoid error when importing OSD keyring
- name: Verify that all rook-ceph mon pods are Running
  delegate_to: "{{ system.active_controller }}"
  shell: |
    kubectl get pods -n rook-ceph \
      -o jsonpath='{range .items[*]}{.metadata.name}{" "}{.status.phase}{"\n"}{end}' \
    | grep -E '^rook-ceph-mon-[a-z]+' \
    | awk '{if ($2 != "Running") {print $0; exit 1}}'
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  register: ceph_pods_check
  retries: 60
  delay: 10
  until: ceph_pods_check.rc == 0

- name: Import OSD keyring into Ceph
  command: >
      ceph auth import -i {{ tmp_workspace }}/osd.{{ osd_id_file.results[osd_index].content | b64decode | trim }}.keyring
  loop: "{{ osds }}"
  loop_control:
    index_var: osd_index

- name: Clean keyrings generated before
  shell: rm -rvf {{ tmp_workspace }}/osd.*
  register: keyrings_deleted

- name: Debug keyrings_deleted var
  debug:
    var: keyrings_deleted.stdout_lines

- name: Cleanup temporary rook-ceph folder
  file:
    path: "{{ tmp_workspace }}"
    state: absent
