#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: "Check if PV {{ pv_name }} exists"
  shell: "kubectl get pv {{ pv_name }}"
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  register: pv_check
  failed_when: false
  changed_when: false

- name: "Save PV {{ pv_name }} to {{ tmp_workspace }}/{{ pv_name }}.yaml file"
  shell: "kubectl get pv {{ pv_name }} -o yaml | tee {{ tmp_workspace }}/{{ pv_name }}.yaml {{ tmp_workspace }}/{{ pv_name }}.yaml.bkp"
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  when: pv_check.rc == 0

- name: Read PV {{ pv_name }} YAML file
  slurp:
    src: "{{ tmp_workspace }}/{{ pv_name }}.yaml"
  register: pv_data_file

- name: Parse the PV {{ pv_name }} YAML content
  set_fact:
    pv_data: "{{ pv_data_file.content | b64decode | from_yaml }}"

- name: Set PVC information
  set_fact:
    pvc_map: "{{ pvc_map | default({}) | combine({pv_name: {'name': pv_data.spec.claimRef.name, 'namespace': pv_data.spec.claimRef.namespace}}) }}"
    cacheable: true
  when:
    - pv_data.spec.claimRef is defined
    - pv_name not in (pvc_map | default({}))

- name: Get PVC info
  include_tasks: get_pvc.yaml

