#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: "Ensure {{ tmp_workspace }} exist"
  file:
    path: "{{ tmp_workspace }}"
    state: directory

- name: "Get the list of all PersistentVolume names"
  command: "kubectl get pv -o jsonpath='{.items[?(@.spec.cephfs)].metadata.name}'"
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  register: pv_list_result
  changed_when: false
  when: old_pv_list is not defined

- name: "Set old_pv_list fact"
  set_fact:
    old_pv_list: "{{ pv_list_result.stdout }}"
    cacheable: true
  when: old_pv_list is not defined

- name: "Include tasks to iterate over each PV"
  include_tasks: process_pv.yaml
  loop: "{{ old_pv_list.split() }}"
  loop_control:
    loop_var: pv_name
  when: old_pv_list | length > 0

# Clean only if all tasks was completed, to avoid errors when reexecuting.
- name: "Cleanup {{ tmp_workspace }}"
  file:
    path: "{{ tmp_workspace }}"
    state: absent
