#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Connectivity check block
  block:
    - name: "Validate if host is reachable"
      wait_for_connection:
        timeout: 60
      register: conn_check

  rescue:
    - name: "Handle connection failure"
      debug:
        msg: "Connection failed for {{ inventory_hostname }}: {{ ansible_failed_result.msg | default('Unknown error') }}"
      when: "'Permission denied' not in (ansible_failed_result.msg | default(''))"

    - include_tasks: "{{ role_path_common }}/tasks/fail_playbook.yaml"
      when: "'Permission denied' not in (ansible_failed_result.msg | default(''))"
