#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Add default memory configs for worker profile
  become: true
  become_user: postgres
  command: >-
    psql -d sysinv -t -A -c "
    UPDATE i_imemory
    SET
        hugepages_configured        = 't',

        -- vSwitch hugepages
        vswitch_hugepages_size_mib  = 1024,
        vswitch_hugepages_reqd      = 0,
        vswitch_hugepages_nr        = 0,
        vswitch_hugepages_avail     = 0,

        -- 2M hugepages
        \"vm_hugepages_nr_2M\"           = 0,
        \"vm_hugepages_avail_2M\"        = 0,
        \"vm_hugepages_nr_2M_pending\"   = 0,
        \"vm_hugepages_possible_2M\"     = 0,
        \"vm_hugepages_2M_percentage\"   = 0,

        -- 1G hugepages
        \"vm_hugepages_nr_1G\"           = 0,
        \"vm_hugepages_avail_1G\"        = 0,
        \"vm_hugepages_nr_1G_pending\"   = 0,
        \"vm_hugepages_possible_1G\"     = 0,
        \"vm_hugepages_use_1G\"          = 't',
        \"vm_hugepages_1G_percentage\"   = 0,

        -- 4K pages
        \"vm_hugepages_nr_4K\" = COALESCE(\"vm_hugepages_nr_4K\", 0),

        -- misc
        vm_pending_as_percentage = 'f',
        capabilities             = NULL,

        -- core memory fields
        node_memtotal_mib = memtotal_mib

    WHERE forihostid=(SELECT id FROM i_host WHERE hostname='{{ item }}');"
  loop: "{{ groups.storages }}"
  loop_control:
    label: "{{ item }}"

- name: Set platform memory on NUMA 0
  environment: "{{ system_env }}"
  command: system host-memory-modify -m {{ min_storage_memory_mib }} {{ item }} 0
  loop: "{{ groups.storages }}"
  loop_control:
    label: "{{ item }}"

- name: Set minimum platform memory on NUMA 1
  environment: "{{ system_env }}"
  command: system host-memory-modify -m 1000 {{ item }} 1
  loop: "{{ groups.storages }}"
  loop_control:
    label: "{{ item }}"
  when: storages_have_numa_1 | bool

- name: Set platform CPUs on NUMA 0
  environment: "{{ system_env }}"
  command: system host-cpu-modify -f platform -p0 {{ min_storage_cpus }} {{ item }}
  loop: "{{ groups.storages }}"
  loop_control:
    label: "{{ item }}"

- name: Set application CPUs on NUMA 1
  environment: "{{ system_env }}"
  command: system host-cpu-modify -f platform -p1 1 {{ item }}
  loop: "{{ groups.storages }}"
  loop_control:
    label: "{{ item }}"
  when: storages_have_numa_1 | bool

- name: Read CPU config prior to unlock
  environment: "{{ system_env }}"
  command: system host-cpu-list {{ item }}
  loop: "{{ groups.storages }}"
  loop_control:
    label: "{{ item }}"
  register: storage_cpu_config
  changed_when: false

- name: Debug storage_cpu_config
  debug:
    msg: "{{ item.stdout_lines | replace('\\n', '\n') }}"
  loop: "{{ storage_cpu_config.results }}"
  loop_control:
    label: "{{ item.item }}"

- name: Read memory config prior to unlock
  environment: "{{ system_env }}"
  command: system host-memory-list {{ item }}
  loop: "{{ groups.storages }}"
  loop_control:
    label: "{{ item }}"
  register: storage_memory_config
  changed_when: false

- name: Debug storage_memory_config
  debug:
    msg: "{{ item.stdout_lines | replace('\\n', '\n') }}"
  loop: "{{ storage_memory_config.results }}"
  loop_control:
    label: "{{ item.item }}"
