#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Se worker personality in DB
  become: true
  become_user: postgres
  command: >
    psql -d sysinv -t -A -c "
    UPDATE i_host SET personality='worker', subfunctions='worker'
    WHERE hostname LIKE 'storage%';"

- name: Delete peers in DB
  become: true
  become_user: postgres
  command: >
    psql -d sysinv -t -A -c "
    UPDATE i_host SET peer_id=NULL WHERE hostname like 'storage%';"

- name: Change personality with host-update
  environment: "{{ system_env }}"
  command: system host-update {{ item }} personality=worker subfunctions=worker
  loop: "{{ groups.storages }}"
  loop_control:
    label: "{{ item }}"
  register: host_update_output

- name: Debug host-update result
  debug:
    msg: "{{ item.stdout_lines | replace('\\n', '\n') }}"
  loop: "{{ host_update_output.results }}"
  loop_control:
    label: "{{ item.item }}"

- name: Change administrativeState from unlocked to locked
  lineinfile:
    path: "{{ tmp_workspace }}/storage-to-worker-cpu-memory.yaml"
    regexp: '^(\s*)administrativeState:\s*unlocked'
    line: '\1administrativeState: locked'
    backrefs: yes

- name: Apply storage DM file with locked state
  command: kubectl apply -f {{ tmp_workspace }}/storage-to-worker-cpu-memory.yaml
  environment:
    KUBECONFIG: "{{ kubeconfig }}"

- name: Give DM a few seconds to apply the new config
  pause:
    seconds: 15
  changed_when: false

