#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Reinstall storages
  environment: "{{ system_env }}"
  command: system host-reinstall {{ item }}
  loop: "{{ groups.storages }}"
  loop_control:
    label: "{{ item }}"
  register: reinstall_output

- name: Debug reinstall_output result
  debug:
    msg: "{{ item.stdout_lines | replace('\\n', '\n') }}"
  loop: "{{ reinstall_output.results }}"
  loop_control:
    label: "{{ item.item }}"

- name: Wait until all storage nodes are locked|disabled|offline
  become: true
  become_user: postgres
  command: >-
    psql -d sysinv -t -A -c
    "SELECT COUNT(*) FROM i_host
     WHERE hostname LIKE 'storage%'
       AND administrative = 'locked'
       AND operational = 'disabled'
       AND availability = 'offline';"
  register: storage_host_offline_count
  until: storage_host_offline_count.stdout | int == groups.storages | length
  retries: 180
  delay: 10
  changed_when: false

- name: Wait until all storage nodes are locked|disabled|online
  become: true
  become_user: postgres
  command: >-
    psql -d sysinv -t -A -c
    "SELECT COUNT(*) FROM i_host
     WHERE hostname LIKE 'storage%'
       AND administrative = 'locked'
       AND operational = 'disabled'
       AND availability = 'online';"
  register: storage_host_online_count
  until: storage_host_online_count.stdout | int == groups.storages | length
  retries: 360
  delay: 10
  changed_when: false

- name: Wait until all storage nodes done reinstalling
  become: true
  become_user: postgres
  command: >-
    psql -d sysinv -t -A -c
    "SELECT COUNT(*) FROM i_host
     WHERE hostname LIKE 'storage%'
       AND inv_state = 'inventoried'
       AND action_state = 'reinstalled';"
  register: storage_host_reinstalling_count
  until: storage_host_reinstalling_count.stdout | int == groups.storages | length
  retries: 120
  delay: 10
  changed_when: false
