#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Block to run or not this role
  block:
    - name: Update storage-backend migration capabilities
      become: true
      become_user: postgres
      command: >
        psql -d sysinv -c "
        UPDATE storage_backend
        SET capabilities = (
          capabilities::jsonb
          || '{\"migration_type\": \"{{ migration_type }}\", \"migration_step\": \"{{ checkpoint }}\", \"migration_status\": \"in-progress\"}'::jsonb
        )::text
        WHERE id = {{ storage_backend.id }};
        "
      vars:
        storage_backend: "{{ hostvars[system.active_controller].storage_backend }}"
      run_once: true
      delegate_to: "{{ system.active_controller }}"
      when: hostvars[system.active_controller].storage_backend is defined

    - name: "Run role {{ role_name }}"
      include_tasks: "{{ roles_dir_path }}/{{ role_name }}/tasks/run_role.yaml"

    - name: Mark this role as run
      set_fact:
        checkpoints: "{{ checkpoints | default([]) + [checkpoint] }}"
        cacheable: true
  vars:
    checkpoint: "{{ checkpoint_name | default(role_name) }}"
  when: checkpoints is undefined or checkpoint not in checkpoints

  rescue:
    - include_tasks: "{{ role_path_common }}/tasks/fail_playbook.yaml"
