#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Obtain docker_config_json from secret in kube-system
  command: kubectl get secret -n kube-system default-registry-key -o jsonpath='{.data.\.dockerconfigjson}'
  register: secret_docker_config_json
  environment:
    KUBECONFIG: "{{ kubeconfig }}"

- name: Render template for secret
  template:
    src: "{{ role_path_common }}/templates/secret-migration-registry-local.yaml.j2"
    dest: "{{ tmp_workspace }}/secret-migration-registry-local.yaml"
  vars:
    b64_docker_config_json: "{{ secret_docker_config_json.stdout }}"
  register: secret_file_created

- name: "Create secret for registry in namespace {{ cephfs_pvc_namespace }}"
  command: "kubectl apply -f {{ tmp_workspace }}/secret-migration-registry-local.yaml"
  register: apply_secret_result
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
