#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: "Force delete k8s resource {{ name | default(manifest_path) | default('--all') }}"
  shell: |
    {% set wait_delete = wait | default(true) %}

    kubectl delete \
    {% if k8s_namespace is defined %}
    -n {{ k8s_namespace }} \
    {% endif %}
    {% if manifest_path is defined %}
    -f {{ manifest_path }} \
    {% else %}
    {{ kind }} {{ name | default('--all') }} \
    {% endif %}
    --wait=false \
    --grace-period=0 \
    --force \
    --ignore-not-found=true

    {% if all is defined and all == true %}
      kubectl get \
      {% if k8s_namespace is defined %}
      -n {{ k8s_namespace }} \
      {% endif %}
      {{ kind }} -o name | \
      xargs -I % kubectl patch % \
      {% if k8s_namespace is defined %}
      -n {{ k8s_namespace }} \
      {% endif %}
      -p '{"metadata":{"finalizers":null}}' \
      --type=merge

      {% if wait_delete == true %}
        kubectl get \
        {% if k8s_namespace is defined %}
        -n {{ k8s_namespace }} \
        {% endif %}
        {{ kind }}
      {% endif %}

    {% else %}
      kubectl patch \
      {% if k8s_namespace is defined %}
      -n {{ k8s_namespace }} \
      {% endif %}
      {% if manifest_path is defined %}
      -f {{ manifest_path }} \
      {% else %}
      {{ kind }} {{ name }} \
      {% endif %}
      -p '{"metadata": {"finalizers": null}}' \
      --type=merge

      {% if wait_delete == true %}
        ! kubectl get \
        {% if k8s_namespace is defined %}
        -n {{ k8s_namespace }} \
        {% endif %}
        {% if manifest_path is defined %}
        -f {{ manifest_path }}
        {% else %}
        {{ kind }} {{ name }}
        {% endif %}
      {% endif %}
    {% endif %}

  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  register: force_delete_result
  retries: 10
  delay: 3
  until: >
    (force_delete_result.rc == 0 and all is undefined )
    or
    ("No resources found" in force_delete_result.stderr and
     all is defined and
     all | bool)
    or
    not wait | default(true) | bool
