#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Update SysInv host config
  include_tasks: update_host_config.yaml

- name: Update SysInv system config
  include_tasks: update_system_config.yaml
