#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Update puppet host config
  shell: sysinv-puppet create-host-config
  register: puppet_host_result

- name: Debug Puppet host
  debug:
    var: puppet_host_result.stdout_lines
