#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Update puppet system config
  shell: sysinv-puppet create-system-config
  register: puppet_update_result
  ignore_errors: true

- name: Debug Puppet system
  debug:
    var: puppet_update_result.stdout_lines
