#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Get list of mounted osd devices
  shell: mount | awk '/osd/ { print $3 }'
  register: mounted_devices
  changed_when: false

- name: Show all mounted OSDs
  debug:
    msg: "{{ mounted_devices.stdout_lines }}"

- name: Unmount OSD devices
  become: true
  mount:
    path: "{{ item }}"
    state: unmounted
  loop: "{{ mounted_devices.stdout_lines }}"
  register: umount_result
  ignore_errors: true

- name: Verify unmount task results
  fail:
    msg: "Failed to unmount '{{ item.item }}'. Error: {{ item.stderr | default('No stderr output provided.') }}"
  loop: "{{ umount_result.results }}"
  loop_control:
    label: "{{ item.item }}"
  failed_when:
    - item.failed is defined and item.failed == true
    - "'not mounted' not in (item.stderr | default('')) | lower"
    - "'no mount point specified' not in (item.stderr | default('')) | lower"
