#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Create secret for registry in namespace
  include_tasks: "{{ role_path_common }}/tasks/create_registry_secret.yaml"
  vars:
    namespace: "{{ cephfs_pvc_namespace }}"

- name: Patch PVCs/PVs with ReadOnlyMany access mode before import
  include_tasks: patch_readonly_access_modes.yaml

- name: Import cephfs backups
  block:
    - name: Import cephfs backups for namespace {{ cephfs_pvc_namespace }} in batches
      include_tasks: import_cephfs_backup_batch.yaml
      loop: "{{ cephfs_pvc_list | batch(pvc_batch_size | int) | list }}"
      loop_control:
        loop_var: batch_pvcs
  always:
    - name: Delete registry secret
      command: "kubectl delete -f {{ tmp_workspace }}/secret-migration-registry-local.yaml --ignore-not-found=true"
      environment:
        KUBECONFIG: "{{ kubeconfig }}"

- name: Restore PVCs/PVs to ReadOnlyMany access mode after import
  include_tasks: restore_readonly_access_modes.yaml
  when: readonly_pvcs is defined and readonly_pvcs | length > 0
