#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: "Create secret for registry in namespace {{ cephfs_pvc_namespace }}"
  include_tasks: "{{ role_path_common }}/tasks/create_registry_secret.yaml"
  vars:
    namespace: "{{ cephfs_pvc_namespace }}"

- name: Import cephfs backups
  block:
    - name: Import cephfs backups from namespace {{ cephfs_pvc_namespace }}
      include_tasks: import_cephfs_backup_single_pvc.yaml
      loop: "{{ cephfs_pvc_list }}"
      loop_control:
        loop_var: pvc
  always:
    - name: Delete registry secret
      command: "kubectl delete -f {{ tmp_workspace }}/secret-migration-registry-local.yaml"
      environment:
        KUBECONFIG: "{{ kubeconfig }}"
