#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Add monitors to hosts
  environment: "{{ system_env }}"
  command: system host-fs-add {{ item }} ceph=20
  loop: "{{ hosts_to_add_mon | default(groups.with_monitor) }}"
  register: add_mon_result
  failed_when: >
    add_mon_result.rc != 0 and
    ("already present" not in add_mon_result.stderr)
  changed_when: ("already present" not in add_mon_result.stderr)

- name: Debug monitor add result
  debug:
    msg: "{{ item.stdout_lines | replace('\\n', '\n') }}"
  loop: "{{ add_mon_result.results }}"
  loop_control:
    label: "{{ item.item }}"

- name: Wait all monitors (host-fs) to be Ready
  become: true
  become_user: postgres
  shell: >
    psql -d sysinv -t -A -c
    "SELECT COUNT(*) FROM host_fs WHERE name='ceph' AND state IN ('Ready', 'In-Use');"
  register: ceph_mons_ready
  retries: 60
  delay: 10
  until: ceph_mons_ready.stdout == expected_mons
  vars:
    expected_mons: "{{ hosts_to_add_mon | default(groups.with_monitor) | length }}"
  changed_when: false

- name: Add floating monitor for DX
  include_tasks: "{{ roles_dir_path }}/deploy-rook/tasks/add_floating_monitor.yaml"
  when:
    - system.system_deployment == "AIO-DX"
    - add_floating is defined
    - add_floating | bool
