#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Lock standby {{ groups.standby_controller | first }}
  environment: "{{ system_env }}"
  command: system host-lock {{ groups.standby_controller | first }}
  register: standby_controller_lock
  failed_when:
    - standby_controller_lock.rc != 0
    - ("already 'locked' host" not in standby_controller_lock.stderr)
  changed_when: ("already 'locked' host" not in standby_controller_lock.stderr)

- name: Debug standby_controller_lock
  debug:
    var: standby_controller_lock.stdout_lines

- name: Wait for {{ groups.standby_controller | first }} to be locked/disabled/online
  become: true
  become_user: postgres
  command: >
    psql -d sysinv -t -A -c
    "SELECT administrative || '|' || operational || '|' || availability
     FROM i_host
     WHERE hostname = '{{ groups.standby_controller | first | quote }}';"
  register: standby_controller_status
  until: standby_controller_status.stdout == 'locked|disabled|online'
  retries: 60
  delay: 10
  changed_when: false

- name: Give the standby host a few extra seconds
  pause:
    seconds: 20
  run_once: true
  delegate_to: "{{ system.active_controller }}"
  changed_when: false

- name: Create floating monitor
  environment: "{{ system_env }}"
  command: system controllerfs-add ceph-float=20
  register: floating_create
  failed_when: >
    floating_create.rc != 0 and
    ("already present" not in floating_create.stderr)
  changed_when: ("already present" not in floating_create.stderr)

- name: Debug floating_create
  debug:
    var: floating_create.stdout_lines
  when: floating_create.stdout_lines | length > 0

- name: Verify ceph-float controllerfs exists in sysinv DB
  become: true
  become_user: postgres
  shell: >
    psql -d sysinv -t -A -c
    "SELECT trim(both ''' }' from split_part(state, '''status'':', 2))
    FROM controller_fs WHERE name='ceph-float';"
  register: ceph_float_check
  until: ceph_float_check.stdout == "available"
  retries: 240
  delay: 10
  changed_when: false

- name: Unlock standby {{ groups.standby_controller | first }}
  environment: "{{ system_env }}"
  command: system host-unlock {{ groups.standby_controller | first }}
  register: standby_controller_unlock
  failed_when:
    - standby_controller_unlock.rc != 0
    - ("already 'unlocked' host" not in standby_controller_unlock.stderr)
  changed_when: ("already 'unlocked' host" not in standby_controller_unlock.stderr)

- name: Debug standby_controller_unlock
  debug:
    var: standby_controller_unlock.stdout_lines

- name: Wait for {{ groups.standby_controller | first }} to be unlocked/enabled/available
  become: true
  become_user: postgres
  command: >
    psql -d sysinv -t -A -c
    "SELECT administrative || '|' || operational || '|' || availability
     FROM i_host
     WHERE hostname = '{{ groups.standby_controller | first | quote }}';"
  register: standby_controller_status
  until: standby_controller_status.stdout == 'unlocked|enabled|available'
  retries: 120
  delay: 10
  changed_when: false
