#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Update storage-tiers fixing forbackendid
  become: true
  become_user: postgres
  command: >
    psql -d sysinv
    -c "UPDATE storage_tiers SET forbackendid=(select id from storage_backend where backend='ceph-rook') WHERE type='ceph' RETURNING id, uuid, type, name, status, forbackendid"
  register: update_tiers
  changed_when: update_tiers is defined
  failed_when: update_tiers is failed

- name: Summarize storage-tiers updates
  when: update_tiers is defined
  debug:
    var: update_tiers.stdout_lines
