---
#
# Copyright (c) 2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# ROLE DESCRIPTION:
#   This role is to disable IPSec on all hosts.
#

- name: Get system mode
  shell: source /etc/platform/platform.conf; echo $system_mode
  register: system_mode

- block:
  - name: Get PXEBoot network list addresses
    script: roles/common/files/get_pxeboot_addr_list.py
    register: ip_addrs_list

  - set_fact:
      pxeboot_addrs: "{{ ip_addrs_list.stdout }}"

  - name: Deprovision ipsec-config service
    command: >-
      ansible all -i "{{ item }}," -m command -a "sm-deprovision service-group-member
      controller-services ipsec-config --apply" -b -e "ansible_ssh_user={{ ansible_ssh_user }}
      ansible_ssh_pass={{ ansible_ssh_pass }} ansible_become_pass={{ ansible_become_pass }}"
    with_items:
      - controller-0
      - controller-1

  - name: Clean up IPsec services on hosts
    include_tasks: cleanup-services.yml
    loop: "{{ pxeboot_addrs }}"

  - name: Get MGMT network addresses list
    script: roles/configure-ipsec/files/get_all_mgmt_addrs.py
    register: all_hosts
    become_user: postgres

  - set_fact:
      all_hosts: "{{ all_hosts.stdout }}"

  # Wait a maximum time of 3 minutes until hosts are reachable via mgmt network
  - name: Wait until hosts are online and reachable
    shell: "ping -c 1 -w 5 {{ item }} | grep ' 0% packet loss'"
    register: host_is_reachable
    loop: "{{ all_hosts }}"
    until: host_is_reachable is not failed
    retries: 18
    delay: 10

  when: system_mode.stdout != "simplex"
