---
#
# Copyright (c) 2024-2025 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# SUB-TASKS DESCRIPTION:
#   This task sets admin network's secondary address pool uuid
#   Input provided:
#     admin_addrpool  - admin network's primary address pool uuid
#     software_version - host's software version

# set_fact for admin secondary addrpool uuid
# when subcloud software_version >= 24.09
- block:
  - name: Get admin network's primary address pool name
    shell: |
      {{ source_env_command }}
      system addrpool-list | awk '$2 == "{{ admin_addrpool }}" { print $4 }'
    register: admin_primary_pool_name

  - name: Get admin network name
    shell: |
      {{ source_env_command }}
      system network-list | awk '$8 == "admin" { print $6 }'
    register: admin_network_name

  - name: Get admin network secondary address pool name
    shell: >-
      {{ source_env_command }}
      system network-addrpool-list |
      awk '$4 == "{{ admin_network_name.stdout }}" && $6 != "{{
      admin_primary_pool_name.stdout }}" { print $6 }'
    register: admin_secondary_pool_name
    when: admin_network_name.stdout | length > 0

  - block:
    - name: Get admin network's secondary address pool uuid
      shell: >-
        {{ source_env_command }}
        system addrpool-list |
        awk '$4 == "{{ admin_secondary_pool_name.stdout }}" { print $2 }'
      register: admin_pool_uuid_secondary

    - name: Set admin_addrpool_secondary fact
      set_fact:
        admin_addrpool_secondary: "{{ admin_pool_uuid_secondary.stdout }}"
    when: admin_secondary_pool_name.stdout | length > 0
  when: software_version is version('24.09', '>=') and admin_addrpool | length > 0
