---
#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# This playbook is intended to be run on standalone systems.
#
# It provides the capability to migrate the storage backend used.
#
# To run the playbook, the user would define the required variable settings
# passing this on the ansible command-line as a parameter.
#
#
# Example command:
#  ANSIBLE_CONFIG='/usr/share/ansible/stx-ansible/playbooks/vars/storage-backend-migration/ansible.cfg' \
#  ansible-playbook /usr/share/ansible/stx-ansible/playbooks/storage-backend-migration-redeploy.yaml -v
#
# Optional extra variables:
#
# - osd_usage_safety_margin_percent: 0 <= int <= 100.
# - cgts_vg_min_required_free_gib: 1 <= int <= 100
# - minimum_platform_mem_workers: 1000 <= int <= 100000
# - storage_backend_migration_backup_dir: string
#

- import_playbook: storage-backend-migration-init.yaml
  vars:
    migration_type: redeploy
  when: execute_init | default(true)

- name: Execute pre-checks
  hosts: active_controller
  gather_facts: false
  become: true

  roles:
    - role: pre-checks
      when: execute_pre_check | default(true)

- import_playbook: storage-backend-migration-pre-migration.yaml
  when: execute_pre_migration | default(true)

- name: Execute pull-images
  hosts: active_controller
  gather_facts: false
  become: true

  roles:
    - role: pull-images
      tags: pull-images
      when: execute_pull_images | default(true)

- name: Turn off Ceph bare-metal on Nodes
  hosts: storages, workers, standby_controller, active_controller
  gather_facts: false
  become: true

  roles:
    - role: remove-baremetal

- name: Wipe disks on hosts with OSDs
  hosts: with_osds
  gather_facts: false
  become: true

  roles:
    - role: wipe-disks

- name: Restart sysinv
  hosts: storages, workers, standby_controller, active_controller
  serial: 1 # run fully on one host at a time
  gather_facts: false
  become: true

  pre_tasks:
    - name: Check host connection before proceed
      import_role:
        name: check_connection

  roles:
    - role: restart-sysinv

- name: Update Puppet
  hosts: active_controller
  gather_facts: false
  become: true

  roles:
    - role: update-puppet

- name: Reinstall Storage nodes as Workers
  hosts: active_controller
  gather_facts: false
  become: true

  roles:
    - role: reinstall-storage-nodes
      when: system.system_deployment == "STORAGE"

- name: Deploy Rook-Ceph app
  hosts: storages, workers, standby_controller, active_controller
  gather_facts: false
  become: true

  roles:
    - role: deploy-rook
      vars:
        hosts_to_add_mon: "{{ groups.with_monitor }}"
        hosts_to_fix_capabilities: "{{ groups.with_mon_and_osds }}"
        add_floating: true

- name: Check Rook-Ceph deploy
  hosts: active_controller
  gather_facts: false
  become: true

  roles:
    - role: deploy-rook-post-checks
    - role: add-rook-missing-resources
    - role: recreate-pvcs
      when: migration_type == "redeploy"

- import_playbook: storage-backend-migration-post-migration.yaml
  when: execute_post_migration | default(true)
