---
#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# This playbook is intended to be run on standalone systems.
#
# It provides the capability to migrate the storage backend used.
#
# To run the playbook, the user would define the required variable settings
# passing this on the ansible command-line as a parameter.
#
#
# Example command:
#  ANSIBLE_CONFIG='/usr/share/ansible/stx-ansible/playbooks/vars/storage-backend-migration/ansible.cfg' \
#  ansible-playbook /usr/share/ansible/stx-ansible/playbooks/storage-backend-migration-in-service.yaml -v
#
# Optional extra variables:
#
# - osd_usage_safety_margin_percent: 0 <= int <= 100.
# - cgts_vg_min_required_free_gib: 1 <= int <= 100
# - minimum_platform_mem_workers: 1000 <= int <= 100000
# - storage_backend_migration_backup_dir: string
# - backups_path: <path/to/backups> (for export-import migration type or in-service if using kube-rbdkube-system pool)
#

- import_playbook: storage-backend-migration-init.yaml
  vars:
    migration_type: in_service

- name: Execute pre-checks
  hosts: active_controller
  gather_facts: false
  become: true

  roles:
    - role: pre-checks

- import_playbook: storage-backend-migration-pre-migration.yaml

- name: Execute pull-images
  hosts: active_controller
  gather_facts: false
  become: true

  roles:
    - role: pull-images
      tags: pull-images

- name: Migrate 21.12 PVs
  hosts: active_controller
  gather_facts: false
  become: true

  roles:
    - role: recreate-old-pvs

    - role: manage-lv
      lv_action: create
      checkpoint_name: manage-lv-create
      when: create_migration_lv | default(false)

    - role: migrate-pool-with-backup
      original_pool: kube-rbdkube-system
      new_pool: kube-rbd
      when: old_pool_exist

    - role: manage-lv
      lv_action: remove
      checkpoint_name: manage-lv-remove
      when: create_migration_lv | default(false)

- name: Migrate OSDs from Filestore to Bluestore
  hosts: with_osds
  serial: 1 # run fully on one host at a time
  gather_facts: false
  become: true

  pre_tasks:
    - name: Check host connection before proceed
      import_role:
        name: check_connection

  roles:
    - role: filestore-to-bluestore

- name: Stop OSD systemctl processes
  hosts: with_osds
  gather_facts: false
  become: true

  roles:
    - role: stop-systemctl-osds

- name: Turn off Ceph bare-metal on Nodes
  hosts: storages, workers, standby_controller, active_controller
  gather_facts: false
  become: true

  roles:
    - role: remove-baremetal

- name: Restart sysinv
  hosts: storages, workers, standby_controller, active_controller
  serial: 1 # run fully on one host at a time
  gather_facts: false
  become: true

  pre_tasks:
    - name: Check host connection before proceed
      import_role:
        name: check_connection

  roles:
    - role: restart-sysinv

- name: Update Puppet
  hosts: active_controller
  gather_facts: false
  become: true

  roles:
    - role: update-puppet

- name: Perform Ceph Pacific migration
  hosts: storages, workers, standby_controller, active_controller
  gather_facts: false
  become: true

  roles:
    - role: nautilus-to-pacific

- name: Prepare Recover Pacific data
  # We need to run on active controller first
  hosts: active_controller, with_osds, host_with_mon_and_osd
  gather_facts: false
  become: true

  roles:
    - role: prepare-recover-data
      checkpoint_name: prepare-recover-data-pacific

- name: Import OSD keyrings for Pacific
  hosts: with_osds
  gather_facts: false
  become: true

  roles:
    - role: import-osd-keyrings
      checkpoint_name: import-osd-keyrings-pacific
      rook_base_host: "{{ rook_base_host_pacific }}"

- name: Get MON info from mon dump for Pacific
  hosts: active_controller
  gather_facts: false
  become: true

  roles:
    - role: get-monitor-info
      checkpoint_name: get-monitor-info-pacific

- name: Recover Pacific data
  hosts: host_with_mon_and_osd, with_osds
  gather_facts: false
  become: true

  roles:
    - role: recover-data
      checkpoint_name: recover-data-pacific
      ceph_image: "{{ images.ceph.pacific }}"
      hosts_to_recover_mon: "{{ hostvars[system.active_controller]['host_with_mon_and_osd'] }}"
      rook_base: "{{ rook_base_pacific }}"
      rook_base_pod: "{{ rook_base_pod_pacific }}"
      rook_base_host: "{{ rook_base_host_pacific }}"

- name: Prepare recovery for Ceph Reef and Deploy Rook-Ceph App
  hosts: active_controller
  gather_facts: false
  become: true

  roles:
    - role: restore-cephfs
      checkpoint_name: restore-cephfs-pacific
      require_osd_release: pacific

    - role: prepare-reef
      ceph_image: "{{ images.ceph.pacific }}" # to uninstall pacific
      rook_base: "{{ rook_base_pacific }}"

- name: Deploy Rook-Ceph app
  hosts: storages, workers, standby_controller, active_controller
  gather_facts: false
  become: true

  roles:
    - role: deploy-rook
      vars:
        migration_type: in_service
        hosts_to_add_mon: "{{ [hostvars[system.active_controller]['host_with_mon_and_osd']] }}"
        hosts_to_fix_capabilities: "{{ [hostvars[system.active_controller]['host_with_mon_and_osd']] }}"

- name: Wait for App to start to be applied, and OSD prepare jobs to be created and completed
  hosts: active_controller
  gather_facts: false
  become: true

  roles:
    - role: wait-rook

- name: Prepare Recover Reef data
  # We need to run on active controller first
  hosts: active_controller, with_osds, host_with_mon_and_osd
  gather_facts: false
  become: true

  roles:
    - role: prepare-recover-data
      checkpoint_name: prepare-recover-data-reef

- name: Import OSD keyrings for Reef
  hosts: with_osds
  gather_facts: false
  become: true

  roles:
    - role: import-osd-keyrings
      checkpoint_name: import-osd-keyrings-reef
      rook_base_host: "{{ rook_base_host_reef }}"

- name: Get MON info from mon dump for Reef
  hosts: active_controller
  gather_facts: false
  become: true

  roles:
    - role: get-monitor-info
      checkpoint_name: get-monitor-info-reef

- name: Recover Reef data
  hosts: host_with_mon_and_osd, with_osds
  gather_facts: false
  become: true

  roles:
    - role: recover-data
      checkpoint_name: recover-data-reef
      ceph_image: "{{ images.ceph.reef }}"
      hosts_to_recover_mon: "{{ hostvars[system.active_controller]['host_with_mon_and_osd'] }}"
      rook_base: "{{ rook_base_reef }}"
      rook_base_pod: "{{ rook_base_pod_reef }}"
      rook_base_host: "{{ rook_base_host_reef }}"

- name: Restore CephFs
  hosts: active_controller
  gather_facts: false
  become: true

  roles:
    - role: restore-cephfs
      checkpoint_name: restore-cephfs-reef
      bounce_rook_pods: true
      require_osd_release: reef

- name: Re-apply Rook-Ceph app with Ceph Reef
  hosts: active_controller
  gather_facts: false
  become: true

  roles:
    - role: re-apply-reef
      vars:
        hosts_to_add_mon: "{{ groups.with_monitor }}"
        hosts_to_fix_capabilities: "{{ groups.with_mon_and_osds }}"
        add_floating: true

- name: Finish the rook-ceph recovery
  hosts: active_controller
  gather_facts: false
  become: true

  roles:
    - role: deploy-rook-post-checks
    - role: add-rook-missing-resources
    - role: recreate-pvs
    - role: manage-snapshotter
      snap_action: disable
      checkpoint_name: manage-snapshotter-disable
    - role: recreate-snapshots
    - role: manage-snapshotter
      snap_action: enable
      checkpoint_name: manage-snapshotter-enable

- import_playbook: storage-backend-migration-post-migration.yaml
