---
#
# Copyright (c) 2021-2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# ROLE DESCRIPTION:
#   This role updates the network configuration for rehoming on subcloud
#

- name: Update admin subnet
  include_role:
    name: common/update-sc-admin-subnet
  when: admin_network is defined and
        (admin_floating_update_required or admin_gateway_update_required)

- name: Get previous system controller subnet address
  shell: >-
    source /etc/platform/openrc;
    system addrpool-list --nowrap | awk '/system-controller-subnet/{ print$6"/"$8 }'
  register: previous_system_controller_subnet_addr

- name: Resolve ipaddr filter differences (Bullseye)
  set_fact:
    prev_sc_subnet_network: >-
      {{ (previous_system_controller_subnet_addr.stdout | ipaddr(0)).split('/')[0] }}
    sc_subnet_network: >-
      {{ (system_controller_subnet | ipaddr(0)).split('/')[0] }}
    sc_subnet_prefix: >-
      {{ system_controller_subnet | ipaddr('prefix') }}
  when: is_bullseye

- name: Resolve ipaddr filter differences (Trixie)
  set_fact:
    prev_sc_subnet_network: >-
      {{ (previous_system_controller_subnet_addr.stdout | ansible.utils.ipaddr(0)).split('/')[0] }}
    sc_subnet_network: >-
      {{ (system_controller_subnet | ansible.utils.ipaddr(0)).split('/')[0] }}
    sc_subnet_prefix: >-
      {{ system_controller_subnet | ansible.utils.ipaddr('prefix') }}
  when: is_trixie

- block:
  - name: Get previous system controller host route uuid for controller-0
    shell: >-
      source /etc/platform/openrc; system host-route-list controller-0
      | grep {{ prev_sc_subnet_network }}
      | awk '{ print $2 }'
    register: previous_route_uuid_controller_0

  - name: Delete previous system controller network on controller-0
    shell: >-
      source /etc/platform/openrc;
      system host-route-delete "{{ item }}"
      {{ cli_confirmation | default('--yes') }}
    loop: "{{ previous_route_uuid_controller_0.stdout_lines }}"
    when: previous_route_uuid_controller_0.stdout_lines | length > 0
  when: system_controller_subnet != previous_system_controller_subnet_addr.stdout

- name: Check existing host route in controller-0
  # Checking if the static route to the new system controller subnet
  # is already configured. If it is already configured, e.g. recovery
  # from a disaster that the system controllers are reinstalled, the
  # static routes should not be added again.
  shell: >-
    source /etc/platform/openrc; system host-route-list controller-0 |
    awk '/{{ sc_subnet_network }}/'
  register: existing_route_controller_0

- name: Set subcloud gateway address
  set_fact:
    sc_gateway_address: "{{ network_params.admin_gateway_address_primary
                           if admin_network is defined
                           else network_params.management_gateway_address_primary }}"

- name: Set subcloud to systemcontroller route interface
  set_fact:
    sc_controller_0_route_interface:
      "{{ controller_0_admin_network_if.stdout_lines[0]
          if admin_network is defined
          else controller_0_management_interface_result.stdout_lines[0] }}"

- name: Add static route from controller-0 to system controller
  shell: >-
    source /etc/platform/openrc; system host-route-add controller-0
    {{ sc_controller_0_route_interface }}
    {{ sc_subnet_network }}
    {{ sc_subnet_prefix }}
    {{ sc_gateway_address }}
  when: existing_route_controller_0.stdout | length == 0

- block:

  - name: Get previous system controller subnet address
    shell: >-
      source /etc/platform/openrc;
      system addrpool-list --nowrap | awk '/system-controller-subnet/{ print$6"/"$8 }'
    register: previous_system_controller_subnet_addr

  - name: Resolve ipaddr filter differences for controller-1 (Bullseye)
    set_fact:
      prev_sc_subnet_network: >-
        {{ (previous_system_controller_subnet_addr.stdout | ipaddr(0)).split('/')[0] }}
    when: is_bullseye

  - name: Resolve ipaddr filter differences for controller-1 (Trixie)
    set_fact:
      prev_sc_subnet_network: >-
        {{ (previous_system_controller_subnet_addr.stdout | ansible.utils.ipaddr(0)).split('/')[0] }}
    when: is_trixie

  - block:
    - name: Get previous system controller host route uuid for controller-1
      shell: >-
        source /etc/platform/openrc; system host-route-list controller-1
        | grep {{ prev_sc_subnet_network }}
        | awk '{ print $2 }'
      register: previous_route_uuid_controller_1

    - name: Delete previous system controller network on controller-1
      shell: >-
        source /etc/platform/openrc;
        system host-route-delete "{{ item }}"
        {{ cli_confirmation | default('--yes') }}
      loop: "{{ previous_route_uuid_controller_1.stdout_lines }}"
      when: previous_route_uuid_controller_1.stdout_lines | length > 0
    when: system_controller_subnet != previous_system_controller_subnet_addr.stdout

  - name: Check existing host route in controller-1
    shell: >-
      source /etc/platform/openrc; system host-route-list controller-1 |
      awk '/{{ sc_subnet_network }}/'
    register: existing_route_controller_1

  - name: Set subcloud to systemcontroller route interface on controller-1
    set_fact:
      sc_controller_1_route_interface:
        "{{ controller_1_admin_network_if.stdout_lines[0]
            if admin_network is defined
            else controller_1_management_interface_result.stdout_lines[0] }}"

  - name: Add static route from controller-1 to system controller
    shell: >-
      source /etc/platform/openrc; system host-route-add controller-1
      {{ sc_controller_1_route_interface }}
      {{ sc_subnet_network }}
      {{ sc_subnet_prefix }}
      {{ sc_gateway_address }}
    when: existing_route_controller_1.stdout | length == 0

  when: system_mode != 'simplex'

- name: Update system controller's subnets
  import_tasks: update_system_controller_subnet.yml

- name: Check existing dns host record for registry central
  shell: >-
    source /etc/platform/openrc;
    system service-parameter-list | awk '/dns/ && /host-record/ && /registry.central/'
  register: existing_dns_registry_central

- name: Extract current dns host record for registry central
  set_fact:
    current_dns_record: "{{ existing_dns_registry_central.stdout |
      regex_search('registry.central,[^\\s|]+') }}"
  when: existing_dns_registry_central.stdout | length != 0

- name: Set central registry for subcloud
  set_fact:
    registry_central_address: >-
      {{ system_controller_floating_address
        if (virtual_system is defined and virtual_system|bool)
        else system_controller_oam_floating_address }}

- block:
    - name: Modify dns host record for registry central
      shell: >-
        source /etc/platform/openrc;
        system service-parameter-modify dns host-record
        registry.central=registry.central,{{ registry_central_address }}
      register: dns_record_output

    - name: Apply dns host record update
      shell: source /etc/platform/openrc; system service-parameter-apply dns

  when:
    - existing_dns_registry_central.stdout | length != 0
    - current_dns_record != ('registry.central,' ~ registry_central_address)

# update docker no_proxy without service parameters apply, the apply
# is triggered later by task "Update docker registry credentials"
- name: Modify docker no_proxy if exists
  shell: >-
    source /etc/platform/openrc; system service-parameter-modify
    docker proxy no_proxy={{ docker_no_proxy_combined | join(',') }}
  when: existing_docker_no_proxy_result.stdout | length > 0

- name: Copy central registy cert
  import_tasks: copy_central_registry_cert.yml
  become: yes
