---
#
# Copyright (c) 2021,2025 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# SUB-TASKS DESCRIPTION:
#   These tasks are to update system controller's subnets
#

- name: Get previous system controller OAM network uuid
  shell: >-
    source /etc/platform/openrc;
    system addrpool-list | awk '/system-controller-oam-subnet/{ print$2 }'
  register: system_controller_oam_subnet_uuid

- name: Delete previous system controller OAM subnet
  shell: >-
    source /etc/platform/openrc;
    system addrpool-delete
    {{ system_controller_oam_subnet_uuid.stdout }}
    {{ cli_confirmation | default('--yes') }}
  when: system_controller_oam_subnet_uuid.stdout | length > 0

- name: Add system controller OAM subnet
  shell: >-
    source /etc/platform/openrc; system addrpool-add system-controller-oam-subnet
    {{ (system_controller_oam_subnet | ipaddr(0)).split('/')[0]  }}
    {{ system_controller_oam_subnet | ipaddr('prefix') }}
    --floating-address {{ system_controller_oam_floating_address }} | awk '/uuid/{ print$4 }'
  register: add_system_controller_oam_subnet_uuid

- name: Read dnsmasq service pid
  command: cat /var/run/dnsmasq.pid
  register: current_pid

- name: Add new system-controller OAM network
  shell: >-
    source /etc/platform/openrc;
    system network-add system-controller-oam system-controller-oam false
    {{ add_system_controller_oam_subnet_uuid.stdout }}

- name: Ensure that dnsmasq is restarted before proceeding
  command: cat /var/run/dnsmasq.pid
  register: new_pid
  retries: 10
  delay: 5
  until: new_pid.stdout != current_pid.stdout

- name: Verify system-controller OAM network creation and availability
  shell: >
    source /etc/platform/openrc;
    system network-list | grep -q 'system-controller-oam'
  register: network_check
  until: network_check.rc == 0
  retries: 20
  delay: 5

- name: Get previous system controller network uuid
  shell: >-
    source /etc/platform/openrc;
    system addrpool-list | awk '/system-controller-subnet/{ print$2 }'
  register: system_controller_subnet_uuid
  until: not (system_controller_subnet_uuid.stderr | lower is search('error'))
  retries: 5
  delay: 10

- name: Delete previous system controller subnet
  shell: >-
    source /etc/platform/openrc;
    system addrpool-delete
    {{ system_controller_subnet_uuid.stdout }}
    {{ cli_confirmation | default('--yes') }}
  when: system_controller_subnet_uuid.stdout | length > 0

- name: Add system controller subnet
  shell: >-
    source /etc/platform/openrc;
    system addrpool-add system-controller-subnet
    {{ (system_controller_subnet | ipaddr(0)).split('/')[0]  }}
    {{ system_controller_subnet | ipaddr('prefix') }}
    --floating-address {{ system_controller_floating_address }} | awk '/uuid/{ print$4 }'
  register: add_system_controller_subnet_uuid

- name: Add new system-controller network
  shell: >-
    source /etc/platform/openrc;
    system network-add system-controller system-controller false
    {{ add_system_controller_subnet_uuid.stdout }}
