---
#
# Copyright (c) 2021,2025-2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# SUB-TASKS DESCRIPTION:
#   These tasks are to update system controller's subnets
#

- name: Resolve ipaddr filter differences for subnet updates (Bullseye)
  set_fact:
    sc_oam_subnet_network: >-
      {{ (system_controller_oam_subnet | ipaddr(0)).split('/')[0] }}
    sc_oam_subnet_prefix: >-
      {{ system_controller_oam_subnet | ipaddr('prefix') }}
    sc_mgmt_subnet_network: >-
      {{ (system_controller_subnet | ipaddr(0)).split('/')[0] }}
    sc_mgmt_subnet_prefix: >-
      {{ system_controller_subnet | ipaddr('prefix') }}
  when: is_bullseye

- name: Resolve ipaddr filter differences for subnet updates (Trixie)
  set_fact:
    sc_oam_subnet_network: >-
      {{ (system_controller_oam_subnet | ansible.utils.ipaddr(0)).split('/')[0] }}
    sc_oam_subnet_prefix: >-
      {{ system_controller_oam_subnet | ansible.utils.ipaddr('prefix') }}
    sc_mgmt_subnet_network: >-
      {{ (system_controller_subnet | ansible.utils.ipaddr(0)).split('/')[0] }}
    sc_mgmt_subnet_prefix: >-
      {{ system_controller_subnet | ansible.utils.ipaddr('prefix') }}
  when: is_trixie

- name: Get previous system controller OAM network uuid
  shell: >-
    source /etc/platform/openrc;
    system addrpool-list | awk '/system-controller-oam-subnet/{ print$2 }'
  register: system_controller_oam_subnet_uuid

- name: Delete previous system controller OAM subnet
  shell: >-
    source /etc/platform/openrc;
    system addrpool-delete
    {{ system_controller_oam_subnet_uuid.stdout }}
    {{ cli_confirmation | default('--yes') }}
  when: system_controller_oam_subnet_uuid.stdout | length > 0

- name: Add system controller OAM subnet
  shell: >-
    source /etc/platform/openrc; system addrpool-add system-controller-oam-subnet
    {{ sc_oam_subnet_network }}
    {{ sc_oam_subnet_prefix }}
    --floating-address {{ system_controller_oam_floating_address }} | awk '/uuid/{ print$4 }'
  register: add_system_controller_oam_subnet_uuid

- name: Add new system-controller OAM network
  shell: >-
    source /etc/platform/openrc;
    system network-add system-controller-oam system-controller-oam false
    {{ add_system_controller_oam_subnet_uuid.stdout }}

- name: Verify system-controller OAM network creation and availability
  shell: >
    source /etc/platform/openrc;
    system network-list | grep -q 'system-controller-oam'
  register: network_check
  until: network_check.rc == 0
  retries: 20
  delay: 5

- name: Get previous system controller network uuid
  shell: >-
    source /etc/platform/openrc;
    system addrpool-list | awk '/system-controller-subnet/{ print$2 }'
  register: system_controller_subnet_uuid
  until: not (system_controller_subnet_uuid.stderr | lower is search('error'))
  retries: 5
  delay: 10

- name: Delete previous system controller subnet
  shell: >-
    source /etc/platform/openrc;
    system addrpool-delete
    {{ system_controller_subnet_uuid.stdout }}
    {{ cli_confirmation | default('--yes') }}
  when: system_controller_subnet_uuid.stdout | length > 0

- name: Add system controller subnet
  shell: >-
    source /etc/platform/openrc;
    system addrpool-add system-controller-subnet
    {{ sc_mgmt_subnet_network }}
    {{ sc_mgmt_subnet_prefix }}
    --floating-address {{ system_controller_floating_address }} | awk '/uuid/{ print$4 }'
  register: add_system_controller_subnet_uuid

- name: Add new system-controller network
  shell: >-
    source /etc/platform/openrc;
    system network-add system-controller system-controller false
    {{ add_system_controller_subnet_uuid.stdout }}
