#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

script_files:
  - fix_rook_backend_network.py
  - fix_lvm_backend_network.py
  - remove_incomplete_secrets.py
  - remove_docker_registry_service_params.py
  - remove_lvm_replication_factor.py
