#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: "Ensure {{ tmp_workspace }} exist"
  file:
    path: "{{ tmp_workspace }}"
    state: directory

- name: Copy files to workspace
  copy:
    src: "{{ roles_dir_path }}/{{ role_name }}/files/{{ item }}"
    dest: "{{ tmp_workspace }}/{{ item }}"
    mode: "0755"
  loop: "{{ script_files }}"

- name: Generate system DM file
  include_tasks: get_system_dm_file.yaml

- name: Fix Rook storage backend network
  include_tasks: change_dm_file.yaml
  vars:
    target_dm_file_name: "rook-network-fixed.yaml"
    dm_script_name: "fix_rook_backend_network.py"
  when: migration_target == "rook_ceph"

# TBD: review this once the final DM implementation is ready
- name: Fix LVM storage backend network
  include_tasks: change_dm_file.yaml
  vars:
    target_dm_file_name: "lvm-network-fixed.yaml"
    dm_script_name: "fix_lvm_backend_network.py"
  when: migration_target == "lvm"

- name: Remove LVM replicationFactor
  include_tasks: change_dm_file.yaml
  vars:
    target_dm_file_name: "no-replicas.yaml"
    dm_script_name: "remove_lvm_replication_factor.py"
  when: migration_target == "lvm"

- name: Remove incomplete secrets in DM file
  include_tasks: change_dm_file.yaml
  vars:
    target_dm_file_name: "secrets-fixed.yaml"
    dm_script_name: "remove_incomplete_secrets.py"

- name: Remove docker registry references from service parameters in DM file
  include_tasks: change_dm_file.yaml
  vars:
    target_dm_file_name: "no-docker-registries.yaml"
    dm_script_name: "remove_docker_registry_service_params.py"

- name: Backup final DM file
  include_tasks: backup_dm_file.yaml

- name: Apply final DM file
  shell: "kubectl apply -f {{ final_dm_full_file_path }}"
  environment:
    KUBECONFIG: "{{ kubeconfig }}"

- name: Make DM update host stale defaults to reflect new DM file
  shell: |
    for host in $(kubectl -n deployment get host -o jsonpath='{.items[*].metadata.name}'); do
      kubectl -n deployment patch host ${host} --type=merge --subresource=status \
        -p='{"status":{"defaults":null,"observedGeneration":0}}'
    done
  environment:
    KUBECONFIG: "{{ kubeconfig }}"

- name: Cleanup temporary workspace folder
  file:
    path: "{{ tmp_workspace }}"
    state: absent
