#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: "Configure thin {{ lvm_thin_disk }} provisioning for {{ lvm_vg_name_cacheable }}"
  include_tasks: "{{ lvm_thin_disk }}/main.yaml"
