#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Set ceph_subvolume_sizes if undefined
  block:
  - name: List all Ceph subvolumes in the group
    command: >
      ceph fs subvolume ls "kube-cephfs" csi --format json
    register: subvolume_list_json
    changed_when: false
    check_mode: false

  - name: Extract subvolume names into a list
    set_fact:
      subvolume_names: "{{ (subvolume_list_json.stdout | from_json) | map(attribute='name') | list }}"

  - name: Get info for each subvolume
    command: >
      ceph fs subvolume info "kube-cephfs" {{ item }} csi --format json
    register: subvolume_info_results
    loop: "{{ subvolume_names }}"
    changed_when: false
    check_mode: false

  - name: Create a fact with all volume sizes
    set_fact:
      ceph_subvolume_sizes_result: "{{ dict(subvolume_info_results.results | map(attribute='item') |
                                     zip(subvolume_info_results.results |
                                         map(attribute='stdout') |
                                         map('from_json') |
                                         map(attribute='bytes_quota'))) }}"

  - name: Include 21.12 PVs in ceph_subvolume_sizes_result fact
    include_tasks: old_pvs_info.yaml

  - name: Create a consolidated fact with all volume sizes
    set_fact:
      ceph_subvolume_sizes: "{{ ceph_subvolume_sizes_result }}"
      cacheable: true

  when: ceph_subvolume_sizes is undefined

- name: Debug ceph_subvolume_sizes var
  debug:
    var: ceph_subvolume_sizes
