#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Scale down CSI volume-snapshot-controller
  run_once: true
  include_tasks: "{{ roles_dir_path }}/common/tasks/kubernetes/scale_resources.yaml"
  vars:
    resources:
      - method: "name"
        name: "volume-snapshot-controller"
        namespace: "kube-system"
        replicas: 0
        kind: StatefulSet

- name: Wait for volume-snapshot-controller to be deleted
  run_once: true
  include_tasks: "{{ roles_dir_path }}/common/tasks/kubernetes/wait_resources_condition.yaml"
  vars:
    k8s_namespace: "kube-system"
    k8s_resource_prefix: "volume-snapshot-controller"
    k8s_resource_type: "pod"
    wait_mode: "deleted"

- name: Disable snapshotter on CSI Driver CRs
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  command: >
    kubectl patch driver {{ item }} -n rook-ceph
    --type merge -p '{"spec":{"snapshotPolicy":"none"}}'
  loop:
    - rook-ceph.cephfs.csi.ceph.com
    - rook-ceph.rbd.csi.ceph.com

- name: Wait for CSI controller plugin rollouts
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  command: >
    kubectl rollout status deployment {{ item }} -n rook-ceph --timeout=120s
  loop:
    - rook-ceph.cephfs.csi.ceph.com-ctrlplugin
    - rook-ceph.rbd.csi.ceph.com-ctrlplugin
  retries: 6
  delay: 10
  register: rollout_result
  until: rollout_result.rc == 0

- name: Check snapshotter is removed from CSI CephFs provisioner
  shell: kubectl get deployment rook-ceph.cephfs.csi.ceph.com-ctrlplugin -n rook-ceph -o jsonpath='{.spec.template.spec.containers[*].name}' | grep -q snapshotter
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  register: snapshotter_check
  failed_when: snapshotter_check.rc == 0
