#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: "Check if PV {{ pv_name }} exists"
  shell: "kubectl get pv {{ pv_name }}"
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  register: pv_check
  failed_when: false
  changed_when: false

- name: "Save PV {{ pv_name }} to {{ tmp_workspace }}/{{ pv_name }}.yaml file"
  shell: "kubectl get pv {{ pv_name }} -o yaml > {{ tmp_workspace }}/{{ pv_name }}.yaml"
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  when: pv_check.rc == 0

- name: "Read PV {{ pv_name }} YAML file"
  slurp:
    src: "{{ tmp_workspace }}/{{ pv_name }}.yaml"
  register: pv_data_file

- name: "Parse the PV {{ pv_name }} YAML content"
  set_fact:
    pv_data: "{{ pv_data_file.content | b64decode | from_yaml }}"

- name: Set PV {{ pv_name }} type
  set_fact:
    pv_type: >-
      {{
        'cephfs' if 'subvolumeName' in (pv_data.spec.csi.volumeAttributes | default({}))
        else
        ('cephfs' if 'cephfs' in (pv_data.spec | default({})) else 'rbd')
      }}

- name: "Show PV {{ pv_name }} type"
  debug:
    msg: "The PV {{ pv_name }} type is {{ pv_type }}"

- block:
    - name: "Extract subvolumeName from the saved PV {{ pv_name }} file"
      set_fact:
        pv_subvolume_name: >-
          {%- set raw_name = (
            pv_data.spec.csi.volumeAttributes.subvolumeName | replace('csi-vol', 'pvc-volumes')
            if 'subvolumeName' in (pv_data.spec.csi.volumeAttributes | default({}))
            else (
              pv_data.metadata.annotations.cephShare | replace('csi-vol', 'kubernetes-dynamic-pvc')
              if 'cephfs' in (pv_data.spec | default({})) else ''
            )
          ) -%}
          {{ (subvolume_map | default({})).get(raw_name, raw_name) }}

    - name: "Show PV {{ pv_name }} subvolumeName"
      debug:
        msg: "The PV {{ pv_name }} subvolumeName is {{ pv_subvolume_name }}"

    - name: "Look up the size of the subvolume in ceph_subvolume_sizes"
      set_fact:
        pv_subvolume_size_bytes: "{{ hostvars[system.active_controller]['ceph_subvolume_sizes'][pv_subvolume_name] }}"

    - name: "Show the size of PV {{ pv_name }} in bytes"
      debug:
        msg: "The size of the PV '{{ pv_name }}' (subvolume '{{ pv_subvolume_name }}') is {{ pv_subvolume_size_bytes }} bytes."
  when: pv_type == 'cephfs'

- name: "Delete PV {{ pv_name }}"
  include_tasks: "{{ role_path_common }}/tasks/force_delete_k8s_resource.yaml"
  vars:
    kind: PersistentVolume
    name: "{{ pv_name }}"

- name: Render recreate_script.py using template
  template:
    src: recreate_script.py.j2
    dest: "{{ tmp_workspace }}/recreate_script.py"
    mode: 0644
  register: python_script_creation
  failed_when: python_script_creation.failed

- name: "Execute recreate PV script for {{ pv_name }}"
  command: "python {{ tmp_workspace }}/recreate_script.py"

- name: "Delete recreate PV script for {{ pv_name }}"
  command: "rm -rf {{ tmp_workspace }}/recreate_script.py"
  args:
    warn: false

- name: "Apply new PV {{ pv_name }} file"
  command: "kubectl apply -f {{ tmp_workspace }}/{{ pv_name }}.yaml"
  environment:
    KUBECONFIG: "{{ kubeconfig }}"

- name: "Recreate SubVolumes"
  include_tasks: recreate_subvolumes.yaml
  when:
  - pv_type == "cephfs"
  - migration_type == "export_import"

- name: "Delete new PV {{ pv_name }} file"
  command: "rm -rf {{ tmp_workspace }}/{{ pv_name }}.yaml"
  args:
    warn: false
