#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: "Ensure {{ tmp_workspace }} exist"
  file:
    path: "{{ tmp_workspace }}"
    state: directory

- name: "Get the list of all PersistentVolume names"
  command: "kubectl get pv -o jsonpath='{.items[*].metadata.name}'"
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  register: pv_list_result
  changed_when: false
  when: pv_list is not defined

- name: "Set pv_list fact"
  set_fact:
    pv_list: "{{ pv_list_result.stdout }}"
    cacheable: true
  when: pv_list is not defined

- name: "Get rbd pool id"
  shell: ceph osd lspools | awk '$2 == "kube-rbd" {print $1}'
  register: rbd_pool_id_result
  when: rbd_pool_id is not defined

- name: Set cephfilesystem ID fact
  set_fact:
    rbd_pool_id: "{{ rbd_pool_id_result }}"
    cacheable: true
  when: rbd_pool_id is not defined

- name: Get cephfilesystem ID
  shell: ceph fs get kube-cephfs --format json-pretty
  register: fs_map
  when: fscid is not defined

- name: Set cephfilesystem ID fact
  set_fact:
    fscid: "{{ fs_map.stdout | from_json | json_query('id') }}"
    cacheable: true
  when: fscid is not defined

- name: "Get RBD Holder Identity"
  command: "kubectl get leases -n rook-ceph rook-ceph-rbd-csi-ceph-com -o jsonpath='{.spec.holderIdentity}'"
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  register: rbd_holder_identity_result
  when: rbd_holder_identity is not defined

- name: "Handle RBD Holder Identity"
  set_fact:
    rbd_holder_identity: "{{ rbd_holder_identity_result.stdout.split('rook-ceph-')[0] + 'rook-ceph.' + rbd_holder_identity_result.stdout.split('rook-ceph-')[1].replace('-', '.') }}"
    cacheable: true
  when: rbd_holder_identity is not defined

- name: Debug RBD Holder Identity
  debug:
    var: rbd_holder_identity

- name: "Get CephFS Holder Identity"
  command: "kubectl get leases -n rook-ceph rook-ceph-cephfs-csi-ceph-com -o jsonpath='{.spec.holderIdentity}'"
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  register: cephfs_holder_identity_result
  when: cephfs_holder_identity is not defined

- name: "Handle CephFS Holder Identity"
  set_fact:
    cephfs_holder_identity: "{{ cephfs_holder_identity_result.stdout.split('rook-ceph-')[0] + 'rook-ceph.' + cephfs_holder_identity_result.stdout.split('rook-ceph-')[1].replace('-', '.') }}"
    cacheable: true
  when: cephfs_holder_identity is not defined

- name: Debug CephFS Holder Identity
  debug:
    var: cephfs_holder_identity

- name: "Include tasks to iterate over each PV"
  include_tasks: recreate_pvs.yaml
  loop: "{{ pv_list.split() }}"
  loop_control:
    loop_var: pv_name
  when: pv_list | length > 0

- name: Rename RBD images name
  include_tasks: "{{ role_path_common }}/tasks/rename_rbd_image.yaml"

# Clean only if all tasks was completed, to avoid errors when reexecuting.
- name: "Cleanup {{ tmp_workspace }}"
  file:
    path: "{{ tmp_workspace }}"
    state: absent
