---
#
# Copyright (c) 2022-2023, 2025 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# ROLE DESCRIPTION:
#   This role generates container images archive file(s).

- name: Archive container images (Debian)
  include_tasks: gen_images_archive_debian.yml
