#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: "Check if Volume Snapshot contents {{ snapshot_contents_name }} exists"
  shell: "kubectl get VolumeSnapshotContent {{ snapshot_contents_name }}"
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  register: snapshot_check
  failed_when: false
  changed_when: false

- name: "Save Volume Snapshot contents {{ snapshot_contents_name }} to {{ tmp_workspace }}/{{ snapshot_contents_name }}.yaml file"
  shell: "kubectl get VolumeSnapshotContent {{ snapshot_contents_name }} -o yaml > {{ tmp_workspace }}/{{ snapshot_contents_name }}.yaml"
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  when: snapshot_check.rc == 0

- name: "Read Volume Snapshot contents {{ snapshot_contents_name }} YAML file"
  slurp:
    src: "{{ tmp_workspace }}/{{ snapshot_contents_name }}.yaml"
  register: snapshot_contents_data_file

- name: "Parse the VSC {{ snapshot_contents_name }} YAML content"
  set_fact:
    snapshot_contents_data: "{{ snapshot_contents_data_file.content | b64decode | from_yaml }}"

- name: "Set contents {{ snapshot_contents_name }} type"
  set_fact:
    contents_type: >-
      {{
        'cephfs' if 'cephfs' in (snapshot_contents_data.spec.driver | default({}))
        else 'rbd'
      }}

- name: "Show VSC {{ snapshot_contents_name }} type"
  debug:
    msg: "The VSC {{ snapshot_contents_name }} type is {{ contents_type }}"

- name: "Delete VSC {{ snapshot_contents_name }}"
  include_tasks: "{{ role_path_common }}/tasks/force_delete_k8s_resource.yaml"
  vars:
    kind: VolumeSnapshotContent
    name: "{{ snapshot_contents_name }}"

- name: Render recreate_script.py using template
  template:
    src: recreate_script.py.j2
    dest: "{{ tmp_workspace }}/recreate_script.py"
    mode: 0644
  register: python_script_creation
  failed_when: python_script_creation.failed

- name: "Execute recreate VSC script for {{ snapshot_contents_name }}"
  command: "python {{ tmp_workspace }}/recreate_script.py"

- name: "Delete recreate VSC script for {{ snapshot_contents_name }}"
  command: "rm -rf {{ tmp_workspace }}/recreate_script.py"
  args:
    warn: false

- name: "Apply new VSC {{ snapshot_contents_name }} file"
  command: "kubectl apply -f {{ tmp_workspace }}/{{ snapshot_contents_name }}.yaml"
  environment:
    KUBECONFIG: "{{ kubeconfig }}"

- name: "Delete new VSC {{ snapshot_contents_name }} file"
  command: "rm -rf {{ tmp_workspace }}/{{ snapshot_contents_name }}.yaml"
  args:
    warn: false
