#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Create and configure Ceph extra pools
  shell: |
    ceph osd pool create {{ item.name }} {{ item.pg_num }} {{ item.pgp_num }} replicated {{ item.crush_rule_name }} || true

    ceph osd pool set {{ item.name }} size {{ item.size }}
    ceph osd pool set {{ item.name }} min_size {{ item.min_size }}

    ceph osd pool application enable {{ item.name }} {{ item.application }}

    {% if item.pg_autoscale_bias is defined %}
    ceph osd pool set {{ item.name }} pg_autoscale_bias {{ item.pg_autoscale_bias }}
    {% endif %}

    {% if item.pg_num_min is defined %}
    ceph osd pool set {{ item.name }} pg_num_min {{ item.pg_num_min }}
    {% endif %}

    {% if item.recovery_priority is defined %}
    ceph osd pool set {{ item.name }} recovery_priority {{ item.recovery_priority }}
    {% endif %}

  loop: "{{ extra_pools_list }}"
  loop_control:
    label: "{{ item.name }}"
  register: pool_create_result
  changed_when: pool_create_result.rc == 0
  become: true
