#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Check if ceph-wipe-disks service account exists
  command: kubectl get serviceaccounts ceph-wipe-disks -n rook-ceph
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  register: wipe_disk_service_account_result
  failed_when: false
  changed_when: false

- name: Set fact if service account exists
  set_fact:
    wipe_disk_service_account_exists: "{{ wipe_disk_service_account_result.rc == 0 }}"

- name: Apply ceph-wipe-disks service account
  command: kubectl apply -f {{ tmp_workspace }}/ceph_wipe_disks_service_account.yaml
  environment:
    KUBECONFIG: "{{ kubeconfig }}"

  when: not wipe_disk_service_account_exists | bool
