#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Check if full-dm-file.yaml already exists
  stat:
    path: "{{ tmp_workspace }}/full-dm-file.yaml"
  register: full_file
  changed_when: false

- name: Generate full-dm-file.yaml only if it does NOT exist yet
  block:
    - name: Get system name
      command: kubectl -n deployment get system -o jsonpath='{.items[].metadata.name}'
      environment:
        KUBECONFIG: "{{ kubeconfig }}"
      register: dm_system_name_tmp
      changed_when: false

    - name: Get full DM file
      environment: "{{ system_env }}"
      command: deployctl build --minimal-config -s {{ dm_system_name_tmp.stdout | trim }} -o {{ tmp_workspace }}/full-dm-file.yaml
      register: deployctl_output
      failed_when: false # it returns not zero if generates file with warnings

    - name: Debug deployctl_output
      debug:
        var: deployctl_output.stdout_lines
  when: not full_file.stat.exists

- name: Check if full-dm-file.yaml was created
  stat:
    path: "{{ tmp_workspace }}/full-dm-file.yaml"
  register: full_dm_file
  changed_when: false

- name: Fail if full DM file was not generated
  fail:
    msg: "full-dm-file.yaml not generated by deployctl"
  when: not full_dm_file.stat.exists

- name: Check if storage-only.yaml already exists
  stat:
    path: "{{ tmp_workspace }}/storage-only.yaml"
  register: storage_only_file
  changed_when: false

- name: Generate storage-only.yaml only if it does NOT exist yet
  block:
    - name: Strip down the DM file to only contain storage information
      shell: "{{ tmp_workspace }}/strip_to_storage_only.py {{ tmp_workspace }}/full-dm-file.yaml | tee {{ tmp_workspace }}/storage-only.yaml"
      register: storage_dm_file_output

    - name: Debug storage_dm_file_output
      debug:
        var: storage_dm_file_output.stdout_lines
  when: not storage_only_file.stat.exists

- name: Check if storage-no-osds.yaml already exists
  stat:
    path: "{{ tmp_workspace }}/storage-no-osds.yaml"
  register: storage_no_osds_file
  changed_when: false

- name: Generate storage-no-osds.yaml only if it does NOT exist yet
  block:
    - name: Strip down the DM file to only contain storage information
      shell: "{{ tmp_workspace }}/remove_osds.py {{ tmp_workspace }}/storage-only.yaml | tee {{ tmp_workspace }}/storage-no-osds.yaml"
      register: storage_dm_file_output

    - name: Debug storage_dm_file_output
      debug:
        var: storage_dm_file_output.stdout_lines
  when: not storage_no_osds_file.stat.exists

- name: Check if storage-labels.yaml already exists
  stat:
    path: "{{ tmp_workspace }}/storage-labels.yaml"
  register: storage_labels_file
  changed_when: false

- name: Generate storage-labels.yaml only if it does NOT exist yet
  block:
    - name: Strip down the DM file to only contain storage information
      shell: "{{ tmp_workspace }}/add_kube_labels.py {{ tmp_workspace }}/storage-no-osds.yaml | tee {{ tmp_workspace }}/storage-labels.yaml"
      register: storage_dm_file_output

    - name: Debug storage_dm_file_output
      debug:
        var: storage_dm_file_output.stdout_lines
  when: not storage_labels_file.stat.exists

- name: Check if storage-to-worker.yaml already exists
  stat:
    path: "{{ tmp_workspace }}/storage-to-worker.yaml"
  register: storage_to_worker_file
  changed_when: false

- name: Generate storage-to-worker.yaml only if it does NOT exist yet
  block:
    - name: Change personality and subfunction to worker
      shell: "{{ tmp_workspace }}/convert_storage_to_worker.py {{ tmp_workspace }}/storage-labels.yaml | tee {{ tmp_workspace }}/storage-to-worker.yaml"
      register: storage_to_worker_dm_file_output

    - name: Debug storage_to_worker_dm_file_output
      debug:
        var: storage_to_worker_dm_file_output.stdout_lines
  when: not storage_to_worker_file.stat.exists

# Always generate this one
- name: Set CPU and memory to new storage profile
  shell: >-
    {{ tmp_workspace }}/set_worker_cpu_memory.py --node0-mib {{ min_storage_memory_mib }} --node0-cpus {{ min_storage_cpus }}
    {% if storages_have_numa_1 | bool %}--add-node1{% endif %}
    {{ tmp_workspace }}/storage-to-worker.yaml | tee {{ tmp_workspace }}/storage-to-worker-cpu-memory.yaml
  register: cpu_memory_dm_file_output

- name: Debug cpu_memory_dm_file_output
  debug:
    var: cpu_memory_dm_file_output.stdout_lines
