#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Build storage hardware facts (cores + memory)
  block:
    - name: Get core count on processor 0 for storages
      become: true
      become_user: postgres
      # Count only physical cores
      command: >
        psql -d sysinv -t -A -c "
        SELECT count(DISTINCT core) AS physical_cores_per_socket
        FROM i_icpu
        WHERE forihostid = (SELECT id FROM i_host WHERE hostname = '{{ item }}')
        AND thread=0
        GROUP BY forinodeid LIMIT 1;"
      register: storage_p_0_core_count
      loop: "{{ groups.storages }}"
      loop_control:
        label: "{{ item }}"
      changed_when: false

    - name: Get total memory in MiB on processor 0 for storages
      become: true
      become_user: postgres
      # Later we will set node_memtotal_mib = memtotal_mib
      command: >
        psql -d sysinv -t -A -c "
        SELECT memtotal_mib
        FROM i_imemory
        WHERE forihostid = (SELECT id FROM i_host WHERE hostname='{{ item }}')
        ORDER BY forinodeid
        LIMIT 1;"
      register: storage_p_0_total_memory
      loop: "{{ groups.storages }}"
      loop_control:
        label: "{{ item }}"
      changed_when: false

    - name: Create storage_hardware_tmp variable
      set_fact:
        storage_hardware_tmp: >-
          {{
            storage_hardware_tmp | default({})
            | combine({
              item.item: {
                'cpu_cores': item.stdout | trim | int,
                'total_memory_mib': storage_p_0_total_memory.results[loop_index].stdout | trim | int
              }
            })
          }}
      loop: "{{ storage_p_0_core_count.results }}"
      loop_control:
        label: "{{ item.item }}"
        index_var: loop_index

    - name: Create storage_hardware variable
      set_fact:
        storage_hardware: "{{ storage_hardware_tmp }}"
        cacheable: true

  when: storage_hardware is undefined

- name: Check for NUMA 1 existance on storage nodes
  block:
    - name: Check for NUMA 1 on memory show
      environment: "{{ system_env }}"
      command: system host-memory-show {{ groups.storages | first }} 1
      register: numa_1_check
      failed_when: false
      changed_when: false

    - name: Set NUMA 1 existance or absence
      set_fact:
        storages_have_numa_1: "{{ numa_1_check.rc == 0 }}"
        cacheable: true
  when: storages_have_numa_1 is undefined

- name: Display storages_have_numa_1
  debug:
    var: storages_have_numa_1

- name: Show final result
  debug:
    var: storage_hardware

- name: Compute minimum values for CPU and memory
  set_fact:
    min_storage_cpus: "{{ [storage_hardware.values() | map(attribute='cpu_cores') | min | int - 1, 1] | max }}" # either all cpus - 1 or at least 1
    min_storage_memory_mib: "{{ [(storage_hardware.values() | map(attribute='total_memory_mib') | min | int) * 2 // 3, minimum_platform_mem_workers | int] | max }}" # either 2/3 of the memory or at least minimum_platform_mem_workers
    cacheable: true

- name: Debug min_storage_cpus
  debug:
    var: min_storage_cpus

- name: Debug min_storage_memory_mib
  debug:
    var: min_storage_memory_mib
