---
#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# ROLE DESCRIPTION:
#   These tasks do the preparation for etcd staged versions.
#

- block:
  - name: Set etcd local directory
    set_fact:
      etcd_local_dir: "/usr/local/etcd"
      etcd_symlink_dir: "/var/lib/etcd"

  # Create etcd "stage0" symlinks under /var/lib/etcd.
  - name: Link etcd stage0 directory
    ansible.builtin.file:
      src: "{{ etcd_local_dir }}/{{ etcd_version }}/{{ item }}"
      dest: "{{ etcd_symlink_dir }}/{{ item }}"
      state: link
    with_items:
      - "stage0"

  when: etcd_version is defined
