#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Scale up all mons
  include_tasks: "{{ role_path_common }}/tasks/kubernetes/scale_resources.yaml"
  vars:
    resources:
      - method: "label"
        label: "app=rook-ceph-mon"
        namespace: "rook-ceph"
        replicas: 1
        kind: Deployment

- name: Verify that all rook-ceph mon pods are Running
  shell: |
    kubectl get pods -n rook-ceph \
      -o jsonpath='{range .items[*]}{.metadata.name}{" "}{.status.phase}{"\n"}{end}' \
    | grep -E '^rook-ceph-mon-[a-z]+' \
    | awk '{if ($2 != "Running") {print $0; exit 1}}'
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  register: ceph_pods_check
  retries: 60
  delay: 10
  until: ceph_pods_check.rc == 0

- name: Wait until all MONs to be in quorum
  shell: timeout 30 ceph mon stat
  register: ceph_mon_stat
  retries: 60
  delay: 10
  until: ceph_mon_stat.rc == 0 and "out of quorum" not in ceph_mon_stat.stdout

- name: Ceph MON stat result
  debug:
    var: ceph_mon_stat.stdout_lines

- name: Parse ceph mon dump into mon_list
  shell: >-
    ceph mon dump | grep 'mon\.' | awk '
      BEGIN { printf "[" }
      { if ($0 ~ /dumped monmap epoch/) next
        rank = $1; sub(/:$/, "", rank);
        ip=$2; name=$3; sub(/^mon\./, "", name)
        if (NR>1) printf ","
        printf "{\"rank\":%s,\"name\":\"%s\",\"ip\":\"%s\"}", rank, name, ip
      }
      END { printf "]\n" }
    '
  register: mon_json
  changed_when: false

- name: Set mon_info fact
  set_fact:
    mon_info: "{{ mon_json.stdout | from_json }}"

- name: Get mon to node mapping
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  shell: >
    kubectl -n rook-ceph get pods
    -l app=rook-ceph-mon
    -o jsonpath='{range .items[*]}{.metadata.labels.mon}{" "}{.spec.nodeName}{"\n"}{end}'
  register: mon_node_map
  changed_when: false

- name: Build mon_node_dict
  set_fact:
    mon_node_dict: "{{ mon_node_dict | default({}) | combine({ item.split()[0]: item.split()[1] }) }}"
  loop: "{{ mon_node_map.stdout_lines }}"
  when: item | length > 0

- name: Build mon_list dict keyed by host (without host field)
  set_fact:
    mon_list: >-
      {{
        mon_list | default({}) |
        combine({
          (mon_node_dict[item.name] | default('unknown')): {
            'rank': item.rank | int,
            'name': item.name,
            'ip': item.ip
          }
        })
      }}
    cacheable: true
  loop: "{{ mon_info }}"
  loop_control:
    loop_var: item

- name: Debug mon list
  debug:
    var: mon_list
