---
#
# Copyright (c) 2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# SUB-TASKS DESCRIPTION:
#   These tasks are to copy the central registry's cert to subcloud
#

- name: Create docker certificate directory for central
  file:
    path: "{{ docker_cert_dir }}/registry.central:9001"
    state: directory
    recurse: yes
    mode: 0700

- name: Create the shared filesystem directory for central
  file:
    path: "{{ config_permdir }}/registry.central"
    state: directory
    recurse: yes
    mode: 0700

- name: Copy the central cloud registry certificate from central cloud to subcloud
  copy:
    src: "{{ docker_cert_dir }}/registry.local:9001/registry-cert.crt"
    dest: "{{ docker_cert_dir }}/registry.central:9001/registry-cert.crt"
    mode: preserve

- name: Store the central certificate to the shared filesystem
  copy:
    src: "{{ docker_cert_dir }}/registry.central:9001/registry-cert.crt"
    dest: "{{ config_permdir }}/registry.central/registry-cert.crt"
    remote_src: yes
    mode: preserve
