---
# Copyright (c) 2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
#   This role is to update the sysinv configurations during subcloud enrollment.
#

- name: Set default values for variables
  set_fact:
    last_system_config_file: "{{ config_permdir }}/{{ system_config_file }}"

- block:
  - name: Add section [USER_DNS_HOST_RECORDS]
    set_fact:
      sysinv_user_dns_host_records: "[USER_DNS_HOST_RECORDS]\n"

  - name: Populate user dns host records section
    set_fact:
      sysinv_user_dns_host_records: "{{ sysinv_user_dns_host_records }}{{ item }}={{ user_dns_host_records[item] }}\n"
    loop: "{{ user_dns_host_records.keys() }}"

  when: user_dns_host_records

- block:
  - name: Lock controller-0 for network update
    include_role:
      name: common/host-lock
    vars:
      target_host: 'controller-0'

  - name: Generate config file for python sysinv db population script
    template:
      src: system_config.j2
      dest: "/tmp/{{ system_config_file }}"

  - name: Set input parameters to populate config script
    set_fact:
      script_input: "/tmp/{{ system_config_file }}"

  - name: Update system configurations
    script: update_system_config.py {{ script_input }}
    register: update_result
    failed_when: false

  - debug: var=update_result

  - name: Fail if update config script throws an exception
    fail:
      msg: |
        Failed to update system configuration.
        Waiting for the system to unlock before retry.
    when: update_result.rc != 0

  rescue:
  - name: Unlock controller-0
    include_role:
      name: common/host-unlock
    vars:
      target_host: 'controller-0'

- name: Copy central registy cert
  import_tasks: copy_central_registry_cert.yml
  become: yes
