#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Remove Ceph configured flag
  command: rm -vf /etc/platform/.node_ceph_configured
  register: node_ceph_configured_output
  args:
    warn: false

- name: Display file removed
  debug:
    var: node_ceph_configured_output.stdout_lines
  when: node_ceph_configured_output.stdout_lines | length > 0

- name: Unmount ceph mon and data if mounted
  command: umount -v /var/lib/ceph/mon /var/lib/ceph/data
  register: umount_result
  failed_when: false
  ignore_errors: true

- name: Verify unmount task results
  fail:
    msg: "Failed to unmount. Error: {{ umount_result.stderr | default('No stderr output provided.') }}"
  when:
    - umount_result is defined and umount_result.rc != 0
    - "'not mounted' not in (umount_result.stderr | default('')) | lower"
    - "'no mount point specified' not in (umount_result.stderr | default('')) | lower"

- name: Detach and down drbd-cephmon
  shell: |
    drbdadm detach drbd-cephmon
    drbdadm down drbd-cephmon
    rm -rvf /etc/drbd.d/drbd-cephmon.res
  register: drbd_detach_down_result
  ignore_errors: true

- name: Debug detach
  debug:
    var: drbd_detach_down_result.stdout_lines
  when: drbd_detach_down_result.stdout_lines | length > 0

- name: Remove ceph-mon-lv ceph-lv and logical volumes
  shell: |
    # Separate commands
    # Otherwise lvremove stops after failing the first one
    lvremove -v -y /dev/cgts-vg/ceph-mon-lv
    lvremove -v -y /dev/cgts-vg/ceph-lv
  register: lvremove_result
  failed_when: false
  ignore_errors: true

- name: Fail if lvremoves failed
  fail:
    msg: |
      Failed to run lvremove.
      Return code: {{ lvremove_result.rc }}
      Stdout: {{ lvremove_result.stdout | default('') }}
      Stderr: {{ lvremove_result.stderr | default('') }}
  when:
    - lvremove_result.rc != 0
    - "'failed to find logical volume' not in (lvremove_result.stdout | lower)"
    - "'failed to find logical volume' not in (lvremove_result.stderr | lower)"

- name: Remove ceph-mon-lv and ceph-lv mounts from /etc/fstab
  shell: |
    sed -i -E '/ceph-mon-lv|ceph-lv|drbd9/d' /etc/fstab
  failed_when: false
  ignore_errors: true
  args:
    warn: false
