- name: Delete CephFs Snapshots
  block:
    - name: Delete CephFs VS
      include_tasks: "{{ role_path_common }}/tasks/force_delete_k8s_resource.yaml"
      vars:
        kind: VolumeSnapshot
        namespace: "-A"
        name: "{{ item }}"
      loop: "{{ cephfs_vs }}"
      when: cephfs_vs | length > 0

    - name: Delete CephFs VSC
      include_tasks: "{{ role_path_common }}/tasks/force_delete_k8s_resource.yaml"
      vars:
        kind: VolumeSnapshotContents
        namespace: "-A"
        name: "{{ item }}"
      loop: "{{ cephfs_vsc }}"
      when: cephfs_vsc | length > 0
  when: migration_type == "redeploy"

- name: Delete RBD VS
  include_tasks: "{{ role_path_common }}/tasks/force_delete_k8s_resource.yaml"
  vars:
    kind: VolumeSnapshot
    namespace: "-A"
    name: "{{ item }}"
  loop: "{{ rbd_vs }}"
  when: rbd_vs | length > 0

- name: Delete RBD VSC
  include_tasks: "{{ role_path_common }}/tasks/force_delete_k8s_resource.yaml"
  vars:
    kind: VolumeSnapshotContents
    namespace: "-A"
    name: "{{ item }}"
  loop: "{{ rbd_vsc }}"
  when: rbd_vsc | length > 0
