#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Delete all entries from ceph_mon table
  become: true
  become_user: postgres
  command: psql -d sysinv -c "delete from ceph_mon;"
  register: delete_ceph_mon

- name: Delete all entries from host_fs table
  become: true
  become_user: postgres
  command: psql -d sysinv -c "delete from host_fs where name='ceph';"
  register: delete_host_fs

- name: Delete capabilities in host table
  become: true
  become_user: postgres
  command: >
    psql -d sysinv -c "
    UPDATE i_host
    SET capabilities = (capabilities::jsonb - 'stor_function')::text;"
