#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Update disk list in the DB
  become: true
  become_user: postgres
  command: >
    psql -d sysinv -t -A -c "UPDATE i_idisk SET foristorid = NULL
    WHERE forihostid=(SELECT id FROM i_host WHERE hostname='{{ item }}');"
  loop: "{{ groups.storages }}"
  loop_control:
    label: "{{ item }}"

- name: Delete OSDs in the DB
  become: true
  become_user: postgres
  command: >
    psql -d sysinv -t -A -c "DELETE FROM i_istor;"

- name: Add storage OSDs from database info
  environment: "{{ system_env }}"
  command: >-
    system host-stor-add {{ item.0.key }} {{ item.1.disk_uuid }} --tier-uuid {{ item.1.tier_uuid }}
  loop: "{{ disks_by_host_db | dict2items | subelements('value') }}"
  loop_control:
    label: "{{ item.0.key }} - disk uuid ({{ item.1.disk_uuid }}) - tier uuid ({{ item.1.tier_uuid }})"
  vars:
    disks_by_host_db: "{{ hostvars[system.active_controller]['disks_by_host'] }}"
