#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Ensure /etc/platform/.node_rook_configured exists
  file:
    path: /etc/platform/.node_rook_configured
    state: touch
    modification_time: preserve
    access_time: preserve
    owner: root
    group: root
    mode: '0644'

- block:
    - name: Change OSD id to NULL in the DB
      become: true
      become_user: postgres
      command: >
        psql -d sysinv -t -A
        -c "UPDATE i_istor SET osdid=NULL WHERE state='configured' RETURNING id;"
      register: change_osd_id_to_null
      changed_when: change_osd_id_to_null.stdout_lines | length > 0

    - name: Debug changed OSDs
      debug:
        var: change_osd_id_to_null.stdout_lines

    - name: Add monitors
      include_tasks: add_monitors.yaml
  when: inventory_hostname in groups.active_controller

# We must do it after monitor add
- name: Add OSDs for STORAGE deployment
  include_tasks: add_storage_node_osds.yaml
  when:
    - inventory_hostname in groups.active_controller
    - system.system_deployment == "STORAGE"

- block:
    - name: Change capabilities for hosts with OSDs and monitors
      include_tasks: change_capabilities.yaml

    - name: Wait host_fs monitors to go to Ready
      become: true
      become_user: postgres
      # In-Use means host-fs is already Ready.
      command: >
        psql -d sysinv -t -A
        -c "SELECT forihostid FROM host_fs WHERE state NOT IN ('Ready', 'In-Use') AND name='ceph';"
      register: wait_host_fs_ready
      until: wait_host_fs_ready.stdout_lines | length == 0
      retries: 60
      delay: 10
      changed_when: false

    - name: Update cluster fixing name, type and deployment_model
      include_tasks: change_cluster.yaml

    - name: Update storage-tiers fixing forbackendid
      include_tasks: change_tiers.yaml

    - name: Apply Rook-Ceph application
      environment: "{{ system_env }}"
      command: system application-apply rook-ceph
      register: app_apply_result
      failed_when:
        - app_apply_result.rc != 0
        - ("applying" not in app_apply_result.stderr)
        - ("in progress" not in app_apply_result.stderr)
  when: inventory_hostname in groups.active_controller
