---
#
# Copyright (c) 2025-2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# SUB-TASKS DESCRIPTION:

- name: Restore each software deployment group
  include_tasks: begin_one_deployment.yml
  loop: "{{ sw_deployments_info.deployments_to_restore }}"
  loop_control:
    loop_var: current_deployment
    label: "{{ current_deployment.sw_version }}"
