---
#
# Copyright (c) 2025 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# SUB-TASKS DESCRIPTION:

- name: Restore software deployments data
  command: >
    tar --use-compress-program=pigz
    -C /
    {%+ for v in sw_deployments_info.tar_transforms + extra_tar_transforms %}
    --transform {{ v | quote }}
    {%+ endfor %}
    {%+ for v in sw_deployments_info.tar_excludes + extra_tar_excludes %}
    --exclude {{ v | quote }}
    {%+ endfor %}
    -xpvf {{ restore_data_file | quote }}
    {{ ' '.join(sw_deployments_restore_items | map('quote')) }}
  args:
    warn: false

- name: Strip previously deployed patch contents from metadata
  script: "strip_patch_contents.py {{ current_path | quote }}"
  loop_control:
    label: "{{ current_path }}"
  loop: "{{ sw_deployments_info.metadata.deployed[1:] }}"
  vars:
    current_path: "{{ ('/', item.replace('deployed', 'available')) | path_join }}"
