#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Check RBD snap images
  shell: rbd ls {{ item.name }} | grep "rbd-snap"
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  register: rbd_snap_images_output
  loop: "{{ all_pools_list | selectattr('application', 'equalto', 'rbd') | list }}"
  loop_control:
    label: "{{ item.name }}"
  failed_when: false

- name: Fail if there are snaphots for RBD
  fail:
    msg: |-
      RBD snapshots are not allowed for export-import migration type!
      This is because references to the RBD snapshots are lost after the migration.
      To erase your RBD snapshots during the migration, please add the extra variable
      '-e erase_rbd_snapshots=true'.
      If using the 'erase_rbd_snapshots=true' the data from PVCs created from snapshots
      will be preserved, just the snapshots themselves will be deleted.
      There is no rollback for the snapshots when using '-e erase_rbd_snapshots=true'
      the snapshots will be deleted permanently.

      Also check RBD snap images using 'rbd ls' on the RBD pools.

      VolumeSnapshotsContents: {{ rbd_vsc }}
      VolumeSnapshots: {{ rbd_vs }}
  when: >
    not erase_rbd_snapshots_cache | bool and
    (rbd_vs | length > 0 or
    rbd_vsc | length > 0 or
    rbd_snap_images_output.results | selectattr('rc', 'equalto', 0) | list | length > 0)

- name: Check space for backups
  include_tasks: "{{ role_path_common }}/tasks/check_space_for_backups.yaml"
