#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: "Ensure {{ tmp_workspace }} exist"
  file:
    path: "{{ tmp_workspace }}"
    state: directory

- name: Export system variables
  include_tasks: "{{ roles_dir_path }}/init-system/tasks/system_env.yaml"

- name: Debug system_env var
  debug:
    var: system_env

- block:
    - name: Get list of images to download
      set_fact:
        images_to_download: >-
          {{
            images_to_download | default([]) +
            (current_values | default([])) |
            list
          }}
      loop: "{{ images | dict2items | map(attribute='value') | list }}"
      vars:
        current_values: >-
          {%- if item is mapping -%}
            {{ item.values() | list }}
          {%- else -%}
            [{{ item | to_json }}]
          {%- endif -%}

    - name: Show list of images to download
      debug:
        var: images_to_download

    - name: Render scripts to pull, tag, and push images to Local Registry ({{ local_registry }})
      template:
        src: "download_images.py.j2"
        dest: "{{ tmp_workspace }}/download_images.py"

    - name: Pull, tag, and push images to Local Registry ({{ local_registry }})
      command: "python {{ tmp_workspace }}/download_images.py"
      register: download_images_result
      failed_when: false

    - name: Show download images output
      debug:
        var: download_images_result.stdout_lines

    - name: Fail if there were a error processing some image
      fail:
        msg: Some images were not downloaded
      when: download_images_result.rc != 0

  always:
    - name: "Cleanup {{ tmp_workspace }} after failure"
      file:
        path: "{{ tmp_workspace }}"
        state: absent

- name: "Cleanup {{ tmp_workspace }}"
  file:
    path: "{{ tmp_workspace }}"
    state: absent
