#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: "Ensure {{ tmp_workspace }} exist"
  file:
    path: "{{ tmp_workspace }}"
    state: directory

- name: Export system variables
  include_tasks: "{{ roles_dir_path }}/init-system/tasks/system_env.yaml"

- name: Debug system_env var
  debug:
    var: system_env

- name: Set images to use based on migration target
  set_fact:
    images_to_use: "{{ images_rook_ceph if migration_target == 'rook_ceph' else images_lvm }}"

- block:
    - name: Get list of images to download
      set_fact:
        images_to_download: "{{ images_to_download | default([]) + current_values }}"
      loop: "{{ images_to_use | dict2items | map(attribute='value') | list }}"
      vars:
        current_values: "{{ item.values() | list if item is mapping else [item] }}"

    - name: Show list of images to download
      debug:
        var: images_to_download

    - name: Render scripts to pull, tag, and push images to Local Registry ({{ local_registry }})
      template:
        src: "download_images.py.j2"
        dest: "{{ tmp_workspace }}/download_images.py"

    - name: Pull, tag, and push images to Local Registry ({{ local_registry }})
      command: "python {{ tmp_workspace }}/download_images.py"
      async: 3600
      poll: 0
      register: download_images_job

    - name: Wait for image pull to finish
      async_status:
        jid: "{{ download_images_job.ansible_job_id }}"
      register: download_images_result
      until: download_images_result.finished | default(false)
      retries: 60
      delay: 60
      failed_when: false

    - name: Show download images result
      debug:
        var: download_images_result

    - name: Fail if there were a error processing some image
      fail:
        msg: Some images were not downloaded
      when: download_images_result.rc is not defined or download_images_result.rc != 0

  always:
    - name: Show download images output log
      command: "cat {{ tmp_workspace }}/download_images.log"
      register: download_images_log
      failed_when: false

    - name: Display download images output
      debug:
        var: download_images_log.stdout_lines
      when: download_images_log.stdout_lines | default([]) | length > 0

    - name: "Cleanup {{ tmp_workspace }} after failure"
      file:
        path: "{{ tmp_workspace }}"
        state: absent

- name: "Cleanup {{ tmp_workspace }}"
  file:
    path: "{{ tmp_workspace }}"
    state: absent
