#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: "Ensure {{ tmp_workspace }} exist"
  file:
    path: "{{ tmp_workspace }}"
    state: directory

- name: Migrate pools
  block:
    - name: Create backup folders
      include_tasks: create_backups_folders.yaml

    - name: Migrate RBD pool
      include_tasks: migrate_rbd_pool.yaml

    - name: "Get all PVs that uses pool {{ original_pool }}"
      command: kubectl get pv -o jsonpath='{range .items[?(@.spec.csi.volumeAttributes.pool=="{{ original_pool }}")]}{.metadata.name}{"\n"}{end}'
      environment:
        KUBECONFIG: "{{ kubeconfig }}"
      register: pool_pv_list_result
      when: pool_pv_list is undefined

    - name: Set PV list by pool
      set_fact:
        pool_pv_list: "{{ pool_pv_list_result.stdout_lines }}"
        cacheable: true
      when: pool_pv_list is undefined

    - name: Show list of PV that uses pool {{ original_pool }}
      debug:
        var: pool_pv_list

    - name: "Recreate PVs to point to pool {{ new_pool }}"
      include_tasks: recreate_pvs.yaml
      loop: "{{ pool_pv_list }}"
      loop_control:
        loop_var: pv_name
      when: pool_pv_list | length > 0

  always:
    - name: "Cleanup {{ tmp_workspace }}"
      file:
        path: "{{ tmp_workspace }}"
        state: absent
