#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Check if default-registry-key secret exists
  command: kubectl get secret default-registry-key -n rook-ceph
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  register: rook_ceph_registry_secret
  failed_when: false
  changed_when: false

- name: Set fact if secret exists
  set_fact:
    rook_ceph_registry_secret: "{{ rook_ceph_registry_secret.rc == 0 }}"

- block:
  - name: Get registry token for images
    command: kubectl get secret default-registry-key -n kube-system -o=jsonpath='{.data.\.dockerconfigjson}'
    environment:
      KUBECONFIG: "{{ kubeconfig }}"
    register: token

  - name: Render rook-ceph manifests to remote
    template:
      src: "{{ role_path_common }}/templates/default-registry-key.yaml.j2"
      dest: "{{ tmp_workspace }}/default-registry-key.yaml"
    vars:
      registry_token: "{{ token.stdout }}"

  - name: Apply default-registry-key secret
    command: kubectl apply -f {{ tmp_workspace }}/default-registry-key.yaml
    environment:
      KUBECONFIG: "{{ kubeconfig }}"

  when: not rook_ceph_registry_secret
