#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Check if rook-ceph-mon secret exists
  command: kubectl get secret rook-ceph-mon -n rook-ceph
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  register: rook_ceph_mon_secret
  failed_when: false
  changed_when: false

- name: Set fact if secret exists
  set_fact:
    rook_ceph_mon_secret_exists: "{{ rook_ceph_mon_secret.rc == 0 }}"

- block:
  - name: Generate CephX key for mon/ceph secret
    command: ceph-authtool --gen-print-key
    register: cephx_key

  - name: Render rook-ceph-mon secret template
    template:
      src: "{{ roles_dir_path }}/nautilus-to-pacific/templates/rook_ceph_secret.yaml.j2"
      dest: "{{ tmp_workspace }}/rook-ceph-secret.yaml"
    vars:
      cephx_secret: "{{ cephx_key.stdout }}"
      fsid: "{{ hostvars[system.active_controller]['ceph_fsid'] }}"

  - name: Apply rook-ceph secret manifest
    command: kubectl apply -f {{ tmp_workspace }}/rook-ceph-secret.yaml
    environment:
      KUBECONFIG: "{{ kubeconfig }}"

  when: not rook_ceph_mon_secret_exists
