#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Get rook-ceph-tool pod name
  shell: kubectl get pods -n rook-ceph | awk '/rook-ceph-tool/ {print $1}'
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  register: tool_pod
  changed_when: false

- name: Rename RBD images
  shell: |
    kubectl -n rook-ceph exec deployments/rook-ceph-tools -- bash -c '
      set -e -o pipefail

      OLD_PREFIX="kubernetes-dynamic-pvc"
      NEW_PREFIX="csi-vol"

      SNAPSHOT_OLD_PREFIX="rbd-snap"
      SNAPSHOT_NEW_PREFIX="csi-snap"

      for obj_name in $(rbd ls {{ item.name }}); do
        if [ "$obj_name" == "$OLD_PREFIX"* ]; then
          obj_name_normalized=${obj_name/#$OLD_PREFIX/$NEW_PREFIX}
          echo "Renaming {{ item.name }}/${obj_name} to {{ item.name }}/${obj_name_normalized}"
          rbd rename "{{ item.name }}/${obj_name}" "{{ item.name }}/${obj_name_normalized}"
        elif [[ "$obj_name" == "$SNAPSHOT_OLD_PREFIX"* ]]; then
          obj_name_normalized=${obj_name/#$SNAPSHOT_OLD_PREFIX/$SNAPSHOT_NEW_PREFIX}
          echo "Renaming {{ item.name }}/${obj_name} to {{ item.name }}/${obj_name_normalized}"
          rbd rename "{{ item.name }}/${obj_name}" "{{ item.name }}/${obj_name_normalized}"

          snapshot_names=$(rbd snap ls "{{ item.name }}/$obj_name_normalized" | awk "NR>1 {print \$2}")

          for snapshot_name in $snapshot_names; do
            full_snap_name="{{ item.name }}/$obj_name_normalized@$snapshot_name"
            snap_name_normalized=${full_snap_name/$SNAPSHOT_OLD_PREFIX/$SNAPSHOT_NEW_PREFIX}
            echo "Renaming snap $full_snap_name to $snap_name_normalized"
            rbd snap rename "$full_snap_name" "$snap_name_normalized"
          done
        else
          echo "Ignoring the renaming to {{ item.name }}/${obj_name}"
        fi
      done
    '
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  register: rename_result
  loop: "{{ all_pools_list | selectattr('application', 'equalto', 'rbd') | list }}"

- name: Show rename result
  debug:
    var: rename_result.stdout
