#!/usr/bin/env python3
#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# This script validates that the OAM IP address from the backup network
# configuration (ifupdown format in /etc/network/interfaces.d/) is not
# already assigned to a wrong interface on the system.
#
# The ifcfg-* files are generated by puppet and follow the Debian
# ifupdown/ifupdown-extra format. Each file contains a stx-description
# line with metadata like "stx-description ifname:oam0,net:oam".
#
# Supported interface configurations:
#   1. Direct physical interface (e.g. ifcfg-enp0s3:3-8 with net:oam)
#   2. VLAN over bond (e.g. ifcfg-vlan409:3-9 -> vlan-raw-device pxeboot0
#      -> bond-slaves enp97s0f0 enp160s0f0)
#   3. VLAN over physical (e.g. ifcfg-vlan41:1-3 -> vlan-raw-device enp25s0f0)
#
# VLAN resolution:
#   VLAN interfaces in Linux can have arbitrary names. This script resolves
#   VLANs by their VLAN ID + parent device using 'ip -d -j link show type vlan'
#   rather than relying on the interface name matching "vlanXXX".
#
# Logic:
#   1. Find the ifcfg-* file containing "net:oam" in its stx-description.
#   2. Extract the OAM IP address(es) from that file.
#   3. Resolve the expected interface chain:
#      - If it's a VLAN: extract VLAN ID and parent device, then find the
#        actual system interface name for that VLAN (by ID+parent).
#      - If parent is a bond: resolve bond-slaves to physical NICs.
#      - Recurse until reaching physical interfaces.
#   4. Check the current system interfaces:
#      - If the OAM IP is not configured anywhere -> PASS (True)
#      - If the OAM IP is on one of the acceptable interfaces -> PASS (True)
#      - If the OAM IP is on a different interface -> FAIL (False)
#
# Exit code 0 and prints "True" on success.
# Exit code 0 and prints "False" on failure (with details logged to stderr).
#

import argparse
import json
import os
import re
import subprocess
import sys


VERBOSE = False


def log_info(msg):
    if VERBOSE:
        print("INFO: {}".format(msg), file=sys.stderr)


def log_warning(msg):
    print("WARNING: {}".format(msg), file=sys.stderr)


def log_error(msg):
    print("ERROR: {}".format(msg), file=sys.stderr)


def get_ifcfg_files(interfaces_dir):
    """Return a list of ifcfg-* file paths in the interfaces directory."""
    if not os.path.isdir(interfaces_dir):
        return []
    return [
        os.path.join(interfaces_dir, f)
        for f in sorted(os.listdir(interfaces_dir))
        if f.startswith("ifcfg-")
    ]


def read_file_lines(filepath):
    """Read a file and return its lines."""
    try:
        with open(filepath, "r") as fh:
            return fh.readlines()
    except (IOError, OSError):
        return []


def find_net_type_file(ifcfg_files, net_type):
    """
    Find the ifcfg file that contains the given net type marker
    in its stx-description line.
    e.g. net_type="oam" matches "stx-description ifname:oam0,net:oam"
    """
    pattern = "net:{}".format(net_type)
    for filepath in ifcfg_files:
        lines = read_file_lines(filepath)
        for line in lines:
            if pattern in line:
                return filepath
    return None


def get_iface_name_from_stanza(filepath):
    """
    Extract the interface name from the 'iface' stanza line.
    e.g. "iface vlan409:3-9 inet6 static" -> "vlan409"
    e.g. "iface enp0s3:3-8 inet static" -> "enp0s3"
    The part after ':' is a sub-interface label and must be ignored.
    """
    lines = read_file_lines(filepath)
    for line in lines:
        match = re.match(r"^\s*iface\s+(\S+)", line)
        if match:
            iface_full = match.group(1)
            # Remove sub-interface label (everything after first ':')
            if ":" in iface_full:
                iface_full = iface_full.split(":")[0]
            return iface_full
    # Fallback: derive from filename
    return get_interface_name_from_filename(filepath)


def get_interface_name_from_filename(filepath):
    """
    Extract the interface name from the ifcfg filename.
    e.g. /etc/network/interfaces.d/ifcfg-vlan409:3-9 -> vlan409
    """
    basename = os.path.basename(filepath)
    iface_name = basename.replace("ifcfg-", "", 1)
    if ":" in iface_name:
        iface_name = iface_name.split(":")[0]
    return iface_name


def get_addresses_from_file(filepath):
    """
    Extract IP addresses from an ifcfg file (ifupdown format).
    Handles both IPv4 and IPv6 addresses with or without prefix/netmask.
    """
    addresses = []
    lines = read_file_lines(filepath)
    for line in lines:
        stripped = line.strip()
        match = re.match(r"^\s*address\s+(\S+)", stripped)
        if match:
            addr = match.group(1)
            # Remove prefix length if present (CIDR notation)
            if "/" in addr:
                addr = addr.split("/")[0]
            addresses.append(addr)
    return addresses


def get_vlan_raw_device(filepath):
    """
    Extract the vlan-raw-device from an ifcfg file.
    Returns the parent interface name or None.
    """
    lines = read_file_lines(filepath)
    for line in lines:
        match = re.match(r"^\s*vlan-raw-device\s+(\S+)", line.strip())
        if match:
            return match.group(1)
    return None


def get_vlan_id_from_file(filepath):
    """
    Extract the VLAN ID from an ifcfg file.
    Tries multiple methods:
      1. From the interface name (e.g. vlan409 -> 409)
      2. From pre-up command (e.g. "ip link add ... type vlan id 409")
    Returns the VLAN ID as integer or None.
    """
    iface_name = get_iface_name_from_stanza(filepath)

    # Method 1: interface name like "vlan409" or "vlan41"
    match = re.match(r"^vlan(\d+)$", iface_name)
    if match:
        return int(match.group(1))

    # Method 2: look for "type vlan id XXX" in pre-up commands
    lines = read_file_lines(filepath)
    for line in lines:
        match = re.search(r"type\s+vlan\s+id\s+(\d+)", line)
        if match:
            return int(match.group(1))

    return None


def get_bond_slaves(filepath):
    """
    Extract bond-slaves from an ifcfg file.
    Returns a list of slave interface names or empty list.
    """
    lines = read_file_lines(filepath)
    for line in lines:
        match = re.match(r"^\s*bond-slaves\s+(.*)", line.strip())
        if match:
            return match.group(1).split()
    return []


def find_ifcfg_for_interface(iface_name, ifcfg_files):
    """
    Find the ifcfg file for a given interface name.
    Matches against the base interface name (without sub-interface label).
    """
    for filepath in ifcfg_files:
        base_name = get_interface_name_from_filename(filepath)
        if base_name == iface_name:
            return filepath
    return None


def get_system_vlans():
    """
    Get all VLAN interfaces on the system using 'ip -d -j link show type vlan'.
    Returns a list of dicts with keys:
      - ifname: actual interface name on the system
      - vlan_id: VLAN ID
      - parent: parent device name (link)
    """
    vlans = []
    try:
        result = subprocess.run(
            ["ip", "-d", "-j", "link", "show", "type", "vlan"],
            capture_output=True, text=True, timeout=10
        )
        if result.returncode != 0:
            return vlans

        data = json.loads(result.stdout)
        for entry in data:
            ifname = entry.get("ifname", "")
            link = entry.get("link", "")
            linkinfo = entry.get("linkinfo", {})
            info_data = linkinfo.get("info_data", {})
            vlan_id = info_data.get("id")
            if vlan_id is not None:
                vlans.append({
                    "ifname": ifname,
                    "vlan_id": int(vlan_id),
                    "parent": link,
                })
    except (subprocess.TimeoutExpired, OSError, ValueError, KeyError):
        pass

    return vlans


def find_system_vlan_iface(vlan_id, parent_device, system_vlans):
    """
    Find the actual system interface name for a VLAN given its
    VLAN ID and parent device.
    Returns the interface name or None if not found.
    """
    for vlan in system_vlans:
        if vlan["vlan_id"] == vlan_id and vlan["parent"] == parent_device:
            return vlan["ifname"]
    return None


def resolve_physical_interfaces(iface_name, ifcfg_files):
    """
    Resolve the physical interfaces for a given interface name by
    following vlan-raw-device and bond-slaves references.

    Returns:
      - physical_ifaces: set of physical interface names
      - all_related: set of all interfaces in the chain (including
        intermediate bonds, VLANs, etc.)
    """
    physical_ifaces = set()
    all_related = set()
    visited = set()
    to_resolve = [iface_name]

    while to_resolve:
        current = to_resolve.pop()
        if current in visited:
            continue
        visited.add(current)
        all_related.add(current)

        ifcfg_file = find_ifcfg_for_interface(current, ifcfg_files)
        if ifcfg_file is None:
            # No ifcfg file found - assume it's a physical interface
            physical_ifaces.add(current)
            continue

        # Check if it's a VLAN (has vlan-raw-device)
        vlan_parent = get_vlan_raw_device(ifcfg_file)
        if vlan_parent:
            all_related.add(current)
            to_resolve.append(vlan_parent)
            continue

        # Check if it's a bond (has bond-slaves)
        slaves = get_bond_slaves(ifcfg_file)
        if slaves:
            all_related.add(current)
            for slave in slaves:
                to_resolve.append(slave)
            continue

        # Neither VLAN nor bond - it's a physical or simple interface
        physical_ifaces.add(current)

    return physical_ifaces, all_related


def get_system_ip_assignments():
    """
    Get current IP address assignments on the system.
    Returns a dict: {ip_address: [interface_names]}
    """
    ip_map = {}
    try:
        result = subprocess.run(
            ["ip", "-o", "addr", "show"],
            capture_output=True, text=True, timeout=10
        )
        if result.returncode != 0:
            return ip_map

        for line in result.stdout.splitlines():
            parts = line.split()
            if len(parts) < 4:
                continue
            iface = parts[1].rstrip(":")
            # Remove @parent notation (e.g. vlan409@pxeboot0)
            if "@" in iface:
                iface = iface.split("@")[0]
            addr_with_prefix = parts[3]
            addr = addr_with_prefix.split("/")[0]
            if addr not in ip_map:
                ip_map[addr] = []
            ip_map[addr].append(iface)
    except (subprocess.TimeoutExpired, OSError):
        pass

    return ip_map


def main():
    parser = argparse.ArgumentParser(
        description="Validate OAM IP address is not assigned to a wrong "
                    "interface on the system."
    )
    parser.add_argument(
        "interfaces_dir",
        nargs="?",
        default="/etc/network/interfaces.d",
        help="Path to the directory containing ifcfg-* files "
             "(default: /etc/network/interfaces.d)"
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        default=False,
        help="Enable verbose INFO messages (default: disabled)"
    )
    args = parser.parse_args()
    interfaces_dir = args.interfaces_dir

    global VERBOSE
    VERBOSE = args.verbose

    ifcfg_files = get_ifcfg_files(interfaces_dir)

    if not ifcfg_files:
        log_warning(
            "No ifcfg files found in {}".format(interfaces_dir)
        )
        print("True")
        return

    # Step 1: Find the OAM ifcfg file (the one with "net:oam")
    oam_file = find_net_type_file(ifcfg_files, "oam")
    if oam_file is None:
        log_warning(
            "No ifcfg file with 'net:oam' marker found in {}".format(
                interfaces_dir)
        )
        print("True")
        return

    # Step 2: Get OAM interface name and IP addresses
    oam_iface = get_iface_name_from_stanza(oam_file)
    oam_addresses = get_addresses_from_file(oam_file)

    if not oam_addresses:
        log_warning(
            "No IP addresses found in OAM config file {}".format(oam_file)
        )
        print("True")
        return

    # Step 3: Resolve the expected physical interfaces
    expected_physical, all_related = resolve_physical_interfaces(
        oam_iface, ifcfg_files
    )

    # Step 4: Resolve VLAN by ID+parent on the live system
    # If the OAM interface is a VLAN, find its actual system name
    system_vlans = get_system_vlans()
    acceptable_ifaces = set(all_related)

    vlan_id = get_vlan_id_from_file(oam_file)
    vlan_parent = get_vlan_raw_device(oam_file)

    if vlan_id is not None and vlan_parent is not None:
        # The OAM is on a VLAN - find the actual system interface
        # for this VLAN ID + parent combination
        system_vlan_name = find_system_vlan_iface(
            vlan_id, vlan_parent, system_vlans
        )
        if system_vlan_name:
            acceptable_ifaces.add(system_vlan_name)
            log_info(
                "VLAN {} on parent '{}' exists on system as "
                "interface '{}'".format(
                    vlan_id, vlan_parent, system_vlan_name)
            )
        else:
            # The VLAN might not exist yet (will be created by ifup).
            # Also check if another VLAN with the same VLAN ID exists
            # on the system over an interface that resolves to the
            # same physical topology.

            # Resolve the expected physical interfaces behind the
            # configured VLAN parent.
            parent_physical, _ = resolve_physical_interfaces(
                vlan_parent, ifcfg_files
            )

            # Check all system VLANs with matching VLAN ID.
            for sv in system_vlans:
                if sv["vlan_id"] != vlan_id:
                    continue

                # Resolve the physical interfaces behind the
                # live system VLAN parent.
                system_parent_physical, _ = (
                    resolve_physical_interfaces(
                        sv["parent"], ifcfg_files
                    )
                )

                # Accept the VLAN if both parents resolve to the
                # same physical interfaces, even if the intermediate
                # interface/bond names differ.
                if (
                    parent_physical and
                    system_parent_physical and
                    parent_physical ==
                    system_parent_physical
                ):
                    acceptable_ifaces.add(sv["ifname"])

                    log_info(
                        "VLAN {} found on system as '{}' "
                        "(parent '{}', same physical topology)".format(
                            vlan_id,
                            sv["ifname"],
                            sv["parent"]
                        )
                    )

    log_info(
        "OAM interface '{}' from file '{}', "
        "OAM addresses: {}, "
        "resolved physical interfaces: {}, "
        "acceptable interfaces: {}".format(
            oam_iface,
            os.path.basename(oam_file),
            oam_addresses,
            sorted(expected_physical),
            sorted(acceptable_ifaces)
        )
    )

    # Step 5: Check current system IP assignments
    system_ip_map = get_system_ip_assignments()

    for oam_addr in oam_addresses:
        if oam_addr in system_ip_map:
            assigned_ifaces = system_ip_map[oam_addr]
            for assigned_iface in assigned_ifaces:
                if assigned_iface not in acceptable_ifaces:
                    # Build a helpful message about where the IP should be
                    if vlan_id is not None and vlan_parent is not None:
                        expected_msg = (
                            "OAM IP should be added to VLAN {} "
                            "(interface '{}') over interface: "
                            "{}".format(
                                vlan_id,
                                oam_iface,
                                " or ".join(sorted(expected_physical))
                            )
                        )
                    else:
                        expected_msg = (
                            "OAM IP should be added to "
                            "interface: {}".format(
                                " or ".join(sorted(expected_physical))
                            )
                        )

                    log_error(
                        "OAM IP address '{}' is currently assigned to "
                        "interface '{}', but based on the backup network "
                        "configuration: {}. "
                        "This may cause a conflict when bringing up "
                        "OAM networking during restore.".format(
                            oam_addr,
                            assigned_iface,
                            expected_msg
                        )
                    )
                    print("False")
                    return
            # IP is on an acceptable interface - that's fine
            log_info(
                "OAM IP '{}' is already assigned to acceptable "
                "interface(s): {}".format(
                    oam_addr, ", ".join(assigned_ifaces))
            )
        else:
            log_info(
                "OAM IP '{}' is not currently assigned to any "
                "interface (will be configured by ifup)".format(oam_addr)
            )

    # All checks passed
    print("True")


if __name__ == "__main__":
    main()
