---
kube_config_dir: /etc/kubernetes/admin.conf

skip_os_dbs:
  - 'Database'
  - 'information_schema'
  - 'performance_schema'
  - 'mysql'
  - 'horizon'
  - 'panko'
  - 'gnocchi'

mariadb_pod: mariadb-server-0

backup_user_images: false

# List of apps whose images will be included in the backup
backup_include_apps: []

# List of apps on DC system controller whose images will be included in the backup
backup_include_dc_controller_apps: ["platform-integ-apps", "rook-ceph"]

homedir: "{{ '/home' if os_release == 'centos' else '/var/home' }}"
config_permdir: "{{ platform_path }}/config/{{ software_version }}"
deploy_permdir: "{{ platform_path }}/deploy/{{ software_version }}"
extension_permdir: "/opt/extension"
extra_permdir: "{{ platform_path }}/extra"
fernet_keys_permdir: "{{ platform_path }}/keystone/fernet-keys"
fluxcd_permdir: "{{ platform_path }}/fluxcd/{{ software_version }}"
helm_overrides_permdir: "{{ platform_path }}/helm/{{ software_version }}"
helm_charts_permdir: "{{ platform_path }}/helm_charts"
keyring_permdir: "{{ platform_path }}/.keyring/{{ software_version }}"
patching_permdir: "/opt/patching"  # TODO(outbrito): Remove when CentOS deprecates
puppet_permdir: "{{ platform_path }}/puppet/{{ software_version }}"
sysinv_permdir: "{{ platform_path }}/sysinv/{{ software_version }}"

# Use plain paths or glob
backup:
  targets:
    - "/etc"
    - "/boot/1/kernel.env"
    - "/boot/efi/EFI/BOOT/boot.env"
    - "/var/lib/kubelet"
    - "{{ config_permdir }}"
    - "{{ deploy_permdir }}"
    - "{{ extension_permdir }}"
    - "{{ extra_permdir }}"
    - "{{ fernet_keys_permdir}}"
    - "{{ fluxcd_permdir }}"
    - "{{ helm_charts_permdir }}"
    - "{{ helm_overrides_permdir }}"
    - "{{ homedir }}"
    - "{{ keyring_permdir }}"
    - "{{ patching_permdir }}"  # TODO(outbrito): Remove when CentOS deprecates
    - "{{ puppet_permdir }}/hieradata"
    - "{{ postgres_dir.path }}"
    - "{{ sysinv_permdir }}"
    - "/var/luks/stx/luks_fs"
  exclude:
    - "/etc/selinux/**"
    - "/etc/selinux"
    - "/etc/udev/**"
    - "/etc/udev"
    - "/etc/openldap/certs.ldif"
    - "/var/lib/kubelet/plugins/**"
    - "/var/lib/kubelet/plugins"
    - "/var/lib/kubelet/pods/**"
    - "/var/lib/kubelet/pods"
    - "{{ homedir }}/*/ansible.log"
    - "{{ homedir }}/*/.ansibl**"
    - "{{ homedir }}/*/.cache/**"
    - "{{ homedir }}/*/.cache"
    - "{{ homedir }}/*/.kube/**"
    - "{{ homedir }}/*/.kube"

exclude_patches_glob: /opt/patching/**

# Image filesystem backup configurations
backup_registry_filesystem: false

image_backup:
  targets:
    - "/var/lib/docker-distribution"
