---
#
# Copyright (c) 2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
#   This role is to clear the old network configuration from the subcloud
#   in the post network reconfiguration
#

- name: Delete the admin address pool if the target network is mgmt
  shell: >-
    source /etc/platform/openrc; system addrpool-delete
    {{ admin_addrpool }}
  when: admin_addrpool and target_net == mgmt_net
