#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Ensure ceph user exists
  user:
    name: ceph
    create_home: false
    system: true

- name: Fix ceph runtime directory
  file:
    path: /var/run/ceph
    state: directory
    owner: ceph
    group: ceph
    mode: '0775'