#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Deprovision ceph-osd service
  command: sm-deprovision service-group-member --apply storage-services ceph-osd

- name: Migrate OSDs all at once
  include_tasks: migrate_single_osd.yaml
  loop: "{{ host_osd_info }}"
  loop_control:
    label: "Host {{ inventory_hostname }} OSD id = {{ item.osd_id }}"
  when: item.osd_objectstore == "filestore"

- name: Reload systemd
  systemd:
    daemon_reload: true

- name: "Start OSDs services"
  systemd:
    name: "ceph-osd@{{ item.osd_id }}.service"
    state: started
    enabled: true
  retries: 10
  delay: 10
  loop: "{{ host_osd_info }}"
  loop_control:
    label: "Host {{ inventory_hostname }} OSD id = {{ item.osd_id }}"

- name: Wait until OSDs are up
  command: ceph osd tree -f json
  register: ceph_osd_tree
  retries: 60
  delay: 10
  until: >
    ceph_osd_tree.stdout | from_json | json_query("nodes[?type=='osd'].status") is not none and
    (
      ceph_osd_tree.stdout | from_json | json_query("nodes[?type=='osd'].status")
    ) | select("equalto", "up") | list | length ==
    (
      ceph_osd_tree.stdout | from_json | json_query("nodes[?type=='osd'].status") | length
    )
  changed_when: false

- name: Wait until cluster finishes recovery
  command: ceph health -f json
  register: ceph_health
  retries: 360
  delay: 10
  until: >
    (
      ceph_health.stdout | from_json | json_query("status") == "HEALTH_OK"
    ) or
    (
      (
        ceph_health.stdout | from_json | json_query("checks")
      | dict2items
      | selectattr("value.severity", "equalto", "HEALTH_WARN")
      | list
      | length
      ) == 0
    )
  changed_when: false

- name: Wait until all PGs are active+clean
  command: timeout 30 ceph pg stat
  register: ceph_pg_stat
  until: >
    ceph_pg_stat.stdout is search('^([0-9]+) pgs: \\1 active\\+clean')
  retries: 120
  delay: 10
  changed_when: false

- name: Wait until the 'recover' keyword goes away from ceph status
  command: timeout 30 ceph -s
  register: ceph_status
  until: >
    'recover' not in ceph_status.stdout
  retries: 60
  delay: 10
  changed_when: false

- name: Display cluster status
  debug:
    var: ceph_status.stdout_lines

- name: Get OSD tree after migrating OSD
  command: timeout 30 ceph osd tree
  register: ceph_osd_tree_output
  changed_when: false

- name: Display OSD tree
  debug:
    var: ceph_osd_tree_output.stdout_lines
