---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rook-ceph-recovery
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get", "watch", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "patch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["list", "get", "patch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list", "get", "patch"]
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["patch", "get"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["list", "patch", "get"]
- apiGroups: ["apps"]
  resources: ["deployments/scale"]
  verbs: ["patch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["list", "watch", "get", "delete"]
- apiGroups: ["snapshot.storage.k8s.io"]
  resources: ["volumesnapshotcontents"]
  verbs: ["list"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["list"]
