#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

reinstall_files:
  - strip_to_storage_only.py
  - convert_storage_to_worker.py
  - set_worker_cpu_memory.py
  - remove_osds.py
  - add_kube_labels.py

minimum_platform_mem_workers: "7000"
