#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

all:
  hosts:
    localhost:
      ansible_connection: local

  vars:
    ansible_user: sysadmin
    ansible_python_interpreter: /usr/bin/python3
