---
#
# Copyright (c) 2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# ROLE DESCRIPTION:
#   This role is to do cleanup after IPsec is disabled on all hosts
#   in the system.
#

- name: Get system mode
  shell: source /etc/platform/platform.conf; echo $system_mode
  register: system_mode

- block:
  - name: Clear mgmt_ipsec flag in sysinv i_host table
    script: roles/common/files/clear-mgmt-ipsec-flag.py
    become_user: postgres

  - name: Get PXEBoot network list addresses
    script: roles/common/files/get_pxeboot_addr_list.py
    register: ip_addrs_list

  - set_fact:
      pxeboot_addrs: "{{ ip_addrs_list.stdout }}"

  - name: Disable IPsec cert renewal cronjob
    command: >-
      ansible all -i "{{ item }}," -m lineinfile -a "path=/var/spool/cron/crontabs/root
      regexp='.*20 .* /usr/bin/ipsec-cert-renew.sh$' state=absent" -b -e
      "ansible_ssh_user={{ ansible_ssh_user }} ansible_ssh_pass={{ ansible_ssh_pass }}
      ansible_become_pass={{ ansible_become_pass }}"
    loop: "{{ pxeboot_addrs }}"

  when: system_mode != "simplex"
