#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Get list of PVs CephFS
  shell: >
    kubectl get pv -o=jsonpath='{range .items[?(@.spec.cephfs)]}{.metadata.annotations.cephShare}{" "}{.spec.capacity.storage}{"\n"}{end}'
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  register: cephfs_pvs_raw
  changed_when: false
  check_mode: false

- name: Initialize ceph_subvolume_sizes_result dictionary
  set_fact:
    ceph_subvolume_sizes_result: "{{ ceph_subvolume_sizes_result | default({}) }}"

- name: Process PV lines and calculate bytes (Single Pass) and Merge
  set_fact:
    ceph_subvolume_sizes_result: >-
      {%- set existing_results = ceph_subvolume_sizes_result | default({}) -%}
      {%- set new_results = {} -%}
      {%- for item in cephfs_pvs_raw.stdout_lines -%}
        {%- if item | length > 0 and ' ' in item -%}
          {%- set line_parts = item.split(' ') -%}
          {%- set current_key = line_parts[0] | trim -%}
          {%- set raw_value = line_parts[1] | trim -%}
          {%- set num = raw_value | regex_replace('^(\\d+).*$', '\\1') | int -%}
          {%- set unit = raw_value | regex_replace('^\\d+', '') -%}
          {%- set factor =
              (1024**6) if unit == 'Ei' else
              (1024**5) if unit == 'Pi' else
              (1024**4) if unit == 'Ti' else
              (1024**3) if unit == 'Gi' else
              (1024**2) if unit == 'Mi' else
              (1024) if unit == 'Ki' else
              1
          -%}
          {%- set current_value_bytes = num * factor -%}
          {%- set _ = new_results.update({current_key: current_value_bytes}) -%}
        {%- endif -%}
      {%- endfor -%}
      {{ existing_results | combine(new_results) }}
