#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Copy rook-ceph manifests to remote
  copy:
    src: "{{ role_path_common }}/files/{{ item }}"
    dest: "{{ tmp_workspace }}/{{ item }}"
  loop: "{{ rook_ceph_manifests }}"

- name: Render rook-ceph manifests to remote
  template:
    src: "{{ role_path_common }}/templates/{{ item.name }}.j2"
    dest: "{{ tmp_workspace }}/{{ item.name }}"
  loop: "{{ rook_ceph_template_manifests }}"

- name: Apply config map with custom overrides
  command: kubectl apply -f {{ tmp_workspace }}/configmap-overrides.yaml
  environment:
    KUBECONFIG: "{{ kubeconfig }}"

- name: Apply Kubernetes manifests
  command: kubectl apply -f {{ tmp_workspace }}/crds.yaml -f {{ tmp_workspace }}/common.yaml -f {{ tmp_workspace }}/operator.yaml
  environment:
    KUBECONFIG: "{{ kubeconfig }}"

- name: Apply toolbox.yaml
  command: kubectl apply -f {{ tmp_workspace }}/toolbox.yaml
  environment:
    KUBECONFIG: "{{ kubeconfig }}"

- name: Set ceph-mon label to {{ hostvars[system.active_controller].host_with_mon_and_osd }}
  shell: kubectl label node {{ hostvars[system.active_controller].host_with_mon_and_osd }} ceph-mon=true --overwrite
  environment:
    KUBECONFIG: "{{ kubeconfig }}"

- name: Apply cluster.yaml
  command: kubectl apply -f {{ tmp_workspace }}/cluster.yaml
  environment:
    KUBECONFIG: "{{ kubeconfig }}"

- name: Wait for all rook-ceph-osd-prepare jobs to be created
  include_tasks: "{{ role_path_common }}/tasks/kubernetes/wait_resources_condition.yaml"
  vars:
    k8s_namespace: "rook-ceph"
    k8s_resource_prefix: "osd-prepare"
    k8s_retries: 120
    wait_mode: "created"
    fact_name: "osd_prepare_jobs"

- name: Wait for all rook-ceph-osd-prepare jobs to be completed
  include_tasks: "{{ role_path_common }}/tasks/kubernetes/wait_resources_condition.yaml"
  vars:
    k8s_namespace: "rook-ceph"
    k8s_resource_list: "{{ osd_prepare_jobs }}"
    wait_mode: "complete"

