#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: "Ensure {{ tmp_workspace }} exist"
  file:
    path: "{{ tmp_workspace }}"
    state: directory

- name: Create Rook configured flag
  file:
    path: /etc/platform/.node_rook_configured
    state: touch
    modification_time: preserve
    access_time: preserve

- block:
  - name: Create rook-ceph-mon secret if does not exists
    include_tasks: create_mon_secret.yaml

  - name: Create default-registry-key secret if does not exists
    include_tasks: create_registry_secret.yaml

  - name: Create Rook-Ceph with Pacific Ceph version
    include_tasks: create_pacific_rook.yaml
  when: inventory_hostname in groups.active_controller

- name: Cleanup temporary rook-ceph folder
  file:
    path: "{{ tmp_workspace }}"
    state: absent
