#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Remove pmon.d ceph files
  shell: rm -vrf /etc/pmon.d/ceph*
  register: cleanup_pmon_files_output
  changed_when: cleanup_pmon_files_output.stdout_lines | length > 0

- name: Display files removed from pmon
  debug:
    var: cleanup_pmon_files_output.stdout_lines
  when: cleanup_pmon_files_output.stdout_lines | length > 0

- name: Give pmon a few extra seconds to identify the changes
  pause:
    seconds: 12
  run_once: true
  delegate_to: "{{ system.active_controller }}"
  changed_when: false
