#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Remove storage-backend {{ backend_name }}
  command: system storage-backend-delete {{ backend_name }} --force
  environment: "{{ system_env }}"
  register: cmd_result
  failed_when:
    - cmd_result.rc != 0
    - "'Backend ' ~ backend_name ~ ' is not found.' not in (cmd_result.stderr | default(''))"
  changed_when: "'Backend ' ~ backend_name ~ ' is not found.' not in (cmd_result.stderr | default(''))"
