#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Get list of host profiles not used by any host
  shell: |
    set -o pipefail
    ALL_PROFILES=$(kubectl get hostprofiles -n deployment -o jsonpath='{.items[*].metadata.name}' | tr ' ' '\n' | sort)
    USED_PROFILES=$(kubectl get hosts -n deployment -o jsonpath='{.items[*].spec.profile}' | tr ' ' '\n' | sort -u)
    comm -23 <(echo "$ALL_PROFILES") <(echo "$USED_PROFILES")
  args:
    executable: /bin/bash  # Required for <( )
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  register: profile_list_to_delete
  changed_when: false
  failed_when: false

- name: Display profile list to delete
  debug:
    var: profile_list_to_delete.stdout_lines
  when:
    - profile_list_to_delete.rc == 0
    - profile_list_to_delete.stdout_lines | length > 0

- name: Delete list of host profiles not used by any host
  command: kubectl delete hostprofile -n deployment {{ item }} --ignore-not-found
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  loop: "{{ profile_list_to_delete.stdout_lines }}"
  loop_control:
    label: "{{ item }}"
  when:
    - profile_list_to_delete.rc == 0
    - profile_list_to_delete.stdout_lines | length > 0
