#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-config-override
  namespace: rook-ceph
data:
  config: |

    [global]
    osd_pool_default_size = 1
    osd_pool_default_min_size = 1
    osd_pool_default_pg_num = 64
    osd_pool_default_pgp_num = 64
    mon_max_pg_per_osd = 2048

    [osd]
    bluestore_fsck_quick_fix_on_mount = true

    [mon]
    mon warn on legacy crush tunables = false
    mon pg warn max per osd = 2048
    mon pg warn max object skew = 0
    mon clock drift allowed = .1
    mon warn on pool no redundancy = false
    mon warn on insecure global id reclaim allowed = false
    mon warn on insecure global id reclaim = false
