---
fluxcd_namespace: flux-helm
fluxcd_secret_name: default-registry-key
fluxcd_resource_dir: /tmp/fluxcd
flux_charts_path: /usr/local/share/flux2-charts/flux2-2.15.0.tgz
flux_helm_release_name: fluxcd
flux_helm_controller_image: docker.io/fluxcd/helm-controller
flux_helm_controller_tag: v1.2.0
flux_helm_controller_liveness_timeout: 5
flux_helm_controller_readiness_timeout: 10
flux_helm_controller_memory_request: 0
flux_source_controller_image: docker.io/fluxcd/source-controller
flux_source_controller_tag: v1.5.0
flux_source_controller_liveness_timeout: 5
flux_source_controller_readiness_timeout: 10
flux_source_controller_memory_request: 0
flux_notification_controller_image: ghcr.io/fluxcd/notification-controller
flux_notification_controller_tag: v1.5.0
flux_notification_controller_liveness_timeout: 5
flux_notification_controller_readiness_timeout: 10
flux_notification_controller_memory_request: 0
flux_kustomize_controller_image: ghcr.io/fluxcd/kustomize-controller
flux_kustomize_controller_tag: v1.5.1
flux_kustomize_controller_liveness_timeout: 5
flux_kustomize_controller_readiness_timeout: 10
flux_kustomize_controller_memory_request: 0
flux_legacy_charts_path: /usr/local/share/flux2-charts-legacy/flux2-2.13.0.tgz
flux_legacy_helm_controller_tag: v1.0.1
flux_legacy_source_controller_tag: v1.3.0
local_registry: registry.local:9001
async_timeout: 240
async_retries: 80
bringup_fluxcd_retries: 5
check_kubernetes_health_retries: 5
delay_time: 6
fluxcd_retries: 5
enable_notification_controller: false
enable_kustomize_controller: false
