#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Main execution block
  block:
    - include_tasks: "{{ role_path_common }}/tasks/checkpoint.yaml"

  rescue:
    - name: Clear Facts Cache (Ansible Cache)
      meta: clear_facts

    - name: Clear Facts Cache (Ansible Cache) for localhost in dynamic place
      file:
        path: "~/.storage-backend-migration-ansible-cache/localhost"
        state: absent
      delegate_to: localhost
      become: false
      ignore_errors: true

    - name: Clear Facts Cache (Ansible Cache) for localhost in a fixed place
      file:
        path: "/home/sysadmin/.storage-backend-migration-ansible-cache/localhost"
        state: absent
      delegate_to: localhost
      become: false
      ignore_errors: true

    - name: Show that cleanup is complete
      debug:
        msg: "The checkpoint tasks failed and the Ansible facts cache has been cleared."

    - name: Force play failure after cleanup
      fail:
        msg: "Final failure after cache cleanup."
