---
# System images that are pre-pulled and pushed to local registry
n3000_opae_img: docker.io/starlingx/n3000-opae:stx.8.0-v1.0.2
kubernetes_entrypoint_img: quay.io/airshipit/kubernetes-entrypoint:9ff5d2e488ad18187bccc48e9595f197d27110c4-ubuntu_jammy
calico_cni_img: quay.io/calico/cni:v3.31.5
calico_node_img: quay.io/calico/node:v3.31.5
calico_kube_controllers_img: quay.io/calico/kube-controllers:v3.31.5
# New Calico/Tigera images
calico_apiserver_img: quay.io/calico/apiserver:v3.31.5
calico_ctl_img: quay.io/calico/ctl:v3.31.5
calico_csi_img: quay.io/calico/csi:v3.31.5
calico_dikastes_img: quay.io/calico/dikastes:v3.31.5
calico_envoy_gateway_img: quay.io/calico/envoy-gateway:v3.31.5
calico_envoy_proxy_img: quay.io/calico/envoy-proxy:v3.31.5
calico_goldmane_img: quay.io/calico/goldmane:v3.31.5
calico_node_driver_registrar_img: quay.io/calico/node-driver-registrar:v3.31.5
calico_pod2daemon_flexvol_img: quay.io/calico/pod2daemon-flexvol:v3.31.5
calico_typha_img: quay.io/calico/typha:v3.31.5
calico_whisker_backend_img: quay.io/calico/whisker-backend:v3.31.5
calico_whisker_img: quay.io/calico/whisker:v3.31.5
tigera_operator_img: quay.io/tigera/operator:v1.40.12

multus_img: ghcr.io/k8snetworkplumbingwg/multus-cni:v4.2.4-thick
sriov_cni_img: ghcr.io/k8snetworkplumbingwg/sriov-cni:v2.10.0
sriov_network_device_img: ghcr.io/k8snetworkplumbingwg/sriov-network-device-plugin:v3.11.0
# Nginx images
nginx_ingress_controller_img: registry.k8s.io/ingress-nginx/controller:v1.15.1
nginx_kube_webhook_certgen_img: registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.6.9
default_backend_img: registry.k8s.io/defaultbackend-amd64:1.5
# Cert-manager images
cert_manager_acmesolver_img: quay.io/jetstack/cert-manager-acmesolver:v1.20.2
cert_manager_cainjector_img: quay.io/jetstack/cert-manager-cainjector:v1.20.2
cert_manager_controller_img: quay.io/jetstack/cert-manager-controller:v1.20.2
cert_manager_webhook_img: quay.io/jetstack/cert-manager-webhook:v1.20.2
cert_manager_startupapicheck_img: quay.io/jetstack/cert-manager-startupapicheck:v1.20.2
# Keep the snapshot-controller image in sync with the one provided at:
# cluster/addons/volumesnapshots/volume-snapshot-controller/volume-snapshot-controller-deployment.yaml
# in the kubernetes github repo
snapshot_controller_img: registry.k8s.io/sig-storage/snapshot-controller:v8.1.0
pause_img: registry.k8s.io/pause:3.10.1
flux_helm_controller_img: docker.io/fluxcd/helm-controller:v1.5.3
flux_source_controller_img: docker.io/fluxcd/source-controller:v1.8.1
flux_notification_controller_img: ghcr.io/fluxcd/notification-controller:v1.8.2
flux_kustomize_controller_img: ghcr.io/fluxcd/kustomize-controller:v1.8.2
# oidc-auth-apps images
oidc_stx_oidc_client_img: docker.io/starlingx/stx-oidc-client:stx.13.0-v1.0.12-@OS_CODENAME@
oidc_dex_img: ghcr.io/dexidp/dex:v2.45.1
oidc_curl_img: docker.io/curlimages/curl:8.19.0
oidc_busybox_img: docker.io/library/busybox:1.37.0
