#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

---
apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
  - name: default-registry-key
metadata:
  name: ceph-wipe-disks
  namespace: rook-ceph
