---
#
# Copyright (c) 2023-2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# ROLE DESCRIPTION:
#   These tasks are used to prepare environment on the target host for
#   packages/ostree_repo prestaging.
#

# When is prestage_source local vs. remote?
# - local: if we are prestaging the same software version as currently running on system controller
# - remote: if we are prestaging a different software version than currently running on system controller

- name: Set the feed directory to /var/www/pages/feed (Debian)
  set_fact:
    release_feed: "/var/www/pages/feed/rel-{{ software_version }}"

# Prepare prestage ostree_repo
- name: Set the source of ostree_repo
  set_fact:
    ostree_repo_release_feed: "{{ release_feed }}/ostree_repo"

- name: Check if {{ ostree_repo_release_feed }} exists on {{ inventory_hostname }}
  stat:
    path: "{{ ostree_repo_release_feed }}"
  register: ostree_repo_release_feed_result

# From the subcloud perspective, we need to check if the ostree directory for
# release N exists. This is necessary to determine if the subcloud is N-1,
# in which the ostree directory for prestaged release N does not exist.
- name: Set flag to indicate if the host ostree repo dir exist
  set_fact:
    host_ostree_dir_exist: "{{ ostree_repo_release_feed_result.stat.exists }}"

- name: Check if {{ host_software_metadata_dir }} exists on {{ inventory_hostname }}
  stat:
    path: "{{ host_software_metadata_dir }}"
  register: host_software_dir_result

- name: Set flag to indicate if the host software dir exist
  set_fact:
    host_software_exist: "{{ host_software_dir_result.stat.exists }}"

- name: Check if {{ host_patch_metadata_dir }} exists on {{ inventory_hostname }}
  stat:
    path: "{{ host_patch_metadata_dir }}"
  register: host_patch_dir_result

- name: Set flag to indicate if the host patches exist
  set_fact:
    host_patches_exist: "{{ host_patch_dir_result.stat.exists }}"

# The force_ostree_dir_sync flag determines whether the entire N release ostree
# directory should be copied to the subcloud or not. This flag is only relevant
# if the subcloud is running N-1 release.
# The condition for it to be true must meet:
#   - The release of the subcloud must be different from the release being
#     prestaged.
#   - The release of the subcloud must be a N-1 release that is USM enabled.
#   - The N release ostree directory does not already exist on the N-1 subcloud.
- name: Set flag to indicate if subcloud prestage is for N-1 scenario
  set_fact:
    force_ostree_dir_sync: "{{ 'true' if (prestage_source == 'remote' and
                                host_software_version is version('22.12', '=') and
                                not host_ostree_dir_exist) else 'false' }}"
- debug:
    msg: |
      Prestaging type: {{ prestage_type }}
      Prestaging reason: {{ prestage_reason }}
      Prestaging source: {{ prestage_source }}
      Prestaging os type: {{ prestage_os_type }}
      Prestaging for N-1 subcloud: {{ force_ostree_dir_sync }}
      Release feed directory (on target): {{ release_feed|default('N/A') }}
