#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: "Check {{ migration_target }} export-import cases"
  include_tasks: "{{ migration_target }}/main.yaml"
