---
platform_conf_path: /etc/platform
deploy_permdir: /opt/platform/deploy
helm_charts_permdir: /opt/platform/helm_charts
extension_permdir: /opt/extension
dc_vault_permdir: /opt/dc-vault
ldap_permdir_centos: /var/lib/openldap-data
ldap_permdir_debian: /var/lib/ldap
fernet_keys_permdir: /opt/platform/keystone/fernet-keys
crushmap_file: crushmap.bin.backup
crushmap_file_tmp: crushmap.bin.tmp
skip_ceph_osds_wipe_flag: /etc/platform/.skip_ceph_osds_wipe
restore_extra_items: []

# The staging area to process the data from the backup tarball
# after bootstrap controller-0 is done during the restore.
staging_dir: /opt/backups

# Flag file to indicate if ceph or rook backend is present
ceph_backend_flag: "{{ platform_conf_path }}/.node_ceph_configured"
rook_backend_flag: "{{ platform_conf_path }}/.node_rook_configured"
