#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Query none hosts
  become_user: postgres
  command: |
    psql -d sysinv -t -A -c \
    "SELECT id, hostname, personality, administrative, operational, availability
    FROM i_host
    WHERE hostname IS NULL OR personality IS NULL;"
  register: none_hosts_output
  changed_when: false

- name: Fail if there are none host entries
  fail:
    msg: |
      There are hosts entries in host-list with none values:
      {{ none_hosts_output.stdout_lines | trim | replace('\\n', '\n') }}
      Please delete them before migrating.
  when: none_hosts_output.stdout_lines | length > 0
