#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Check for flag .backup_in_progress
  stat:
    path: /etc/platform/.backup_in_progress
  register: backup_in_progress_flag

- name: Fail if there is a backup in progress
  fail:
    msg: >-
      Backup is in progress.
      Please complete the backup before migrating.
  when: backup_in_progress_flag.stat.exists

- name: Check for flag .restore_in_progress
  stat:
    path: /etc/platform/.restore_in_progress
  register: restore_in_progress_flag

- name: Fail if there is a restore in progress
  fail:
    msg: >-
      Restore is in progress.
      Please complete the restore before migrating.
  when: restore_in_progress_flag.stat.exists
