#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Display system alarms if any
  include_tasks: "display_alarms.yaml"

- name: Check if any applications are in a undesired state
  include_tasks: "check_any_applications_state.yaml"

- name: Check Ceph cluster health
  include_tasks: "check_ceph_cluster_health.yaml"

- name: Check platform-integ-apps is applied
  include_tasks: "check_platform_integ_apps.yaml"

- name: Check deployment-manager is applied
  include_tasks: "check_dm_app.yaml"

- name: Check openstack app is not applied
  include_tasks: "check_openstack_app.yaml"
  when: block_openstack_app | bool

- name: Check for none hosts
  include_tasks: "check_none_hosts.yaml"

- name: Check if hosts are unlocked/enabled/available
  include_tasks: "check_hosts_ready.yaml"

- name: Check if hosts are in-sync and reconciled
  include_tasks: "check_hosts_in_sync_reconciled.yaml"

- name: Check if system is in-sync and reconciled
  include_tasks: "check_system_in_sync_reconciled.yaml"

- name: Check if there is a backup or restore in progress
  include_tasks: "check_backup_or_restore_in_progress.yaml"

- name: "Check if there is sufficient space in {{ storage_backend_migration_backup_dir }}"
  include_tasks: "check_migration_backup_dir.yaml"

- name: Check if there is sufficient space in /var
  include_tasks: "check_var_space.yaml"

- name: Check if there is sufficient space in cgts-vg
  include_tasks: "check_cgtsvg_space.yaml"
  vars:
    min_required_free_gib: "{{ cgts_vg_min_required_free_gib }}"

- name: Check if there is not allowed pools
  include_tasks: check_allowed_pools.yaml

- name: Check if all pools have required values
  include_tasks: check_pools_values.yaml

- name: Check if there is a upgrade in progress
  include_tasks: "check_upgrade_in_progress.yaml"

- name: Check if any pods are using Ceph PVCs
  include_tasks: "check_ceph_pvcs.yaml"

- name: Check if any VolumeSnapshot is not ready
  include_tasks: "check_volume_snapshots.yaml"
