#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Remove pmon.d files
  include_tasks: "{{ role_path_common }}/tasks/remove_pmon_files.yaml"

- name: Check for flag .node_ceph_configured
  stat:
    path: /etc/platform/.node_ceph_configured
  register: node_ceph_configured_flag
