#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Cleanup ceph files
  shell: >
    rm -vrf
    /var/lib/ceph/*
    /opt/platform/ceph/
    /etc/platform/.ceph-mon-lv
    /run/ceph/
    /run/ceph_hang/
    /var/log/ceph/*
    /var/log/ceph-manager.log
    /var/lib/systemd/coredump/core.ceph-*
    /opt/platform/sysinv/{{ system.sw_version }}/.crushmap_applied
  register: cleanup_ceph_files_output
  ignore_errors: true

- name: Display files removed
  debug:
    var: cleanup_ceph_files_output.stdout_lines
  when: cleanup_ceph_files_output.stdout_lines | length > 0

# We need to avoid removing ceph.conf otherwise puppet fails
# when creating the floating monitor
- name: Cleanup /etc/ceph directory except ceph.conf
  shell: find /etc/ceph -mindepth 1 ! -name 'ceph.conf' -exec rm -rfv {} +
  register: cleanup_etc_ceph_output
  ignore_errors: true

- name: Display files removed from /etc/ceph
  debug:
    var: cleanup_etc_ceph_output.stdout_lines
  when: cleanup_etc_ceph_output.stdout_lines | length > 0

# We need to make sure this directory exists otherwise puppet fails
# when creating the floating monitor
- name: Recreate ceph metadata OSD dir
  become: true
  file:
    path: "/var/lib/ceph/osd"
    state: directory
    mode: 0755
