#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Remove pmon.d SM file
  shell: rm -vrf /etc/pmon.d/sm.conf
  register: cleanup_pmon_files_output
  changed_when: cleanup_pmon_files_output.stdout_lines | length > 0

- name: Give pmon a few extra seconds to identify the changes
  pause:
    seconds: 12
  run_once: true
  delegate_to: "{{ system.active_controller }}"
  changed_when: false

- name: Cleanup ceph services
  include_tasks: cleanup_ceph_services.yaml

- name: Deprovision Services
  include_tasks: deprovision_services.yaml
  when: inventory_hostname in groups.controllers

- name: Stop ceph services
  include_tasks: stop_ceph_services.yaml

- name: Retrieve all ceph backends aside from original
  become: true
  become_user: postgres
  command: >
    psql -d sysinv -t -A -c "
    SELECT name FROM storage_backend WHERE backend='ceph' AND name!='ceph-store';"
  register: ceph_backends
  changed_when: false
  when: inventory_hostname in groups.active_controller

- name: Convert storage-backend to ceph-rook
  become: true
  become_user: postgres
  command: >
    psql -d sysinv -c "
    BEGIN;
    DELETE FROM storage_ceph;
    UPDATE storage_backend
      SET name = 'ceph-rook-store',
          backend = 'ceph-rook',
          state = 'configuring-with-app',
          services = 'block,filesystem',
          capabilities = (
            capabilities::jsonb || '{\"deployment_model\": \"{{ deployment_model }}\", \"replication\": \"{{ pool_size }}\", \"min_replication\": \"{{ pool_minsize }}\"}'::jsonb
          )::text
      WHERE id = {{ storage_backend.id }};
    INSERT INTO storage_ceph_rook (id) VALUES ({{ storage_backend.id }}) ON CONFLICT (id) DO NOTHING;
    UPDATE storage_tiers SET forbackendid = NULL WHERE forbackendid IN (SELECT id FROM storage_backend WHERE id != {{ storage_backend.id }} AND backend = 'ceph');
    DELETE FROM storage_backend WHERE id != {{ storage_backend.id }} AND backend = 'ceph';
    COMMIT
    "
  vars:
    storage_backend: "{{ hostvars[system.active_controller].storage_backend }}"
    deployment_model: "{{ hostvars[system.active_controller].deployment_model }}"
  when:
    - inventory_hostname in groups.active_controller
    - migration_target == "rook_ceph"

- name: Convert storage-backend to lvm
  become: true
  become_user: postgres
  command: >
    psql -d sysinv -c "
    BEGIN;
    DELETE FROM storage_ceph;
    UPDATE i_idisk SET foristorid = NULL WHERE foristorid IN (SELECT id FROM i_istor WHERE function = 'osd');
    DELETE FROM i_istor WHERE function = 'osd';
    DELETE FROM storage_tiers WHERE type = 'ceph';
    DELETE FROM clusters WHERE name = 'ceph_cluster';
    UPDATE storage_backend
      SET name = 'lvm-store',
          backend = 'lvm',
          state = 'configuring-with-app',
          services = NULL,
          capabilities = (
            jsonb_build_object(
              'migration_target', capabilities::jsonb->'migration_target',
              'migration_type', capabilities::jsonb->'migration_type',
              'migration_step', capabilities::jsonb->'migration_step',
              'migration_status', capabilities::jsonb->'migration_status'
            )
          )::text
      WHERE id = {{ storage_backend.id }};
    INSERT INTO storage_lvm (id) VALUES ({{ storage_backend.id }}) ON CONFLICT (id) DO NOTHING;
    DELETE FROM storage_backend WHERE id != {{ storage_backend.id }} AND backend = 'ceph';
    COMMIT
    "
  vars:
    storage_backend: "{{ hostvars[system.active_controller].storage_backend }}"
  when:
    - inventory_hostname in groups.active_controller
    - migration_target == "lvm"

- name: Remove Ceph backends aside from original
  vars:
    backend_name: "{{ item  }}"
  include_tasks: "{{ role_path_common }}/tasks/remove_backend.yaml"
  loop: "{{ ceph_backends.stdout_lines }}"
  loop_control:
    label: "{{ item }}"
  when:
    - inventory_hostname in groups.active_controller
    - ceph_backends.stdout_lines | length > 0

- name: Remove platform-integ-apps Application
  vars:
    app_name: platform-integ-apps
    force: false
  include_tasks: "{{ role_path_common }}/tasks/remove_app.yaml"
  when: inventory_hostname in groups.active_controller

- name: Cleanup k8s resources
  include_tasks: cleanup_resource_k8s.yaml
  when: inventory_hostname in groups.active_controller

- name: Cleanup ceph config
  include_tasks: cleanup_ceph_config.yaml

- name: Cleanup database
  include_tasks: cleanup_database.yaml
  when: inventory_hostname in groups.active_controller

- name: Umount OSDs
  include_tasks: umount_osds.yaml
  when: inventory_hostname in groups.with_osds

- name: Cleanup ceph files
  include_tasks: cleanup_ceph_files.yaml

- name: Wait before running deprovision again
  pause:
    seconds: 15
  run_once: true
  delegate_to: "{{ system.active_controller }}"
  changed_when: false

- name: Deprovision Services
  include_tasks: deprovision_services.yaml
  when: inventory_hostname in groups.controllers

- name: Create symbolic link for sm.conf
  file:
    dest: /etc/pmon.d/sm.conf
    src: /usr/share/starlingx/pmon.d/sm.conf
    state: link
  when: inventory_hostname in groups.controllers
