#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Delete stx-ceph-manager pod
  command: kubectl delete pod -n rook-ceph -l app=stx-ceph-manager --ignore-not-found
  environment:
    KUBECONFIG: "{{ kubeconfig }}"

- name: Delete ceph-mgr-provision pod
  command: kubectl delete pod -n rook-ceph -l job-name=ceph-mgr-provision --ignore-not-found
  environment:
    KUBECONFIG: "{{ kubeconfig }}"

- name: Delete ceph-sync-osds pod
  command: kubectl delete pod -n rook-ceph -l job-name=ceph-sync-osds --ignore-not-found
  environment:
    KUBECONFIG: "{{ kubeconfig }}"

- name: Remove ceph-mon-lv mount from /etc/fstab (detect by ceph-mon-lv)
  lineinfile:
    path: /etc/fstab
    regexp: '.*ceph-mon-lv.*'
    state: absent
  become: true