#
# Copyright (c) 2025 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Delete cephfilesystem kube-cephfs
  command: kubectl delete -f {{ tmp_workspace }}/filesystem.yaml --ignore-not-found
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  register: async_deletion
  async: 1800
  poll: 0

- name: Remove finalizer from cephfilesystem kube-cephfs
  command: >
    kubectl patch -n rook-ceph cephfilesystem kube-cephfs
    -p '{"metadata":{"finalizers":null}}'
    --type=merge
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  ignore_errors: true

- name: Wait for all deletion of cephfilesystem kube-cephfs
  async_status:
    jid: "{{ async_deletion.ansible_job_id }}"
  register: wait_result
  until: wait_result.finished
  retries: 60
  delay: 10
